-- ******************************** SqlDBM: Databricks *******************************
-- * Generated by SqlDBM: Databricks Demo 67, v14 vs v13 by eric.ruiz+yew@sqldbm.com *

ALTER TABLE Products
  ADD COLUMN ProductExample string;
ALTER TABLE Products
ALTER COLUMN ProductExample SET NOT NULL;