-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Workshop Project ERUIZ , v19 vs v17 by eric.ruiz+yew@sqldbm.com *

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    SET COMMENT = 'Audit log fact table tracking user actions and changes across the supply chain system, providing a comprehensive record of system interactions and modifications.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN USERID COMMENT 'Unique identifier of the user who performed the action, linking the audit log to the specific user account responsible for the system interaction.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN AUDITID COMMENT 'Unique sequential identifier for each audit log entry, serving as the primary tracking mechanism for individual system events and changes.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN ACTION COMMENT 'Descriptive text indicating the specific action performed in the system, such as ''Create'', ''Update'', ''Delete'', or ''View'', providing context for the logged event.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN ACTIONDATE COMMENT 'Calendar date when the system action was performed, allowing for date-based filtering and historical tracking of system events.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN ACTIONTIME COMMENT 'Precise timestamp capturing the exact moment of the system action, enabling granular time-based analysis and event sequencing.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN ENTITYAFFECTED COMMENT 'Name or type of the system entity (e.g., ''Inventory'', ''Order'', ''Product'') that was modified or interacted with during the logged action.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN ENTITYID COMMENT 'Unique identifier of the specific entity instance that was affected by the user action, providing a direct link to the modified record.';

ALTER TABLE SUPPLYCHAIN.AUDITLOGFACT_T
    ALTER COLUMN NOTES COMMENT 'Additional contextual information or details about the action, allowing for supplementary explanations or system-generated notes related to the event.';