-- ************************* SqlDBM: Microsoft SQL Server *************************
-- * Generated by SqlDBM: SqlServer Demo 78, v5 vs v4 by eric.ruiz+yew@sqldbm.com *

ALTER TABLE [dbo].[OfferingType]
    ADD [column1] smallint NOT NULL;