-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Data Warehouse, Dev vs v8 by eric.ruiz@sqldbm.com *

DROP TABLE EDW.FactResellerSales;

DROP TABLE EDW.FactInternetSales;

DROP TABLE EDW.DimProduct;

DROP TABLE EDW.NewFactCurrencyRate;

DROP TABLE EDW.FactSurveyResponse;

DROP TABLE EDW.FactFinance;

DROP TABLE EDW.FactCurrencyRate;

DROP TABLE EDW.DimReseller;

DROP TABLE EDW.DimProductSubcategory;

DROP TABLE EDW.DimCustomer;

DROP TABLE testing123;

DROP TABLE testing;

DROP TABLE EDW.FactSalesQuota;

DROP TABLE EDW.DimScenario;

DROP TABLE EDW.DimProductCategory;

DROP TABLE EDW.DimOrganization;

DROP TABLE EDW.DimGeography;

DROP TABLE EDW.DimEmployee;

DROP TABLE EDW.DimDepartmentGroup;

DROP TABLE EDW.DimDateClone;

DROP TABLE EDW.DimCurrency;

DROP TABLE EDW.DimAccount_Test;

DROP TABLE EDW.DimAccount;

DROP VIEW view_1;

DROP VIEW EDW.DIM_PRODUCT_CAT_SUBCAT_V;

CREATE SCHEMA GOLDLAYER;

DROP SCHEMA EDW;

CREATE TABLE GOLDLAYER.STG_PARTSUPP_DIM_PART_DIM_SUPPLIER_DIM_CUSTOMER_STG_LINEITEM_STG_ORDERS
(
 PS_PARTKEY      float NOT NULL,
 PS_SUPPKEY      float NOT NULL,
 PS_AVAILQTY     float NOT NULL,
 PS_SUPPLYCOST   float NOT NULL,
 PS_COMMENT      varchar(199) NOT NULL,
 P_PARTKEY       float NOT NULL,
 P_NAME          varchar(55) NOT NULL,
 P_MFGR          varchar(25) NOT NULL,
 P_BRAND         varchar(10) NOT NULL,
 P_TYPE          varchar(25) NOT NULL,
 P_SIZE          float NOT NULL,
 P_CONTAINER     varchar(10) NOT NULL,
 P_RETAILPRICE   float NOT NULL,
 P_COMMENT       varchar(23) NOT NULL,
 S_SUPPKEY       float NOT NULL,
 S_NAME          varchar(25) NOT NULL,
 S_ADDRESS       varchar(40) NOT NULL,
 S_NATIONKEY     float NOT NULL,
 S_PHONE         varchar(15) NOT NULL,
 S_ACCTBAL       float NOT NULL,
 S_COMMENT       varchar(101) NOT NULL,
 C_CUSTKEY       float NOT NULL,
 C_NAME          varchar(25) NOT NULL,
 C_ADDRESS       varchar(40) NOT NULL,
 C_NATIONKEY     float NOT NULL,
 C_PHONE         varchar(15) NOT NULL,
 C_ACCTBAL       float NOT NULL,
 C_MKTSEGMENT    varchar(10) NOT NULL,
 C_COMMENT       varchar(117) NOT NULL,
 L_ORDERKEY      float NOT NULL,
 L_PARTKEY       float NOT NULL,
 L_SUPPKEY       float NOT NULL,
 L_LINENUMBER    float NOT NULL,
 L_QUANTITY      float NOT NULL,
 L_EXTENDEDPRICE float NOT NULL,
 L_DISCOUNT      float NOT NULL,
 L_TAX           float NOT NULL,
 L_RETURNFLAG    varchar(1) NOT NULL,
 L_LINESTATUS    varchar(1) NOT NULL,
 L_SHIPDATE      date NOT NULL,
 L_COMMITDATE    date NOT NULL,
 L_RECEIPTDATE   date NOT NULL,
 L_SHIPINSTRUCT  varchar(25) NOT NULL,
 L_SHIPMODE      varchar(10) NOT NULL,
 L_COMMENT       varchar(44) NOT NULL,
 O_ORDERKEY      float NOT NULL,
 O_ORDERSTATUS   varchar(1) NOT NULL,
 O_TOTALPRICE    float NOT NULL,
 O_ORDERDATE     date NOT NULL,
 O_ORDERPRIORITY varchar(15) NOT NULL,
 O_CLERK         varchar(15) NOT NULL,
 O_SHIPPRIORITY  float NOT NULL,
 O_COMMENT       varchar(79) NOT NULL,
 __LOAD_DATE_4   date NOT NULL COMMENT 'LOAD DATE'
);

CREATE TABLE GOLDLAYER.DIM_SUPPLIER
(
 S_SUPPKEY        float,
 S_NAME           varchar(25),
 S_ADDRESS        varchar(40),
 S_NATIONKEY      float,
 S_PHONE          varchar(15),
 S_ACCTBAL        float,
 S_COMMENT        varchar(101),
 __LOAD_DATE      date COMMENT 'LOAD DATE',
 LOAD_DATE        date COMMENT 'LOAD DATE',
 COL_W_EXPERSSION date COMMENT 'A COLUMN WITH EXPRESSION'
);

CREATE TABLE GOLDLAYER.DIM_PART
(
 P_PARTKEY        float,
 P_NAME           varchar(55),
 P_MFGR           varchar(25),
 P_BRAND          varchar(10),
 P_TYPE           varchar(25),
 P_SIZE           float,
 P_CONTAINER      varchar(10),
 P_RETAILPRICE    float,
 P_COMMENT        varchar(23),
 __LOAD_DATE      date COMMENT 'LOAD DATE',
 LOAD_DATE        date COMMENT 'LOAD DATE',
 COL_W_EXPERSSION varchar(16777216) COMMENT 'A COLUMN WITH EXPRESSION'
);

CREATE TABLE GOLDLAYER.DIM_CUSTOMER
(
 C_CUSTKEY        float,
 C_NAME           varchar(25),
 C_ADDRESS        varchar(40),
 C_NATIONKEY      float,
 C_PHONE          varchar(15),
 C_ACCTBAL        float,
 C_MKTSEGMENT     varchar(10),
 C_COMMENT        varchar(117),
 __LOAD_DATE      date COMMENT 'LOAD DATE',
 LOAD_DATE        date COMMENT 'LOAD DATE',
 COL_W_EXPERSSION date COMMENT 'A COLUMN WITH EXPRESSION'
);