-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.RETENTION_PERIOD
CREATE TAG SUPPLYCHAIN.RETENTION_PERIOD ALLOWED_VALUES '7 YEARS';
