-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.ACCESS_LEVEL
CREATE TAG SUPPLYCHAIN.ACCESS_LEVEL ALLOWED_VALUES 'RESTRICTED';
