-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 78 by eric.ruiz+yew@sqldbm.com *

-- **************************************  ACMECORP.SUPPLYCHAIN.ACCESS_LEVEL
CREATE TAG ACMECORP.SUPPLYCHAIN.ACCESS_LEVEL ALLOWED_VALUES 'RESTRICTED';
