-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 35 by eric.ruiz+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.RETENTION_PERIOD
CREATE TAG SUPPLYCHAIN.RETENTION_PERIOD ALLOWED_VALUES '7 YEARS';
