-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CUSTOMER_DT
CREATE DYNAMIC TABLE SUPPLYCHAIN.CUSTOMER_DT
(
 ID          COMMENT 'Unique identifier for the customer record in this table',
 REGION      COMMENT 'Geographic region or territory assigned to the customer',
 CREATED_AT  COMMENT 'Timestamp when the record was created or loaded'
)
COMMENT = 'Staging or data transfer table for customer records with regional classification and timestamp tracking for ETL processes.'
WAREHOUSE = DEMO_WH
TARGET_LAG = '10 MINUTES'
INITIALIZE = ON_CREATE
REFRESH_MODE = FULL
  AS SELECT 
    c.customerid AS id,             -- map CUSTOMERID → id
    c.country   AS region,          -- map COUNTRY → region
    CURRENT_TIMESTAMP AS created_at -- add system timestamp
FROM supplychain.customer c;
