-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 78 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERS_HT
CREATE HYBRID TABLE SUPPLYCHAIN.ORDERS_HT
(
 ORDER_ID        number(38,0) NOT NULL AUTOINCREMENT START 1000 INCREMENT 1 COMMENT 'Unique order identifier',
 CUSTOMER_ID     number(38,0) NOT NULL COMMENT 'Customer identifier',
 PRODUCT_ID      number(38,0) NOT NULL COMMENT 'Product identifier',
 QUANTITY        number(38,0) NOT NULL DEFAULT 1,
 UNIT_PRICE      number(10,2) NOT NULL,
 ORDER_DATE      timestamp_ntz(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 STATUS          varchar(16777216) NOT NULL DEFAULT 'PENDING',
 TRACKING_NUMBER varchar(16777216) COMMENT 'Optional shipment tracking number',

 INDEX IDX_ORDERS_STATUS ( STATUS ),
 INDEX IDX_ORDERS_CUST_DATE ( CUSTOMER_ID, ORDER_DATE ) INCLUDE ( PRODUCT_ID, QUANTITY ),
 CONSTRAINT PK_ORDERS PRIMARY KEY ( ORDER_ID ),
 CONSTRAINT TRACKING_NUMBER UNIQUE ( TRACKING_NUMBER )
)
COMMENT = 'Hybrid table storing orders with full OLTP + OLAP support, no FKs';
