-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERS_HT
CREATE HYBRID TABLE SUPPLYCHAIN.ORDERS_HT
(
 ORDER_ID        number(38,0) NOT NULL AUTOINCREMENT START 1000 INCREMENT 1 COMMENT 'Unique identifier for the order',
 CUSTOMER_ID     number(38,0) NOT NULL COMMENT 'Unique identifier of the customer placing the order',
 PRODUCT_ID      number(38,0) NOT NULL COMMENT 'Unique identifier of the product ordered',
 QUANTITY        number(38,0) NOT NULL DEFAULT 1 COMMENT 'Quantity of the product ordered',
 UNIT_PRICE      number(10,2) NOT NULL COMMENT 'Price per unit at the time of order',
 ORDER_DATE      timestamp_ntz(9) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp when the order was placed',
 STATUS          varchar(16777216) NOT NULL DEFAULT 'PENDING' COMMENT 'Current status of the order (defaults to PENDING)',
 TRACKING_NUMBER varchar(16777216) COMMENT 'Unique tracking number for monitoring the shipment',

 INDEX IDX_ORDERS_CUST_DATE ( CUSTOMER_ID, ORDER_DATE ) INCLUDE ( PRODUCT_ID, QUANTITY ),
 INDEX IDX_ORDERS_STATUS ( STATUS ),
 CONSTRAINT PK_ORDERS PRIMARY KEY ( ORDER_ID ),
 CONSTRAINT TRACKING_NUMBER UNIQUE ( TRACKING_NUMBER )
)
COMMENT = 'Historical or transaction log table capturing order details with product information and tracking; supports order history and audit trails.';
