-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [CONSUMPTION].[vw_PricingAnalysis]
CREATE VIEW [CONSUMPTION].[vw_PricingAnalysis] AS
SELECT 
    pl.PriceListId,
    pl.PriceListCode,
    pl.PriceListName,
    pl.CurrencyCode,
    pl.IsActive,
    pl.EffectiveFrom,
    pl.EffectiveTo,
    CASE 
        WHEN pl.EffectiveTo < CAST(GETDATE() AS DATE) THEN 'Expired'
        WHEN pl.EffectiveFrom <= CAST(GETDATE() AS DATE) AND (pl.EffectiveTo IS NULL OR pl.EffectiveTo >= CAST(GETDATE() AS DATE)) THEN 'Active'
        ELSE 'Upcoming'
    END AS PriceListStatus,
    COUNT(DISTINCT pli.PriceListItemId) AS PriceItemCount,
    MIN(pli.UnitPrice) AS MinPrice,
    MAX(pli.UnitPrice) AS MaxPrice,
    AVG(pli.UnitPrice) AS AvgPrice
FROM dbo.PriceList pl
LEFT JOIN dbo.PriceListItem pli ON pl.PriceListId = pli.PriceListId
GROUP BY 
    pl.PriceListId, pl.PriceListCode, pl.PriceListName, pl.CurrencyCode,
    pl.IsActive, pl.EffectiveFrom, pl.EffectiveTo;
GO
