-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [consumption].[vw_CustomerSummary]
CREATE VIEW [consumption].[vw_CustomerSummary] AS
SELECT 
    c.CustomerId,
    c.CustomerNumber,
    c.CustomerName,
    c.CustomerStatus,
    c.DefaultCurrencyCode,
    COUNT(DISTINCT so.SalesOrderId) AS TotalOrders,
    COUNT(DISTINCT cc.CustomerContractId) AS TotalContracts,
    COUNT(DISTINCT se.ServiceEntitlementId) AS TotalEntitlements,
    COUNT(DISTINCT cl.CustomerLocationId) AS TotalLocations,
    COUNT(DISTINCT con.CustomerContactId) AS TotalContacts,
    c.CreatedAt,
    c.UpdatedAt
FROM dbo.Customer c
LEFT JOIN dbo.SalesOrder so ON c.CustomerId = so.CustomerId
LEFT JOIN dbo.CustomerContract cc ON c.CustomerId = cc.CustomerId
LEFT JOIN dbo.ServiceEntitlement se ON c.CustomerId = se.CustomerId
LEFT JOIN dbo.CustomerLocation cl ON c.CustomerId = cl.CustomerId
LEFT JOIN dbo.CustomerContact con ON c.CustomerId = con.CustomerId
GROUP BY 
    c.CustomerId, c.CustomerNumber, c.CustomerName, c.CustomerStatus, 
    c.DefaultCurrencyCode, c.CreatedAt, c.UpdatedAt;
GO
