-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [consumption].[vw_SalesOrderLineDetail]
CREATE VIEW [consumption].[vw_SalesOrderLineDetail] AS
SELECT 
    sol.SalesOrderLineId,
    sol.SalesOrderId,
    so.OrderNumber,
    sol.LineNumber,
    sol.LineType,
    CASE 
        WHEN sol.OfferingId IS NOT NULL THEN o.OfferingCode
        WHEN sol.BundleId IS NOT NULL THEN b.BundleCode
        ELSE NULL
    END AS ItemCode,
    CASE 
        WHEN sol.OfferingId IS NOT NULL THEN o.OfferingName
        WHEN sol.BundleId IS NOT NULL THEN b.BundleName
        ELSE NULL
    END AS ItemName,
    sol.Quantity,
    sol.UnitPrice,
    sol.DiscountPct,
    sol.TaxPct,
    sol.StartDate,
    sol.EndDate,
    DATEDIFF(DAY, ISNULL(sol.StartDate, so.OrderDate), ISNULL(sol.EndDate, GETDATE())) AS DurationDays,
    sol.Quantity * sol.UnitPrice AS LineGrossAmount,
    sol.Quantity * sol.UnitPrice * (1 - sol.DiscountPct / 100) AS LineDiscountedAmount,
    sol.Quantity * sol.UnitPrice * (1 - sol.DiscountPct / 100) * (1 + sol.TaxPct / 100) AS LineNetAmount
FROM dbo.SalesOrderLine sol
INNER JOIN dbo.SalesOrder so ON sol.SalesOrderId = so.SalesOrderId
LEFT JOIN dbo.Offering o ON sol.OfferingId = o.OfferingId
LEFT JOIN dbo.Bundle b ON sol.BundleId = b.BundleId;
GO
