-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [consumption].[vw_CustomerLocationSummary]
CREATE VIEW [consumption].[vw_CustomerLocationSummary] AS
SELECT 
    cl.CustomerLocationId,
    cl.CustomerId,
    c.CustomerName,
    cl.LocationCode,
    cl.LocationName,
    cl.AddressLine1,
    cl.AddressLine2,
    cl.City,
    cl.StateProvince,
    cl.PostalCode,
    cl.CountryCode,
    cl.IsPrimary,
    COUNT(DISTINCT so.SalesOrderId) AS OrdersFromLocation,
    COUNT(DISTINCT con.CustomerContactId) AS ContactsAtLocation,
    cl.CreatedAt
FROM dbo.CustomerLocation cl
INNER JOIN dbo.Customer c ON cl.CustomerId = c.CustomerId
LEFT JOIN dbo.SalesOrder so ON cl.CustomerLocationId = so.CustomerLocationId
LEFT JOIN dbo.CustomerContact con ON cl.CustomerId = con.CustomerId
GROUP BY 
    cl.CustomerLocationId, cl.CustomerId, c.CustomerName, cl.LocationCode,
    cl.LocationName, cl.AddressLine1, cl.AddressLine2, cl.City, cl.StateProvince,
    cl.PostalCode, cl.CountryCode, cl.IsPrimary, cl.CreatedAt;
GO
