-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [consumption].[vw_OfferingBundleAnalysis]
CREATE VIEW [consumption].[vw_OfferingBundleAnalysis] AS
SELECT 
    'Offering' AS ItemType,
    o.OfferingId AS ItemId,
    o.OfferingCode AS ItemCode,
    o.OfferingName AS ItemName,
    o.OfferingDescription AS ItemDescription,
    ot.OfferingTypeName AS CategoryName,
    COUNT(DISTINCT oi.OfferingItemId) AS ComponentCount,
    o.IsActive,
    o.EffectiveFrom,
    o.EffectiveTo,
    o.CreatedAt,
    o.UpdatedAt
FROM dbo.Offering o
LEFT JOIN dbo.OfferingType ot ON o.OfferingTypeId = ot.OfferingTypeId
LEFT JOIN dbo.OfferingItem oi ON o.OfferingId = oi.OfferingId
GROUP BY 
    o.OfferingId, o.OfferingCode, o.OfferingName, o.OfferingDescription,
    ot.OfferingTypeName, o.IsActive, o.EffectiveFrom, o.EffectiveTo,
    o.CreatedAt, o.UpdatedAt

UNION ALL

SELECT 
    'Bundle' AS ItemType,
    b.BundleId AS ItemId,
    b.BundleCode AS ItemCode,
    b.BundleName AS ItemName,
    b.BundleDescription AS ItemDescription,
    'Bundle' AS CategoryName,
    COUNT(DISTINCT bi.BundleItemId) AS ComponentCount,
    b.IsActive,
    b.EffectiveFrom,
    b.EffectiveTo,
    b.CreatedAt,
    b.UpdatedAt
FROM dbo.Bundle b
LEFT JOIN dbo.BundleItem bi ON b.BundleId = bi.BundleId
GROUP BY 
    b.BundleId, b.BundleCode, b.BundleName, b.BundleDescription,
    b.IsActive, b.EffectiveFrom, b.EffectiveTo, b.CreatedAt, b.UpdatedAt;
GO
