-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.PRICEBOOK_T
CREATE TABLE CRM.PRICEBOOK_T
(
 PRICEBOOK_ID string(18) NOT NULL COMMENT 'Unique identifier for each pricebook, serving as the primary key.' CONSTRAINT PK_PRICEBOOK PRIMARY KEY,
 NAME         string(80) NOT NULL COMMENT 'The name of the pricebook (e.g., Standard Pricebook, Promotional Pricebook).',
 IS_ACTIVE    boolean COMMENT 'Indicates whether the pricebook is active and available for use in CRM processes.',
 CREATED_DATE date COMMENT 'The date when the pricebook record was created.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Stores pricing catalogs, allowing organizations to maintain different product pricing structures for various customer segments or sales contexts.';
