-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** CRM.Profile
CREATE TABLE CRM.Profile
(
ProfileId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each profile, used as the primary key.'),
Name        string(80) NOT NULL OPTIONS(description = 'The name of the profile (e.g., Administrator, Sales Representative).'),
Description string OPTIONS(description = 'Optional description providing additional details about the profile and its purpose.')
)
OPTIONS(description = 'Manages security and permissions, ensuring users have appropriate access to CRM data and functionalities.',
friendly_name = 'Profile');
