-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.USER_T
CREATE TABLE CRM.USER_T
(
 USER_ID      string(18) NOT NULL COMMENT 'Unique identifier for each user in the CRM. This ID is used as the primary key for linking user records throughout the system.' CONSTRAINT PK_USER PRIMARY KEY,
 USERNAME     string(80) NOT NULL COMMENT 'Specifies the unique username for the user, used for login and identification.',
 EMAIL        string(80) COMMENT 'Stores the email address of the user. This is used for system notifications and communication.',
 IS_ACTIVE    boolean COMMENT 'Indicates whether the user''s account is active. Active users can log in and access the CRM, while inactive users cannot.',
 PROFILE_ID   string(18) COMMENT 'References the Profile table to define permissions and access for this user.',
 CREATED_DATE date COMMENT 'The date and time when this user record was created in the system.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Contains information about CRM system users, including their login credentials, roles, and activity statuses.';
