-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** CRM.Product
CREATE TABLE CRM.Product
(
ProductId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each product, serving as the primary key.'),
Name        string(80) NOT NULL OPTIONS(description = 'The name of the product (e.g., Premium Subscription or Wireless Headphones).'),
ProductCode string(40) OPTIONS(description = 'A unique code used to identify the product in inventory or sales records.'),
Description string OPTIONS(description = 'Optional details about the product, such as features, specifications, or benefits.'),
IsActive    bool OPTIONS(description = 'Indicates whether the product is currently available for sales or use in CRM processes.'),
CreatedDate date OPTIONS(description = 'The date when the product record was added to the CRM.')
)
OPTIONS(description = 'Stores information about products or services offered by the organization, forming the foundation for pricing and sales management.',
friendly_name = 'Product');
