-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.dim_CONTACT_T
CREATE TABLE CRM.dim_CONTACT_T
(
 CON_ID          string(18) NOT NULL COMMENT 'Unique identifier for each contact, serving as the primary key.',
 from_dts        timestamp_ntz(9) NOT NULL,
 to_dts          timestamp_ntz(9) NOT NULL,
 FIRST_NAME      string(40) COMMENT 'The first name of the contact.',
 LAST_NAME       string(80) NOT NULL COMMENT 'The last name of the contact, which is required for proper identification.',
 ACC_ID          string(18) COMMENT 'References the account associated with this contact.',
 EMAIL           string(80) COMMENT 'The email address of the contact, used for communication.',
 PHONE           string(40) COMMENT 'The primary phone number for the contact.',
 MOBILE_PHONE    string(40) COMMENT 'The mobile phone number of the contact.',
 MAILING_CITY    string(40) COMMENT 'The city in the contact’s mailing address.',
 MAILING_COUNTRY string(40) COMMENT 'The country in the contact’s mailing address.',
 CREATED_DATE    date COMMENT 'The date when the contact record was created.',
 LastUpdated     timestamp NOT NULL,
 load_dts        timestamp_ntz(9) NOT NULL,
 CONSTRAINT PK_85 PRIMARY KEY (CON_ID, from_dts)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
