-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.opportunitylineitem
CREATE TABLE crm.opportunitylineitem
(
 LineItemId    varchar(18) NOT NULL COMMENT 'Unique identifier for each line item in an opportunity, serving as the primary key.' CONSTRAINT pk_opportunitylineitem PRIMARY KEY,
 OpportunityId varchar(18) COMMENT 'References the opportunity associated with the line item.' CONSTRAINT opportunityid12 REFERENCES crm.opportunity,
 ProductId     varchar(18) COMMENT 'References the product associated with the line item.' CONSTRAINT productid12 REFERENCES crm.product,
 Quantity      decimal(10,2) COMMENT 'Specifies the quantity of the product included in the line item.',
 UnitPrice     decimal(18,2) COMMENT 'Specifies the price per unit of the product.',
 CreatedDate   date COMMENT 'The date when the line item record was created.'
)
USING DELTA
 COMMENT 'Stores product-level details for opportunities, including quantity, pricing, and related products.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
