-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_DIMACCOUNT
CREATE TABLE CRM.SILVER_DIMACCOUNT
(
 ACCOUNT_KEY     int NOT NULL CONSTRAINT DIMACCOUNT_PK PRIMARY KEY,
 ACCOUNT_ID      varchar(18) NOT NULL,
 NAME            string,
 ACCOUNT_NUMBER  string,
 INDUSTRY        string,
 ANNUAL_REVENUE  decimal(18,2),
 RATING          string,
 TYPE            string,
 BILLING_CITY    string,
 BILLING_COUNTRY string,
 CREATED_DATE    date,
 Last_Updated    timestamp NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
