-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_DIMTERRITORY
CREATE TABLE CRM.SILVER_DIMTERRITORY
(
 TERRITORY_KEY int NOT NULL CONSTRAINT DIMTERRITORY_PK PRIMARY KEY,
 TERRITORY_ID  varchar(18) NOT NULL,
 NAME          string,
 DESCRIPTION   varchar(50),
 CREATED_DATE  date,
 Last_Updated  timestamp NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
