-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** CRM.User
CREATE TABLE CRM.User
(
UserId      string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each user in the CRM. This ID is used as the primary key for linking user records throughout the system.'),
Username    string(80) NOT NULL OPTIONS(description = 'Specifies the unique username for the user, used for login and identification.'),
Email       string(80) OPTIONS(description = 'Stores the email address of the user. This is used for system notifications and communication.'),
IsActive    bool OPTIONS(description = 'Indicates whether the users account is active. Active users can log in and access the CRM, while inactive users cannot.'),
ProfileId   string OPTIONS(description = 'References the Profile table to define permissions and access for this user.'),
CreatedDate date OPTIONS(description = 'The date and time when this user record was created in the system.')
)
OPTIONS(description = 'Contains information about CRM system users, including their login credentials, roles, and activity statuses.',
friendly_name = 'User');
