-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_TASK
CREATE TABLE CRM.SILVER_TASK
(
 TASK_ID      varchar(18) NOT NULL COMMENT 'Unique identifier for each task. Used as the primary key.' CONSTRAINT PK_TASK PRIMARY KEY,
 SUBJECT      string COMMENT 'A brief description or title for the task (e.g., "Follow up with client").',
 STATUS       string COMMENT 'Indicates the current status of the task (e.g., Open, In Progress, Completed).',
 PRIORITY     string COMMENT 'Defines the urgency of the task (e.g., High, Medium, Low).',
 DUE_DATE     date COMMENT 'Specifies the deadline for completing the task.',
 CREATED_DATE date COMMENT 'The date when the task record was created in the system.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Tracks actionable items assigned to CRM users to manage workflows and ensure timely follow-ups.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
