-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** CRM.Opportunity
CREATE TABLE CRM.Opportunity
(
OpportunityId string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each opportunity, serving as the primary key.'),
Name          string(120) NOT NULL OPTIONS(description = 'The name of the opportunity, such as Q1 Enterprise Sale.'),
AccountId     string REFERENCES CRM.Account(AccountId) NOT ENFORCED OPTIONS(description = 'References the account associated with the opportunity, linking the deal to a customer.'),
CloseDate     date OPTIONS(description = 'The expected or actual date when the opportunity is closed.'),
Stage         string(40) OPTIONS(description = 'Indicates the current stage in the sales pipeline (e.g., Prospecting, Negotiation, Closed Won).'),
Amount        numeric(18, 2) OPTIONS(description = 'Specifies the potential revenue value of the opportunity.'),
Probability   numeric(5, 2) OPTIONS(description = 'Represents the likelihood of successfully closing the opportunity, expressed as a percentage.'),
CreatedDate   date OPTIONS(description = 'The date when the opportunity record was created.')
)
OPTIONS(description = 'Tracks potential revenue-generating deals, providing visibility into the sales pipeline and supporting revenue forecasting.',
friendly_name = 'Opportunity');
