-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_QUOTE
CREATE TABLE CRM.SILVER_QUOTE
(
 QUOTE_ID       varchar(18) NOT NULL COMMENT 'Unique identifier for each quote, serving as the primary key.' CONSTRAINT PK_QUOTE PRIMARY KEY,
 OPPORTUNITY_ID varchar(18) COMMENT 'References the opportunity associated with the quote.' CONSTRAINT OPPORTUNITYID REFERENCES CRM.SILVER_OPPORTUNITY,
 STATUS         string COMMENT 'Tracks the current status of the quote (e.g., Draft, Approved, Rejected).',
 TOTAL_PRICE    decimal(18,2) COMMENT 'The total monetary value of the quote.',
 CREATED_DATE   date COMMENT 'The date when the quote record was created.',
 Last_Updated   timestamp NOT NULL
)
USING DELTA
 COMMENT 'Manages customer-facing pricing proposals, linking them to specific opportunities.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
