-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_CAMPAIGNMEMBER
CREATE TABLE CRM.SILVER_CAMPAIGNMEMBER
(
 MEMBER_ID    varchar(18) NOT NULL COMMENT 'Unique identifier for each campaign member, serving as the primary key.' CONSTRAINT PK_CAMPAIGNMEMBER PRIMARY KEY,
 CAMPAIGN_ID  varchar(18) COMMENT 'References the campaign associated with the member.' CONSTRAINT CAMPAIGNID REFERENCES CRM.SILVER_CAMPAIGN,
 LEAD_ID      varchar(18) COMMENT 'References the lead associated with the campaign member.' CONSTRAINT LEADID REFERENCES CRM.SILVER_LEAD,
 STATUS       string COMMENT 'Tracks the members status within the campaign (e.g., Responded, Sent).',
 CREATED_DATE date COMMENT 'The date when the campaign member record was created.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Tracks the participation and engagement of leads or contacts in marketing campaigns.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
