-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_DIMCAMPAIGN
CREATE TABLE CRM.SILVER_DIMCAMPAIGN
(
 CAMPAIGN_KEY  int NOT NULL CONSTRAINT DIMCAMPAIGN_PK PRIMARY KEY,
 CAMPAIGN_ID   varchar(18) NOT NULL,
 NAME          string,
 TYPE          string,
 STATUS        string,
 START_DATE    date,
 END_DATE      date,
 BUDGETED_COST decimal(18,2),
 CREATED_DATE  date,
 Last_Updated  timestamp NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
