-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.dimcampaign
CREATE TABLE crm.dimcampaign
(
 CampaignKey  int NOT NULL CONSTRAINT dimcampaign_pk PRIMARY KEY,
 CampaignId   varchar(18) NOT NULL,
 Name         string,
 Type         string,
 Status       string,
 StartDate    date,
 EndDate      date,
 BudgetedCost decimal(18,2),
 CreatedDate  date
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
