-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.TASK
CREATE TABLE CRM.TASK
(
TASK_ID      string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each task. Used as the primary key.'),
SUBJECT      string(255) OPTIONS(description = 'A brief description or title for the task.'),
STATUS       string(20) OPTIONS(description = 'Indicates the current status of the task.'),
PRIORITY     string(10) OPTIONS(description = 'Defines the urgency of the task .'),
DUE_DATE     date OPTIONS(description = 'Specifies the deadline for completing the task.'),
CREATED_DATE date OPTIONS(description = 'The date when the task record was created in the system.')
)
OPTIONS(description = 'Tracks actionable items assigned to CRM users to manage workflows and ensure timely follow-ups.',
friendly_name = 'Task');
