-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.product
CREATE TABLE crm.product
(
 ProductId   varchar(18) NOT NULL COMMENT 'Unique identifier for each product, serving as the primary key.' CONSTRAINT pk_product PRIMARY KEY,
 Name        string NOT NULL COMMENT 'The name of the product (e.g., Premium Subscription or Wireless Headphones).',
 ProductCode string COMMENT 'A unique code used to identify the product in inventory or sales records.',
 Description varchar(255) COMMENT 'Optional details about the product, such as features, specifications, or benefits.',
 IsActive    boolean COMMENT 'Indicates whether the product is currently available for sales or use in CRM processes.',
 CreatedDate date COMMENT 'The date when the product record was added to the CRM.'
)
USING DELTA
 COMMENT 'Stores information about products or services offered by the organization, forming the foundation for pricing and sales management.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
