-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.CAMPAIGN_MEMBER_T
CREATE TABLE CRM.CAMPAIGN_MEMBER_T
(
 MEMBER_ID    string(18) NOT NULL COMMENT 'Unique identifier for each campaign member, serving as the primary key.' CONSTRAINT PK_CAMPAIGN_MEMBER PRIMARY KEY,
 CAMPAIGN_ID  string(18) COMMENT 'References the campaign associated with the member.' CONSTRAINT CAMPAIGN_ID REFERENCES CRM.CAMPAIGN_T,
 LEAD_ID      string(18) COMMENT 'References the lead associated with the campaign member.' CONSTRAINT LEAD_ID REFERENCES CRM.LEAD_T,
 STATUS       string(20) COMMENT 'Tracks the member''s status within the campaign (e.g., Responded, Sent).',
 CREATED_DATE date COMMENT 'The date when the campaign member record was created.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Tracks the participation and engagement of leads or contacts in marketing campaigns.';
