-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.factsales
CREATE TABLE crm.factsales
(
 SalesKey     int NOT NULL CONSTRAINT factsales_pk PRIMARY KEY,
 ProductKey   int CONSTRAINT factsales_dimproduct_fk REFERENCES crm.dimproduct,
 AccountKey   int CONSTRAINT factsales_dimaccount_fk REFERENCES crm.dimaccount,
 TimeKey      int CONSTRAINT factsales_dimtime_fk REFERENCES crm.dimtime,
 UserKey      int CONSTRAINT factsales_dimuser_fk REFERENCES crm.dimuser,
 TerritoryKey int CONSTRAINT factsales_dimterritory_fk REFERENCES crm.dimterritory,
 Quantity     decimal(10,2),
 UnitPrice    decimal(18,2),
 CreatedDate  date
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
