-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_ACCOUNT
CREATE TABLE CRM.SILVER_ACCOUNT
(
 ACCOUNT_ID      varchar(18) NOT NULL COMMENT 'Unique identifier for each account in the CRM system.' CONSTRAINT PK_ACCOUNT PRIMARY KEY,
 NAME            string NOT NULL COMMENT 'The name of the account, such as a business or individual customer.',
 ACCOUNT_NUMBER  string COMMENT 'A unique number associated with the account for tracking purposes.',
 INDUSTRY        string COMMENT 'The industry to which the account belongs (e.g., Technology, Finance).',
 ANNUAL_REVENUE  decimal(18,2) COMMENT 'The annual revenue of the account, used for analysis and segmentation.',
 RATING          string COMMENT 'A qualitative rating of the account (e.g., Hot, Warm, Cold) to prioritize engagement.',
 TYPE            string COMMENT 'Specifies the type of account (e.g., Customer, Partner, Prospect).',
 BILLING_CITY    string COMMENT 'The city in the accounts billing address.',
 BILLING_COUNTRY string COMMENT 'The country in the accounts billing address.',
 CREATED_DATE    date COMMENT 'The date when the account record was created in the CRM.',
 Last_Updated    timestamp NOT NULL
)
USING DELTA
 COMMENT 'Stores core information about companies or individuals with whom the organization has business relationships, including customers, partners, and prospects.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
