-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_DIMROLE
CREATE TABLE CRM.SILVER_DIMROLE
(
 ROLE_KEY       int NOT NULL CONSTRAINT DIMROLE_PK PRIMARY KEY,
 ROLE_ID        varchar(18) NOT NULL,
 NAME           string,
 PARENT_ROLE_ID varchar(18),
 CREATED_DATE   date,
 Last_Updated   timestamp NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
