-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.PROFILE
CREATE TABLE CRM.PROFILE
(
 PROFILE_ID  char(18) NOT NULL COMMENT 'Unique identifier for each profile, used as the primary key.',
 NAME        varchar(80) NOT NULL COMMENT 'The name of the profile (e.g., Administrator, Sales Representative).',
 DESCRIPTION varchar COMMENT 'Optional description providing additional details about the profile and its purpose.',

 CONSTRAINT PK_PROFILE PRIMARY KEY ( PROFILE_ID )
)
COMMENT = 'Manages security and permissions, ensuring users have appropriate access to CRM data and functionalities.';
