-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** CRM.Territory
CREATE TABLE CRM.Territory
(
TerritoryId string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each territory. Serves as the primary key for territory records.'),
Name        string(80) NOT NULL OPTIONS(description = 'The name of the territory (e.g., West Region, Enterprise Accounts). Used to identify and categorize territories.'),
Description string OPTIONS(description = 'Optional text providing additional details or purpose of the territory.'),
CreatedDate date OPTIONS(description = 'The date when the territory record was created in the CRM system.')
)
OPTIONS(description = 'Defines geographical or organizational regions for managing sales or service operations, aiding in resource allocation and performance tracking.',
friendly_name = 'Territory');
