-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.TERRITORY
CREATE TABLE CRM.TERRITORY
(
 TERRITORY_ID char(18) NOT NULL COMMENT 'Unique identifier for each territory. Serves as the primary key for territory records.',
 NAME         varchar(80) NOT NULL COMMENT 'The name of the territory (e.g., West Region, Enterprise Accounts). Used to identify and categorize territories.',
 DESCRIPTION  varchar COMMENT 'Optional text providing additional details or purpose of the territory.',
 CREATED_DATE date COMMENT 'The date when the territory record was created in the CRM system.',

 CONSTRAINT PK_TERRITORY PRIMARY KEY ( TERRITORY_ID )
)
COMMENT = 'Defines geographical or organizational regions for managing sales or service operations, aiding in resource allocation and performance tracking.';
