-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_TERRITORY
CREATE TABLE CRM.SILVER_TERRITORY
(
 TERRITORY_ID varchar(18) NOT NULL COMMENT 'Unique identifier for each territory. Serves as the primary key for territory records.' CONSTRAINT PK_TERRITORY PRIMARY KEY,
 NAME         string NOT NULL COMMENT 'The name of the territory (e.g., West Region, Enterprise Accounts). Used to identify and categorize territories.',
 DESCRIPTION  varchar(255) COMMENT 'Optional text providing additional details or purpose of the territory.',
 CREATED_DATE date COMMENT 'The date when the territory record was created in the CRM system.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Defines geographical or organizational regions for managing sales or service operations, aiding in resource allocation and performance tracking.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
