-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_PRICEBOOK
CREATE TABLE CRM.SILVER_PRICEBOOK
(
 PRICEBOOK_ID varchar(18) NOT NULL COMMENT 'Unique identifier for each pricebook, serving as the primary key.' CONSTRAINT PK_PRICEBOOK PRIMARY KEY,
 NAME         string NOT NULL COMMENT 'The name of the pricebook (e.g., Standard Pricebook, Promotional Pricebook).',
 IS_ACTIVE    boolean COMMENT 'Indicates whether the pricebook is active and available for use in CRM processes.',
 CREATED_DATE date COMMENT 'The date when the pricebook record was created.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Stores pricing catalogs, allowing organizations to maintain different product pricing structures for various customer segments or sales contexts.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
