-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.CONTRACT
CREATE TABLE CRM.CONTRACT
(
CONTRACT_ID  string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each contract, serving as the primary key.'),
ACCOUNT_ID   string REFERENCES CRM.ACCOUNT(ACCOUNT_ID) NOT ENFORCED OPTIONS(description = 'References the account associated with this contract.'),
START_DATE   date OPTIONS(description = 'Specifies the start date of the contract.'),
END_DATE     date OPTIONS(description = 'Specifies the end date or expiration of the contract.'),
STATUS       string(20) OPTIONS(description = 'Tracks the current status of the contract (e.g., Active, Expired).'),
CREATED_DATE date OPTIONS(description = 'The date when the contract record was created in the CRM.')
)
OPTIONS(description = 'Manages customer agreements, tracking contract duration, status, and associated accounts.',
friendly_name = 'Contract');
