-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.contact
CREATE TABLE crm.contact
(
 ContactId      varchar(18) NOT NULL COMMENT 'Unique identifier for each contact, serving as the primary key.' CONSTRAINT pk_contact PRIMARY KEY,
 FirstName      string COMMENT 'The first name of the contact.',
 LastName       string NOT NULL COMMENT 'The last name of the contact, which is required for proper identification.',
 AccountId      varchar(18) COMMENT 'References the account associated with this contact.' CONSTRAINT accountid REFERENCES crm.account,
 Email          string COMMENT 'The email address of the contact, used for communication.',
 Phone          string COMMENT 'The primary phone number for the contact.',
 MobilePhone    string COMMENT 'The mobile phone number of the contact.',
 MailingCity    string COMMENT 'The city in the contact’s mailing address.',
 MailingCountry string COMMENT 'The country in the contact’s mailing address.',
 CreatedDate    date COMMENT 'The date when the contact record was created.'
)
USING DELTA
 COMMENT 'Represents individuals associated with accounts, tracking their details and enabling personalized interactions.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
