-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.opportunity
CREATE TABLE crm.opportunity
(
 OpportunityId varchar(18) NOT NULL COMMENT 'Unique identifier for each opportunity, serving as the primary key.' CONSTRAINT pk_opportunity PRIMARY KEY,
 Name          string NOT NULL COMMENT 'The name of the opportunity, such as Q1 Enterprise Sale.',
 AccountId     varchar(18) COMMENT 'References the account associated with the opportunity, linking the deal to a customer.' CONSTRAINT accountid23 REFERENCES crm.account,
 CloseDate     date COMMENT 'The expected or actual date when the opportunity is closed.',
 Stage         string COMMENT 'Indicates the current stage in the sales pipeline (e.g., Prospecting, Negotiation, Closed Won).',
 Amount        decimal(18,2) COMMENT 'Specifies the potential revenue value of the opportunity.',
 Probability   decimal(5,2) COMMENT 'Represents the likelihood of successfully closing the opportunity, expressed as a percentage.',
 CreatedDate   date COMMENT 'The date when the opportunity record was created.'
)
USING DELTA
 COMMENT 'Tracks potential revenue-generating deals, providing visibility into the sales pipeline and supporting revenue forecasting.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
