-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_PRICEBOOKENTRY
CREATE TABLE CRM.SILVER_PRICEBOOKENTRY
(
 ENTRY_ID     varchar(18) NOT NULL COMMENT 'Unique identifier for each pricebook entry, serving as the primary key.' CONSTRAINT PK_PRICEBOOKENTRY PRIMARY KEY,
 PRICEBOOK_ID varchar(18) COMMENT 'References the pricebook in which this product-price association is defined.' CONSTRAINT PRICEBOOKID REFERENCES CRM.SILVER_PRICEBOOK,
 PRODUCT_ID   varchar(18) COMMENT 'References the product associated with this pricebook entry.' CONSTRAINT PRODUCTID REFERENCES CRM.SILVER_PRODUCT,
 UNIT_PRICE   decimal(18,2) COMMENT 'Specifies the price of one unit of the product in the context of this pricebook.',
 IS_ACTIVE    boolean COMMENT 'Indicates whether the pricebook entry is active and available for use in transactions.',
 CREATED_DATE date COMMENT 'The date when the pricebook entry was created in the CRM.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Connects products to specific pricebooks, defining pricing for various sales and marketing contexts.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
