-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** CRM.Contact
CREATE TABLE CRM.Contact
(
ContactId      string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each contact, serving as the primary key.'),
FirstName      string(40) OPTIONS(description = 'The first name of the contact.'),
LastName       string(80) NOT NULL OPTIONS(description = 'The last name of the contact, which is required for proper identification.'),
AccountId      string REFERENCES CRM.Account(AccountId) NOT ENFORCED OPTIONS(description = 'References the account associated with this contact.'),
Email          string(80) OPTIONS(description = 'The email address of the contact, used for communication.'),
Phone          string(40) OPTIONS(description = 'The primary phone number for the contact.'),
MobilePhone    string(40) OPTIONS(description = 'The mobile phone number of the contact.'),
MailingCity    string(40) OPTIONS(description = 'The city in the contact?s mailing address.'),
MailingCountry string(40) OPTIONS(description = 'The country in the contact?s mailing address.'),
CreatedDate    date OPTIONS(description = 'The date when the contact record was created.')
)
OPTIONS(description = 'Represents individuals associated with accounts, tracking their details and enabling personalized interactions.',
friendly_name = 'Contact');
