-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.CAMPAIGN_MEMBER
CREATE TABLE CRM.CAMPAIGN_MEMBER
(
MEMBER_ID    string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each campaign member, serving as the primary key.'),
CAMPAIGN_ID  string OPTIONS(description = 'References the campaign associated with the member.'),
LEAD_ID      string OPTIONS(description = 'References the lead associated with the campaign member.'),
STATUS       string(20) OPTIONS(description = 'Tracks the members status within the campaign (e.g., Responded, Sent).'),
CREATED_DATE date OPTIONS(description = 'The date when the campaign member record was created.'),
 CONSTRAINT CAMPAIGN_ID FOREIGN KEY (CAMPAIGN_ID) REFERENCES CRM.CAMPAIGN (CAMPAIGN_ID) NOT ENFORCED,
 CONSTRAINT LEAD_ID FOREIGN KEY (LEAD_ID) REFERENCES CRM.LEAD (LEAD_ID) NOT ENFORCED
)
OPTIONS(description = 'Tracks the participation and engagement of leads or contacts in marketing campaigns.',
friendly_name = 'CampaignMember');
