-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_EVENT
CREATE TABLE CRM.SILVER_EVENT
(
 EVENT_ID     varchar(18) NOT NULL COMMENT 'Unique identifier for each event, serving as the primary key.' CONSTRAINT PK_EVENT PRIMARY KEY,
 SUBJECT      string COMMENT 'The title or topic of the event (e.g., "Product Demo" or "Quarterly Review").',
 START_DATE   date COMMENT 'The start date and time of the event.',
 END_DATE     date COMMENT 'The end date and time of the event.',
 LOCATION     string COMMENT 'The physical or virtual location where the event is scheduled to occur.',
 CREATED_DATE date COMMENT 'The date when the event record was created.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Stores scheduled events, such as meetings or appointments, to track interactions with customers and stakeholders.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
