-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.`user`
CREATE TABLE crm.`user`
(
 UserId      varchar(18) NOT NULL COMMENT 'Unique identifier for each user in the CRM. This ID is used as the primary key for linking user records throughout the system.' CONSTRAINT pk_user PRIMARY KEY,
 Username    string NOT NULL COMMENT 'Specifies the unique username for the user, used for login and identification.',
 Email       string COMMENT 'Stores the email address of the user. This is used for system notifications and communication.',
 IsActive    boolean COMMENT 'Indicates whether the users account is active. Active users can log in and access the CRM, while inactive users cannot.',
 ProfileId   varchar(18) COMMENT 'References the Profile table to define permissions and access for this user.',
 CreatedDate date COMMENT 'The date and time when this user record was created in the system.'
)
USING DELTA
 COMMENT 'Contains information about CRM system users, including their login credentials, roles, and activity statuses.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
