-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.dimaccount
CREATE TABLE crm.dimaccount
(
 AccountKey     int NOT NULL CONSTRAINT dimaccount_pk PRIMARY KEY,
 AccountId      varchar(18) NOT NULL,
 Name           string,
 AccountNumber  string,
 Industry       string,
 AnnualRevenue  decimal(18,2),
 Rating         string,
 Type           string,
 BillingCity    string,
 BillingCountry string,
 CreatedDate    date
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
