-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.event
CREATE TABLE crm.event
(
 EventId     varchar(18) NOT NULL COMMENT 'Unique identifier for each event, serving as the primary key.' CONSTRAINT pk_event PRIMARY KEY,
 Subject     string COMMENT 'The title or topic of the event (e.g., "Product Demo" or "Quarterly Review").',
 StartDate   date COMMENT 'The start date and time of the event.',
 EndDate     date COMMENT 'The end date and time of the event.',
 Location    string COMMENT 'The physical or virtual location where the event is scheduled to occur.',
 CreatedDate date COMMENT 'The date when the event record was created.'
)
USING DELTA
 COMMENT 'Stores scheduled events, such as meetings or appointments, to track interactions with customers and stakeholders.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
