-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.EVENT
CREATE TABLE CRM.EVENT
(
EVENT_ID     string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each event, serving as the primary key.'),
SUBJECT      string(255) OPTIONS(description = 'The title or topic of the event.'),
START_DATE   date OPTIONS(description = 'The start date and time of the event.'),
END_DATE     date OPTIONS(description = 'The end date and time of the event.'),
LOCATION     string(255) OPTIONS(description = 'The physical or virtual location where the event is scheduled to occur.'),
CREATED_DATE date OPTIONS(description = 'The date when the event record was created.')
)
OPTIONS(description = 'Stores scheduled events, such as meetings or appointments, to track interactions with customers and stakeholders.',
friendly_name = 'Event');
