-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.USER
CREATE TABLE CRM.USER
(
 USER_ID      char(18) NOT NULL COMMENT 'Unique identifier for each user in the CRM. This ID is used as the primary key for linking user records throughout the system.',
 USERNAME     varchar(80) NOT NULL COMMENT 'Specifies the unique username for the user, used for login and identification.',
 EMAIL        varchar(80) COMMENT 'Stores the email address of the user. This is used for system notifications and communication.',
 IS_ACTIVE    boolean COMMENT 'Indicates whether the user''s account is active. Active users can log in and access the CRM, while inactive users cannot.',
 PROFILE_ID   char(18) COMMENT 'References the Profile table to define permissions and access for this user.',
 CREATED_DATE date COMMENT 'The date and time when this user record was created in the system.',

 CONSTRAINT PK_USER PRIMARY KEY ( USER_ID )
)
COMMENT = 'Contains information about CRM system users, including their login credentials, roles, and activity statuses.';
