-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.PRICEBOOK_ENTRY
CREATE TABLE CRM.PRICEBOOK_ENTRY
(
ENTRY_ID     string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each pricebook entry, serving as the primary key.'),
PRICEBOOK_ID string OPTIONS(description = 'References the pricebook in which this product-price association is defined.'),
PRODUCT_ID   string OPTIONS(description = 'References the product associated with this pricebook entry.'),
UNIT_PRICE   numeric(18, 2) OPTIONS(description = 'Specifies the price of one unit of the product in the context of this pricebook.'),
IS_ACTIVE    bool OPTIONS(description = 'Indicates whether the pricebook entry is active and available for use in transactions.'),
CREATED_DATE date OPTIONS(description = 'The date when the pricebook entry was created in the CRM.'),
 CONSTRAINT PRICEBOOK_ID FOREIGN KEY (PRICEBOOK_ID) REFERENCES CRM.PRICEBOOK (PRICEBOOK_ID) NOT ENFORCED,
 CONSTRAINT PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES CRM.PRODUCT (PRODUCT_ID) NOT ENFORCED
)
OPTIONS(description = 'Connects products to specific pricebooks, defining pricing for various sales and marketing contexts.',
friendly_name = 'PricebookEntry');
