-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.dimuser
CREATE TABLE crm.dimuser
(
 UserKey     int NOT NULL CONSTRAINT dimuser_pk PRIMARY KEY,
 UserId      varchar(18) NOT NULL,
 Username    string,
 Email       string,
 IsActive    boolean,
 ProfileId   varchar(18),
 CreatedDate date
)
USING DELTA
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
