-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_CAMPAIGN
CREATE TABLE CRM.SILVER_CAMPAIGN
(
 CAMPAIGN_ID   varchar(18) NOT NULL COMMENT 'Unique identifier for each campaign, serving as the primary key.' CONSTRAINT PK_CAMPAIGN PRIMARY KEY,
 NAME          string NOT NULL COMMENT 'The name of the campaign (e.g., Spring Sale or Customer Retention Drive).',
 TYPE          string COMMENT 'Specifies the type of campaign (e.g., Email, Social Media, Direct Mail).',
 STATUS        string COMMENT 'The current status of the campaign (e.g., Active, Completed, Planned).',
 START_DATE    date COMMENT 'The start date of the campaign.',
 END_DATE      date COMMENT 'The end date of the campaign.',
 BUDGETED_COST decimal(18,2) COMMENT 'The estimated financial budget allocated for the campaign.',
 CREATED_DATE  date COMMENT 'The date when the campaign record was created.',
 Last_Updated  timestamp NOT NULL
)
USING DELTA
 COMMENT 'Tracks marketing campaigns, including details about their type, duration, budget, and status.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
