-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: Sample/Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM."CASE"
CREATE TABLE CRM."CASE"
(
 CASE_ID      char(18) NOT NULL COMMENT 'Unique identifier for each customer case, serving as the primary key.',
 ACCOUNT_ID   char(18) COMMENT 'References the account associated with the case, linking the issue to a specific customer.',
 CON_ID       char(18) COMMENT 'References the contact associated with the case, providing the individual point of contact for the issue.',
 STATUS       varchar(20) COMMENT 'Tracks the current status of the case (e.g., New, In Progress, Closed).',
 PRIORITY     varchar(10) COMMENT 'Indicates the urgency level of the case (e.g., High, Medium, Low).',
 SUBJECT      varchar(255) COMMENT 'Provides a brief description or title for the case (e.g., "Billing Issue").',
 DESCRIPTION  varchar COMMENT 'Contains detailed information about the case, outlining the customer’s issue or request.',
 CREATED_DATE date COMMENT 'The date when the case record was created in the CRM.',
 ADDRESS      string NOT NULL,

 CONSTRAINT PK_CASE PRIMARY KEY ( CASE_ID ),
 CONSTRAINT ACCOUNT_ID FOREIGN KEY ( ACCOUNT_ID ) REFERENCES CRM.ACCOUNT ( ACCOUNT_ID ),
 CONSTRAINT CON_ID FOREIGN KEY ( CON_ID ) REFERENCES CRM.CONTACT ( CON_ID )
)
COMMENT = 'Tracks customer service issues, complaints, or inquiries, enabling efficient case management and resolution.';
