-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** crm.contract
CREATE TABLE crm.contract
(
 ContractId  varchar(18) NOT NULL COMMENT 'Unique identifier for each contract, serving as the primary key.' CONSTRAINT pk_contract PRIMARY KEY,
 AccountId   varchar(18) COMMENT 'References the account associated with this contract.' CONSTRAINT accountid1 REFERENCES crm.account,
 StartDate   date COMMENT 'Specifies the start date of the contract.',
 EndDate     date COMMENT 'Specifies the end date or expiration of the contract.',
 Status      string COMMENT 'Tracks the current status of the contract (e.g., Active, Expired).',
 CreatedDate date COMMENT 'The date when the contract record was created in the CRM.'
)
USING DELTA
 COMMENT 'Manages customer agreements, tracking contract duration, status, and associated accounts.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
