-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.QUOTE_T
CREATE TABLE CRM.QUOTE_T
(
 QUOTE_ID       string(18) NOT NULL COMMENT 'Unique identifier for each quote, serving as the primary key.' CONSTRAINT PK_QUOTE PRIMARY KEY,
 OPPORTUNITY_ID string(18) COMMENT 'References the opportunity associated with the quote.' CONSTRAINT OPPORTUNITY_ID REFERENCES CRM.OPPORTUNITY_T,
 STATUS         string(20) COMMENT 'Tracks the current status of the quote (e.g., Draft, Approved, Rejected).',
 TOTAL_PRICE    decimal(18,2) COMMENT 'The total monetary value of the quote.',
 CREATED_DATE   date COMMENT 'The date when the quote record was created.',
 LastUpdated    timestamp NOT NULL
)
 COMMENT 'Manages customer-facing pricing proposals, linking them to specific opportunities.';
