-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.PROFILE
CREATE TABLE CRM.PROFILE
(
PROFILE_ID  string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each profile, used as the primary key.'),
NAME        string(80) NOT NULL OPTIONS(description = 'The name of the profile (e.g., Administrator, Sales Representative).'),
DESCRIPTION string OPTIONS(description = 'Optional description providing additional details about the profile and its purpose.')
)
OPTIONS(description = 'Manages security and permissions, ensuring users have appropriate access to CRM data and functionalities.',
friendly_name = 'Profile');
