-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** CRM.CONTACT
CREATE TABLE CRM.CONTACT
(
CONTACT_ID      string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each contact, serving as the primary key.'),
FIRST_NAME      string(40) OPTIONS(description = 'The first name of the contact.'),
LAST_NAME       string(80) NOT NULL OPTIONS(description = 'The last name of the contact, which is required for proper identification.'),
ACCOUNT_ID      string REFERENCES CRM.ACCOUNT(ACCOUNT_ID) NOT ENFORCED OPTIONS(description = 'References the account associated with this contact.'),
EMAIL           string(80) OPTIONS(description = 'The email address of the contact, used for communication.'),
PHONE           string(40) OPTIONS(description = 'The primary phone number for the contact.'),
MOBILE_PHONE    string(40) OPTIONS(description = 'The mobile phone number of the contact.'),
MAILING_CITY    string(40) OPTIONS(description = 'The city in the contact?s mailing address.'),
MAILING_COUNTRY string(40) OPTIONS(description = 'The country in the contact?s mailing address.'),
CREATED_DATE    date OPTIONS(description = 'The date when the contact record was created.')
)
OPTIONS(description = 'Represents individuals associated with accounts, tracking their details and enabling personalized interactions.',
friendly_name = 'Contact');
