-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** CRM.SILVER_OPPORTUNITYLINEITEM
CREATE TABLE CRM.SILVER_OPPORTUNITYLINEITEM
(
 LINE_ITEM_ID   varchar(18) NOT NULL COMMENT 'Unique identifier for each line item in an opportunity, serving as the primary key.' CONSTRAINT PK_OPPORTUNITYLINEITEM PRIMARY KEY,
 OPPORTUNITY_ID varchar(18) COMMENT 'References the opportunity associated with the line item.' CONSTRAINT OPPORTUNITYID_12 REFERENCES CRM.SILVER_OPPORTUNITY,
 PRODUCT_ID     varchar(18) COMMENT 'References the product associated with the line item.' CONSTRAINT PRODUCTID_12 REFERENCES CRM.SILVER_PRODUCT,
 QUANTITY       decimal(10,2) COMMENT 'Specifies the quantity of the product included in the line item.',
 UNIT_PRICE     decimal(18,2) COMMENT 'Specifies the price per unit of the product.',
 CREATED_DATE   date COMMENT 'The date when the line item record was created.',
 Last_Updated   timestamp NOT NULL
)
USING DELTA
 COMMENT 'Stores product-level details for opportunities, including quantity, pricing, and related products.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
