-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** Customer1
CREATE TABLE Customer1
(
 cusid     int NOT NULL CONSTRAINT PK_46 PRIMARY KEY,
 fname     string NOT NULL,
 ContactId varchar(18) NOT NULL COMMENT 'Unique identifier for each contact, serving as the primary key.' CONSTRAINT FK_23 REFERENCES crm.contact
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
