-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[Service]
CREATE TABLE [dbo].[Service]
(
 [ServiceId]           int IDENTITY (1, 1) NOT NULL ,
 [ServiceCode]         nvarchar(60) NOT NULL ,
 [ServiceName]         nvarchar(200) NOT NULL ,
 [ServiceDescription]  nvarchar(1000) NULL ,
 [ServiceCategoryId]   int NULL ,
 [DefaultDurationDays] int NULL ,
 [IsMetered]           bit NOT NULL CONSTRAINT [DF_Service_IsMetered] DEFAULT (0) ,
 [UomCode]             nvarchar(10) NOT NULL ,
 [TaxCategoryId]       int NULL ,
 [IsActive]            bit NOT NULL CONSTRAINT [DF_Service_IsActive] DEFAULT (1) ,
 [CreatedAt]           datetime2(3) NOT NULL CONSTRAINT [DF_Service_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [UpdatedAt]           datetime2(3) NOT NULL CONSTRAINT [DF_Service_UpdatedAt] DEFAULT (SYSUTCDATETIME()) ,

 CONSTRAINT [PK_Service] PRIMARY KEY NONCLUSTERED ([ServiceId] ASC),
 CONSTRAINT [UQ_Service_Code] UNIQUE NONCLUSTERED ([ServiceCode] ASC),
 CONSTRAINT [FK_Service_Category] FOREIGN KEY ([ServiceCategoryId])  REFERENCES [dbo].[ServiceCategory]([ServiceCategoryId]),
 CONSTRAINT [FK_Service_TaxCategory] FOREIGN KEY ([TaxCategoryId])  REFERENCES [dbo].[TaxCategory]([TaxCategoryId]),
 CONSTRAINT [FK_Service_Uom] FOREIGN KEY ([UomCode])  REFERENCES [dbo].[UnitOfMeasure]([UomCode])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents services that can be sold individually or as part of offerings and bundles', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'ServiceId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique code identifying the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'ServiceCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name of the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'ServiceName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Detailed description of the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'ServiceDescription';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the service category', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'ServiceCategoryId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Default duration in days for this service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'DefaultDurationDays';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the service is usage-based (metered)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'IsMetered';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unit of measure for the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'UomCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the tax category for the service', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'TaxCategoryId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the service is currently available for sale', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'IsActive';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the service record was created', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the service record was last updated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Service', @level2type=N'COLUMN', @level2name=N'UpdatedAt';
GO