-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[ProductCategory]
CREATE TABLE [dbo].[ProductCategory]
(
 [ProductCategoryId]       int IDENTITY (1, 1) NOT NULL ,
 [CategoryName]            nvarchar(100) NOT NULL ,
 [ParentProductCategoryId] int NULL ,

 CONSTRAINT [PK_ProductCategory] PRIMARY KEY NONCLUSTERED ([ProductCategoryId] ASC),
 CONSTRAINT [UQ_ProductCategory_Name] UNIQUE NONCLUSTERED ([CategoryName] ASC),
 CONSTRAINT [FK_ProductCategory_Parent] FOREIGN KEY ([ParentProductCategoryId])  REFERENCES [dbo].[ProductCategory]([ProductCategoryId])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Hierarchical categories for classifying products', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductCategory';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the product category', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductCategory', @level2type=N'COLUMN', @level2name=N'ProductCategoryId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the product category', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductCategory', @level2type=N'COLUMN', @level2name=N'CategoryName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent category for hierarchical classification', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductCategory', @level2type=N'COLUMN', @level2name=N'ParentProductCategoryId';
GO