-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[Bundle]
CREATE TABLE [dbo].[Bundle]
(
 [BundleId]          int IDENTITY (1, 1) NOT NULL ,
 [BundleCode]        nvarchar(60) NOT NULL ,
 [BundleName]        nvarchar(200) NOT NULL ,
 [BundleDescription] nvarchar(1000) NULL ,
 [IsActive]          bit NOT NULL CONSTRAINT [DF_Bundle_IsActive] DEFAULT (1) ,
 [EffectiveFrom]     date NOT NULL CONSTRAINT [DF_Bundle_EffectiveFrom] DEFAULT (CONVERT(date, SYSUTCDATETIME())) ,
 [EffectiveTo]       date NULL ,
 [CreatedAt]         datetime2(3) NOT NULL CONSTRAINT [DF_Bundle_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [UpdatedAt]         datetime2(3) NOT NULL CONSTRAINT [DF_Bundle_UpdatedAt] DEFAULT (SYSUTCDATETIME()) ,

 CONSTRAINT [PK_Bundle] PRIMARY KEY NONCLUSTERED ([BundleId] ASC),
 CONSTRAINT [UQ_Bundle_Code] UNIQUE NONCLUSTERED ([BundleCode] ASC),
 CONSTRAINT [CK_Bundle_EffectiveRange] CHECK ( EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents product bundles that group multiple offerings together for sale as a single package', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Bundle';
GO