-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[UNIT_OF_MEASURE_T]
CREATE TABLE [DBO].[UNIT_OF_MEASURE_T]
(
 [UOM_CODE] nvarchar(10) NOT NULL ,
 [UOM_NAME] nvarchar(50) NOT NULL ,

 CONSTRAINT [PK_UNIT_OF_MEASURE] PRIMARY KEY NONCLUSTERED ([UOM_CODE] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference table for units of measure used in product and service quantity specifications', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'UNIT_OF_MEASURE_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Code for the unit of measure (e.g., EA, BOX, HR, LTR)', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'UNIT_OF_MEASURE_T', @level2type=N'COLUMN', @level2name=N'UOM_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Full name of the unit of measure', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'UNIT_OF_MEASURE_T', @level2type=N'COLUMN', @level2name=N'UOM_NAME';
GO