-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[TAX_CATEGORY_T]
CREATE TABLE [DBO].[TAX_CATEGORY_T]
(
 [TAX_CATEGORY_ID]   int IDENTITY (1, 1) NOT NULL ,
 [TAX_CATEGORY_NAME] nvarchar(50) NOT NULL ,
 [TAX_RATE_PCT]      decimal(9,4) NOT NULL CONSTRAINT [DF_TaxCategory_TaxRatePct] DEFAULT (0) ,

 CONSTRAINT [PK_TAX_CATEGORY] PRIMARY KEY NONCLUSTERED ([TAX_CATEGORY_ID] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference table defining tax categories and their applicable tax rates', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'TAX_CATEGORY_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the tax category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'TAX_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'TAX_CATEGORY_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the tax category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'TAX_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'TAX_CATEGORY_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Tax rate percentage for this category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'TAX_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'TAX_RATE_PCT';
GO