-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[CustomerContract]
CREATE TABLE [dbo].[CustomerContract]
(
 [CustomerContractId] int IDENTITY (1, 1) NOT NULL ,
 [CustomerId]         int NOT NULL ,
 [ContractNumber]     nvarchar(60) NOT NULL ,
 [ContractName]       nvarchar(200) NULL ,
 [StartDate]          date NOT NULL ,
 [EndDate]            date NULL ,
 [PriceListId]        int NULL ,
 [Status]             nvarchar(30) NOT NULL CONSTRAINT [DF_CustomerContract_Status] DEFAULT (N'Active') ,
 [CreatedAt]          datetime2(3) NOT NULL CONSTRAINT [DF_CustomerContract_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [CategoryID]         int NOT NULL ,

 CONSTRAINT [PK_CustomerContract] PRIMARY KEY NONCLUSTERED ([CustomerContractId] ASC),
 CONSTRAINT [UQ_CustomerContract_Number] UNIQUE NONCLUSTERED ([ContractNumber] ASC),
 CONSTRAINT [FK_3] FOREIGN KEY ([CategoryID])  REFERENCES [pos].[Category]([CategoryID]),
 CONSTRAINT [FK_CustomerContract_Customer] FOREIGN KEY ([CustomerId])  REFERENCES [dbo].[Customer]([CustomerId]),
 CONSTRAINT [FK_CustomerContract_PriceList] FOREIGN KEY ([PriceListId])  REFERENCES [dbo].[PriceList]([PriceListId]),
 CONSTRAINT [CK_CustomerContract_Range] CHECK ( EndDate IS NULL OR EndDate >= StartDate )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents legal contracts between the company and customers, defining terms and pricing', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the contract', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'CustomerContractId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the customer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'CustomerId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique business identifier for the contract', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'ContractNumber';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name or title of the contract', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'ContractName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Date when the contract becomes effective', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'StartDate';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Date when the contract expires', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'EndDate';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the price list governing this contract', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'PriceListId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Current status of the contract (Active, Expired, Archived, etc.)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'Status';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the contract record was created', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for product category', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerContract', @level2type=N'COLUMN', @level2name=N'CategoryID';
GO