-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[PRICE_LIST_T]
CREATE TABLE [DBO].[PRICE_LIST_T]
(
 [PRICE_LIST_ID]   int IDENTITY (1, 1) NOT NULL ,
 [PRICE_LIST_CODE] nvarchar(50) NOT NULL ,
 [PRICE_LIST_NAME] nvarchar(200) NOT NULL ,
 [CURRENCY_CODE]   char(3) NOT NULL ,
 [IS_ACTIVE]       bit NOT NULL CONSTRAINT [DF_PriceList_IsActive] DEFAULT (1) ,
 [EFFECTIVE_FROM]  date NOT NULL ,
 [EFFECTIVE_TO]    date NULL ,

 CONSTRAINT [PK_PRICE_LIST] PRIMARY KEY NONCLUSTERED ([PRICE_LIST_ID] ASC),
 CONSTRAINT [UQ_PRICE_LIST_CODE] UNIQUE NONCLUSTERED ([PRICE_LIST_CODE] ASC),
 CONSTRAINT [FK_PRICE_LIST_CURRENCY] FOREIGN KEY ([CURRENCY_CODE])  REFERENCES [DBO].[CURRENCY_T]([CURRENCY_CODE]),
 CONSTRAINT [CK_PRICE_LIST_EFFECTIVE_RANGE] CHECK ( EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents a set of pricing rules for products, services, bundles, and offerings in a specific currency', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the price list', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'PRICE_LIST_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique code identifying the price list', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'PRICE_LIST_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name of the price list', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'PRICE_LIST_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Currency in which prices are specified', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'CURRENCY_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the price list is currently in use', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'IS_ACTIVE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Date when the price list becomes effective', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'EFFECTIVE_FROM';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Date when the price list expires', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'PRICE_LIST_T', @level2type=N'COLUMN', @level2name=N'EFFECTIVE_TO';
GO