-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[SalesOrderLine]
CREATE TABLE [dbo].[SalesOrderLine]
(
 [SalesOrderLineId] int IDENTITY (1, 1) NOT NULL ,
 [SalesOrderId]     int NOT NULL ,
 [LineNumber]       int NOT NULL ,
 [LineType]         nvarchar(20) NOT NULL ,
 [OfferingId]       int NULL ,
 [BundleId]         int NULL ,
 [Quantity]         decimal(18,4) NOT NULL ,
 [UnitPrice]        decimal(18,4) NOT NULL ,
 [DiscountPct]      decimal(9,4) NOT NULL CONSTRAINT [DF_SalesOrderLine_Discount] DEFAULT (0) ,
 [TaxPct]           decimal(9,4) NOT NULL CONSTRAINT [DF_SalesOrderLine_Tax] DEFAULT (0) ,
 [StartDate]        date NULL ,
 [EndDate]          date NULL ,
 [CreatedAt]        datetime2(3) NOT NULL CONSTRAINT [DF_SalesOrderLine_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [ContractItemId]   int NOT NULL ,

 CONSTRAINT [PK_SalesOrderLine] PRIMARY KEY NONCLUSTERED ([SalesOrderLineId] ASC),
 CONSTRAINT [UQ_SalesOrderLine] UNIQUE NONCLUSTERED ([SalesOrderId] ASC, [LineNumber] ASC),
 CONSTRAINT [FK_4] FOREIGN KEY ([ContractItemId])  REFERENCES [dbo].[ContractItem]([ContractItemId]),
 CONSTRAINT [FK_SalesOrderLine_Bundle] FOREIGN KEY ([BundleId])  REFERENCES [dbo].[Bundle]([BundleId]),
 CONSTRAINT [FK_SalesOrderLine_Offering] FOREIGN KEY ([OfferingId])  REFERENCES [dbo].[Offering]([OfferingId]),
 CONSTRAINT [FK_SalesOrderLine_Order] FOREIGN KEY ([SalesOrderId])  REFERENCES [dbo].[SalesOrder]([SalesOrderId]),
 CONSTRAINT [CK_SalesOrderLine_Type] CHECK ( (LineType = N'Offering' AND OfferingId IS NOT NULL AND BundleId IS NULL)
    OR
    (LineType = N'Bundle' AND BundleId IS NOT NULL AND OfferingId IS NULL) ),
 CONSTRAINT [CK_SalesOrderLine_Discount] CHECK ( DiscountPct >= 0 AND DiscountPct <= 100 ),
 CONSTRAINT [CK_SalesOrderLine_Dates] CHECK ( EndDate IS NULL OR StartDate IS NULL OR EndDate >= StartDate )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents individual line items within a sales order', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the sales order line', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'SalesOrderLineId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent sales order', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'SalesOrderId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Sequential line number within the order', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'LineNumber';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Type of line item: ''Offering'' or ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'LineType';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to an offering, when LineType is ''Offering''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'OfferingId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a bundle, when LineType is ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'BundleId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Quantity ordered of this line item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'Quantity';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unit price for this line item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'UnitPrice';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Discount percentage applied to this line item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'DiscountPct';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Tax percentage applied to this line item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'TaxPct';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Service start date for subscription-based line items', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'StartDate';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Service end date for subscription-based line items', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'EndDate';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the order line was created', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the contract item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SalesOrderLine', @level2type=N'COLUMN', @level2name=N'ContractItemId';
GO