-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[SERVICE_CATEGORY_T]
CREATE TABLE [DBO].[SERVICE_CATEGORY_T]
(
 [SERVICE_CATEGORY_ID]        int IDENTITY (1, 1) NOT NULL ,
 [CATEGORY_NAME]              nvarchar(100) NOT NULL ,
 [PARENT_SERVICE_CATEGORY_ID] int NULL ,

 CONSTRAINT [PK_SERVICE_CATEGORY] PRIMARY KEY NONCLUSTERED ([SERVICE_CATEGORY_ID] ASC),
 CONSTRAINT [UQ_SERVICE_CATEGORY_NAME] UNIQUE NONCLUSTERED ([CATEGORY_NAME] ASC),
 CONSTRAINT [FK_SERVICE_CATEGORY_PARENT] FOREIGN KEY ([PARENT_SERVICE_CATEGORY_ID])  REFERENCES [DBO].[SERVICE_CATEGORY_T]([SERVICE_CATEGORY_ID])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Hierarchical categories for classifying services', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_CATEGORY_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the service category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'SERVICE_CATEGORY_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the service category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'CATEGORY_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent category for hierarchical classification', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_CATEGORY_T', @level2type=N'COLUMN', @level2name=N'PARENT_SERVICE_CATEGORY_ID';
GO