-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[OfferingType]
CREATE TABLE [dbo].[OfferingType]
(
 [OfferingTypeId]   int IDENTITY (1, 1) NOT NULL ,
 [OfferingTypeName] nvarchar(50) NOT NULL ,

 CONSTRAINT [PK_OfferingType] PRIMARY KEY NONCLUSTERED ([OfferingTypeId] ASC),
 CONSTRAINT [UQ_OfferingType_Name] UNIQUE NONCLUSTERED ([OfferingTypeName] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference table for classifying different types of offerings', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OfferingType';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the offering type', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OfferingType', @level2type=N'COLUMN', @level2name=N'OfferingTypeId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the offering type (e.g., Standard, Premium, Enterprise)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OfferingType', @level2type=N'COLUMN', @level2name=N'OfferingTypeName';
GO