-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[ContractItem]
CREATE TABLE [dbo].[ContractItem]
(
 [ContractItemId]     int IDENTITY (1, 1) NOT NULL ,
 [CustomerContractId] int NOT NULL ,
 [ItemType]           nvarchar(20) NOT NULL ,
 [OfferingId]         int NULL ,
 [BundleId]           int NULL ,
 [UnitPriceOverride]  decimal(18,4) NULL ,
 [DiscountPct]        decimal(9,4) NULL ,
 [MaxQuantity]        decimal(18,4) NULL ,
 [column1]            decimal NOT NULL ,

 CONSTRAINT [PK_ContractItem] PRIMARY KEY NONCLUSTERED ([ContractItemId] ASC),
 CONSTRAINT [FK_ContractItem_Bundle] FOREIGN KEY ([BundleId])  REFERENCES [dbo].[Bundle]([BundleId]),
 CONSTRAINT [FK_ContractItem_Contract] FOREIGN KEY ([CustomerContractId])  REFERENCES [dbo].[CustomerContract]([CustomerContractId]),
 CONSTRAINT [FK_ContractItem_Offering] FOREIGN KEY ([OfferingId])  REFERENCES [dbo].[Offering]([OfferingId]),
 CONSTRAINT [CK_ContractItem_Type] CHECK ( (ItemType = N'Offering' AND OfferingId IS NOT NULL AND BundleId IS NULL)
    OR (ItemType = N'Bundle' AND BundleId IS NOT NULL AND OfferingId IS NULL) ),
 CONSTRAINT [CK_ContractItem_Discount] CHECK ( DiscountPct IS NULL OR (DiscountPct >= 0 AND DiscountPct <= 100) )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents offerings or bundles included in a customer contract with pricing overrides', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the contract item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'ContractItemId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent customer contract', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'CustomerContractId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Type of item: ''Offering'' or ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'ItemType';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to an offering, when ItemType is ''Offering''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'OfferingId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a bundle, when ItemType is ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'BundleId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Custom unit price for this contract item, overriding the standard price list', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'UnitPriceOverride';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Discount percentage applied to this contract item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'DiscountPct';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Maximum quantity that can be ordered for this contract item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ContractItem', @level2type=N'COLUMN', @level2name=N'MaxQuantity';
GO