-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[CustomerLocation]
CREATE TABLE [dbo].[CustomerLocation]
(
 [CustomerLocationId] int IDENTITY (1, 1) NOT NULL ,
 [CustomerId]         int NOT NULL ,
 [LocationCode]       nvarchar(50) NOT NULL ,
 [LocationName]       nvarchar(200) NOT NULL ,
 [AddressLine1]       nvarchar(200) NULL ,
 [AddressLine2]       nvarchar(200) NULL ,
 [City]               nvarchar(100) NULL ,
 [StateProvince]      nvarchar(100) NULL ,
 [PostalCode]         nvarchar(20) NULL ,
 [CountryCode]        char(2) NULL ,
 [IsPrimary]          bit NOT NULL CONSTRAINT [DF_CustomerLocation_IsPrimary] DEFAULT (0) ,
 [CreatedAt]          datetime2(3) NOT NULL CONSTRAINT [DF_CustomerLocation_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,

 CONSTRAINT [PK_CustomerLocation] PRIMARY KEY NONCLUSTERED ([CustomerLocationId] ASC),
 CONSTRAINT [UQ_CustomerLocation] UNIQUE NONCLUSTERED ([CustomerId] ASC, [LocationCode] ASC),
 CONSTRAINT [FK_CustomerLocation_Customer] FOREIGN KEY ([CustomerId])  REFERENCES [dbo].[Customer]([CustomerId])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents physical locations or addresses associated with a customer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the customer location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'CustomerLocationId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the customer organization', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'CustomerId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique code identifying the location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'LocationCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name of the location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'LocationName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'First line of the physical address', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'AddressLine1';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Second line of the physical address (apartment, suite, etc.)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'AddressLine2';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'City name of the location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'City';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'State or province of the location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'StateProvince';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Postal or zip code of the location', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'PostalCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'ISO 3166-1 alpha-2 country code', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'CountryCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if this is the primary location for the customer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'IsPrimary';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the location record was created', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CustomerLocation', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO