-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[Currency]
CREATE TABLE [dbo].[Currency]
(
 [CurrencyCode] char(3) NOT NULL ,
 [CurrencyName] nvarchar(50) NOT NULL ,

 CONSTRAINT [PK_Currency] PRIMARY KEY NONCLUSTERED ([CurrencyCode] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference table for supported currencies used in pricing and transactions', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Currency';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'ISO 4217 three-letter currency code', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Currency', @level2type=N'COLUMN', @level2name=N'CurrencyCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Full name of the currency', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Currency', @level2type=N'COLUMN', @level2name=N'CurrencyName';
GO