-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[Supplier]
CREATE TABLE [dbo].[Supplier]
(
 [SupplierId]   int IDENTITY (1, 1) NOT NULL ,
 [SupplierName] nvarchar(200) NOT NULL ,
 [SupplierCode] nvarchar(50) NULL ,
 [IsActive]     bit NOT NULL CONSTRAINT [DF_Supplier_IsActive] DEFAULT (1) ,

 CONSTRAINT [PK_Supplier] PRIMARY KEY NONCLUSTERED ([SupplierId] ASC),
 CONSTRAINT [UQ_Supplier_Name] UNIQUE NONCLUSTERED ([SupplierName] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents suppliers/vendors from whom products are sourced', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the supplier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier', @level2type=N'COLUMN', @level2name=N'SupplierId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the supplier organization', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier', @level2type=N'COLUMN', @level2name=N'SupplierName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Business identifier for the supplier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier', @level2type=N'COLUMN', @level2name=N'SupplierCode';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the supplier is currently active', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier', @level2type=N'COLUMN', @level2name=N'IsActive';
GO