-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[CUSS_T]
CREATE TABLE [DBO].[CUSS_T]
(
 [CUSS_ID]               int IDENTITY (1, 1) NOT NULL ,
 [CUSS_NUMBER]           nvarchar(30) NOT NULL ,
 [CUSS_NAME]             nvarchar(200) NOT NULL ,
 [CUSS_STATUS]           nvarchar(30) NOT NULL CONSTRAINT [DF_Customer_Status] DEFAULT (N'Active') ,
 [TAX_ID]                nvarchar(50) NULL ,
 [DEFAULT_CURRENCY_CODE] char(3) NOT NULL CONSTRAINT [DF_Customer_Currency] DEFAULT ('USD') ,
 [CREATED_AT]            datetime2(3) NOT NULL CONSTRAINT [DF_Customer_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [UPDATED_AT]            datetime2(3) NOT NULL CONSTRAINT [DF_Customer_UpdatedAt] DEFAULT (SYSUTCDATETIME()) ,

 CONSTRAINT [PK_CUSS] PRIMARY KEY NONCLUSTERED ([CUSS_ID] ASC),
 CONSTRAINT [UQ_CUSS_CUSS_NUMBER] UNIQUE NONCLUSTERED ([CUSS_NUMBER] ASC),
 CONSTRAINT [FK_CUSS_CURRENCY] FOREIGN KEY ([DEFAULT_CURRENCY_CODE])  REFERENCES [DBO].[CURRENCY_T]([CURRENCY_CODE])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents customer organizations that purchase products, services, and bundles', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the customer', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CUSS_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique business identifier for the customer', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CUSS_NUMBER';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Legal name of the customer organization', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CUSS_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Current status of the customer (Active, Inactive, Prospect, etc.)', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CUSS_STATUS';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Tax identification number or VAT number of the customer', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'TAX_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Default currency for customer transactions and invoicing', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'DEFAULT_CURRENCY_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the customer record was created', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CREATED_AT';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the customer record was last updated', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'UPDATED_AT';
GO