-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[SERVICE_T]
CREATE TABLE [DBO].[SERVICE_T]
(
 [SERVICE_ID]            int IDENTITY (1, 1) NOT NULL ,
 [SERVICE_CODE]          nvarchar(60) NOT NULL ,
 [SERVICE_NAME]          nvarchar(200) NOT NULL ,
 [SERVICE_DESCRIPTION]   nvarchar(1000) NULL ,
 [SERVICE_CATEGORY_ID]   int NULL ,
 [DEFAULT_DURATION_DAYS] int NULL ,
 [IS_METERED]            bit NOT NULL CONSTRAINT [DF_Service_IsMetered] DEFAULT (0) ,
 [UOM_CODE]              nvarchar(10) NOT NULL ,
 [TAX_CATEGORY_ID]       int NULL ,
 [IS_ACTIVE]             bit NOT NULL CONSTRAINT [DF_Service_IsActive] DEFAULT (1) ,
 [CREATED_AT]            datetime2(3) NOT NULL CONSTRAINT [DF_Service_CreatedAt] DEFAULT (SYSUTCDATETIME()) ,
 [UPDATED_AT]            datetime2(3) NOT NULL CONSTRAINT [DF_Service_UpdatedAt] DEFAULT (SYSUTCDATETIME()) ,

 CONSTRAINT [PK_SERVICE] PRIMARY KEY NONCLUSTERED ([SERVICE_ID] ASC),
 CONSTRAINT [UQ_SERVICE_CODE] UNIQUE NONCLUSTERED ([SERVICE_CODE] ASC),
 CONSTRAINT [FK_SERVICE_CATEGORY] FOREIGN KEY ([SERVICE_CATEGORY_ID])  REFERENCES [DBO].[SERVICE_CATEGORY_T]([SERVICE_CATEGORY_ID]),
 CONSTRAINT [FK_SERVICE_TAX_CATEGORY] FOREIGN KEY ([TAX_CATEGORY_ID])  REFERENCES [DBO].[TAX_CATEGORY_T]([TAX_CATEGORY_ID]),
 CONSTRAINT [FK_SERVICE_UOM] FOREIGN KEY ([UOM_CODE])  REFERENCES [DBO].[UNIT_OF_MEASURE_T]([UOM_CODE])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents services that can be sold individually or as part of offerings and bundles', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'SERVICE_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique code identifying the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'SERVICE_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name of the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'SERVICE_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Detailed description of the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'SERVICE_DESCRIPTION';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the service category', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'SERVICE_CATEGORY_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Default duration in days for this service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'DEFAULT_DURATION_DAYS';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the service is usage-based (metered)', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'IS_METERED';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unit of measure for the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'UOM_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the tax category for the service', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'TAX_CATEGORY_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the service is currently available for sale', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'IS_ACTIVE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the service record was created', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'CREATED_AT';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the service record was last updated', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'SERVICE_T', @level2type=N'COLUMN', @level2name=N'UPDATED_AT';
GO