-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [DBO].[BUNDLE_ITEM_T]
CREATE TABLE [DBO].[BUNDLE_ITEM_T]
(
 [BUNDLE_ITEM_ID]  int IDENTITY (1, 1) NOT NULL ,
 [BUNDLE_ID]       int NOT NULL ,
 [OFFERING_ID]     int NULL ,
 [CHILD_BUNDLE_ID] int NULL ,
 [ITEM_TYPE]       nvarchar(20) NOT NULL ,
 [QUANTITY]        decimal(18,4) NOT NULL CONSTRAINT [DF_BundleItem_Qty] DEFAULT (1) ,
 [SORT_ORDER]      int NOT NULL CONSTRAINT [DF_BundleItem_Sort] DEFAULT (1) ,
 [IS_OPTIONAL]     bit NOT NULL CONSTRAINT [DF_BundleItem_IsOptional] DEFAULT (0) ,

 CONSTRAINT [PK_BUNDLE_ITEM] PRIMARY KEY NONCLUSTERED ([BUNDLE_ITEM_ID] ASC),
 CONSTRAINT [UQ_BUNDLE_ITEM_UNIQUE_LINE] UNIQUE NONCLUSTERED ([BUNDLE_ID] ASC, [ITEM_TYPE] ASC, [OFFERING_ID] ASC, [CHILD_BUNDLE_ID] ASC),
 CONSTRAINT [FK_BUNDLE_ITEM_BUNDLE] FOREIGN KEY ([BUNDLE_ID])  REFERENCES [DBO].[BUNDLE_T]([BUNDLE_ID]),
 CONSTRAINT [FK_BUNDLE_ITEM_CHILD_BUNDLE] FOREIGN KEY ([CHILD_BUNDLE_ID])  REFERENCES [DBO].[BUNDLE_T]([BUNDLE_ID]),
 CONSTRAINT [FK_BUNDLE_ITEM_OFFERING] FOREIGN KEY ([OFFERING_ID])  REFERENCES [DBO].[OFFERING_T]([OFFERING_ID]),
 CONSTRAINT [CK_BUNDLE_ITEM_TYPE] CHECK ( (ItemType = N'Offering' AND OfferingId IS NOT NULL AND ChildBundleId IS NULL)
    OR
    (ItemType = N'Bundle' AND ChildBundleId IS NOT NULL AND OfferingId IS NULL AND ChildBundleId <> BundleId) )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents individual items within a bundle, linking offerings or child bundles to parent bundles', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the bundle item', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'BUNDLE_ITEM_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent bundle', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'BUNDLE_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to an offering included in the bundle, when ItemType is ''Offering''', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'OFFERING_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a child bundle included in the parent bundle, when ItemType is ''Bundle''', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'CHILD_BUNDLE_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Type of item: ''Offering'' or ''Bundle''', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'ITEM_TYPE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Quantity of the item included in the bundle', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'QUANTITY';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display order of the item within the bundle', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'SORT_ORDER';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating if the item is optional within the bundle', @level0type = N'SCHEMA', @level0name = N'DBO', @level1type = N'TABLE', @level1name = N'BUNDLE_ITEM_T', @level2type=N'COLUMN', @level2name=N'IS_OPTIONAL';
GO