-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [dbo].[PriceListItem]
CREATE TABLE [dbo].[PriceListItem]
(
 [PriceListItemId] int IDENTITY (1, 1) NOT NULL ,
 [PriceListId]     int NOT NULL ,
 [ItemType]        nvarchar(20) NOT NULL ,
 [ProductId]       int NULL ,
 [ServiceId]       int NULL ,
 [OfferingId]      int NULL ,
 [BundleId]        int NULL ,
 [UnitPrice]       decimal(18,4) NOT NULL ,
 [MinQuantity]     decimal(18,4) NOT NULL CONSTRAINT [DF_PriceListItem_MinQty] DEFAULT (1) ,
 [MaxQuantity]     decimal(18,4) NULL ,

 CONSTRAINT [PK_PriceListItem] PRIMARY KEY NONCLUSTERED ([PriceListItemId] ASC),
 CONSTRAINT [UQ_PriceListItem_Unique] UNIQUE NONCLUSTERED ([PriceListId] ASC, [ItemType] ASC, [ProductId] ASC, [ServiceId] ASC, [OfferingId] ASC, [BundleId] ASC, [MinQuantity] ASC),
 CONSTRAINT [FK_PriceListItem_Bundle] FOREIGN KEY ([BundleId])  REFERENCES [dbo].[Bundle]([BundleId]),
 CONSTRAINT [FK_PriceListItem_Offering] FOREIGN KEY ([OfferingId])  REFERENCES [dbo].[Offering]([OfferingId]),
 CONSTRAINT [FK_PriceListItem_PriceList] FOREIGN KEY ([PriceListId])  REFERENCES [dbo].[PriceList]([PriceListId]),
 CONSTRAINT [FK_PriceListItem_Product] FOREIGN KEY ([ProductId])  REFERENCES [dbo].[Product]([ProductId]),
 CONSTRAINT [FK_PriceListItem_Service] FOREIGN KEY ([ServiceId])  REFERENCES [dbo].[Service]([ServiceId]),
 CONSTRAINT [CK_PriceListItem_Type] CHECK ( (ItemType = N'Product' AND ProductId IS NOT NULL AND ServiceId IS NULL AND OfferingId IS NULL AND BundleId IS NULL)
    OR (ItemType = N'Service' AND ServiceId IS NOT NULL AND ProductId IS NULL AND OfferingId IS NULL AND BundleId IS NULL)
    OR (ItemType = N'Offering' AND OfferingId IS NOT NULL AND ProductId IS NULL AND ServiceId IS NULL AND BundleId IS NULL)
    OR (ItemType = N'Bundle' AND BundleId IS NOT NULL AND ProductId IS NULL AND ServiceId IS NULL AND OfferingId IS NULL) ),
 CONSTRAINT [CK_PriceListItem_QtyRange] CHECK ( MaxQuantity IS NULL OR MaxQuantity >= MinQuantity )
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Represents individual price entries for products, services, bundles, or offerings in a price list', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the price list item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'PriceListItemId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to the parent price list', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'PriceListId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Type of item: ''Product'', ''Service'', ''Offering'', or ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'ItemType';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a product, when ItemType is ''Product''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'ProductId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a service, when ItemType is ''Service''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'ServiceId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to an offering, when ItemType is ''Offering''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'OfferingId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reference to a bundle, when ItemType is ''Bundle''', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'BundleId';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Price per unit of the item', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'UnitPrice';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Minimum quantity required for this price tier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'MinQuantity';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Maximum quantity allowed for this price tier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PriceListItem', @level2type=N'COLUMN', @level2name=N'MaxQuantity';
GO