-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** DIM_EMPLOYEE_copy_1
CREATE TABLE DIM_EMPLOYEE_copy_1
(
 EMPLOYEE_HKEY    binary NOT NULL CONSTRAINT PK_DIM_EMPLOYEE PRIMARY KEY,
 EMPLOYEE_ID      decimal(10,0) NOT NULL,
 FIRST_NAME       string,
 LAST_NAME        string,
 ROLE_DESCRIPTION string,
 BIRTH_DATE       date NOT NULL
);
