-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Eaton Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** dim_TABLE_9_T
CREATE TABLE dim_TABLE_9_T
(
 from_dts     timestamp_ntz(9) NOT NULL,
 to_dts       timestamp_ntz(9) NOT NULL,
 CLAIM_NUMBER varchar(16777216) NOT NULL, -- From template: "Claim Number"
 load_dts     timestamp_ntz(9) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( from_dts )
);
