-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [ecommerce].[Product]
CREATE TABLE [ecommerce].[Product]
(
 [ProductID]     int IDENTITY (1, 1) NOT NULL ,
 [CategoryID]    int NOT NULL ,
 [ProductName]   nvarchar(200) NOT NULL ,
 [Description]   nvarchar(1000) NULL ,
 [Price]         decimal(18, 2) NOT NULL ,
 [StockQuantity] int NOT NULL CONSTRAINT [DF_Product_StockQuantity] DEFAULT 0 ,
 [ImageURL]      nvarchar(500) NULL ,
 [IsActive]      bit NOT NULL CONSTRAINT [DF_Product_IsActive] DEFAULT 1 ,
 [CreatedAt]     datetime2(3) NOT NULL CONSTRAINT [DF_Product_CreatedAt] DEFAULT SYSUTCDATETIME() ,
 [UpdatedAt]     datetime2(3) NOT NULL CONSTRAINT [DF_Product_UpdatedAt] DEFAULT SYSUTCDATETIME() ,

 CONSTRAINT [PK_Product] PRIMARY KEY NONCLUSTERED ([ProductID] ASC),
 CONSTRAINT [UQ_Product_Name] UNIQUE NONCLUSTERED ([ProductName] ASC),
 CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryID])  REFERENCES [ecommerce].[Category]([CategoryID]),
 CONSTRAINT [CK_Product_Price] CHECK ( Price > 0 ),
 CONSTRAINT [CK_Product_StockQuantity] CHECK ( StockQuantity >= 0 )
);
GO

CREATE NONCLUSTERED INDEX [IX_Product_CategoryID] ON [ecommerce].[Product] 
 (
  [CategoryID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [IX_Product_IsActive] ON [ecommerce].[Product] 
 (
  [IsActive] ASC
 )

GO

CREATE NONCLUSTERED INDEX [IX_Product_Price] ON [ecommerce].[Product] 
 (
  [Price] ASC
 )

GO