-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [ecommerce].[Category]
CREATE TABLE [ecommerce].[Category]
(
 [CategoryID]   int IDENTITY (1, 1) NOT NULL ,
 [CategoryName] nvarchar(100) NOT NULL ,
 [Description]  nvarchar(500) NULL ,
 [CreatedAt]    datetime2(3) NOT NULL CONSTRAINT [DF_Category_CreatedAt] DEFAULT SYSUTCDATETIME() ,
 [UpdatedAt]    datetime2(3) NOT NULL CONSTRAINT [DF_Category_UpdatedAt] DEFAULT SYSUTCDATETIME() ,

 CONSTRAINT [PK_Category] PRIMARY KEY NONCLUSTERED ([CategoryID] ASC),
 CONSTRAINT [UQ_Category_Name] UNIQUE NONCLUSTERED ([CategoryName] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Master table of product categories used for organizing and classifying products in the ecommerce catalog.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the category.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category', @level2type=N'COLUMN', @level2name=N'CategoryID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Display name of the category.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category', @level2type=N'COLUMN', @level2name=N'CategoryName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Detailed description of the category and its purpose.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category', @level2type=N'COLUMN', @level2name=N'Description';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the category record was created.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the category record was last updated.', @level0type = N'SCHEMA', @level0name = N'ecommerce', @level1type = N'TABLE', @level1name = N'Category', @level2type=N'COLUMN', @level2name=N'UpdatedAt';
GO