-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [ECOMMERCE].[CUSS_T]
CREATE TABLE [ECOMMERCE].[CUSS_T]
(
 [CUSS_ID]        int IDENTITY (1, 1) NOT NULL ,
 [FIRST_NAME]     nvarchar(100) NOT NULL ,
 [LAST_NAME]      nvarchar(100) NOT NULL ,
 [EMAIL]          nvarchar(255) NOT NULL ,
 [PHONE]          nvarchar(20) NULL ,
 [ADDRESS]        nvarchar(500) NOT NULL ,
 [CITY]           nvarchar(100) NULL ,
 [STATE_PROVINCE] nvarchar(100) NULL ,
 [POSTAL_CODE]    nvarchar(20) NULL ,
 [COUNTRY]        nvarchar(100) NULL ,
 [IS_ACTIVE]      bit NOT NULL CONSTRAINT [DF_Customer_IsActive] DEFAULT 1 ,
 [CREATED_AT]     datetime2(3) NOT NULL CONSTRAINT [DF_Customer_CreatedAt] DEFAULT SYSUTCDATETIME() ,
 [UPDATED_AT]     datetime2(3) NOT NULL CONSTRAINT [DF_Customer_UpdatedAt] DEFAULT SYSUTCDATETIME() ,

 CONSTRAINT [PK_CUSS] PRIMARY KEY NONCLUSTERED ([CUSS_ID] ASC),
 CONSTRAINT [UQ_CUSS_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_CUSS_EMAIL] ON [ECOMMERCE].[CUSS_T] 
 (
  [EMAIL] ASC
 )

GO

CREATE NONCLUSTERED INDEX [IX_CUSS_IS_ACTIVE] ON [ECOMMERCE].[CUSS_T] 
 (
  [IS_ACTIVE] ASC
 )

GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Stores customer profile and contact information for e-commerce transactions', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the customer', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CUSS_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Customer''s first name', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'FIRST_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Customer''s last name', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'LAST_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Customer''s email address', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'EMAIL';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Customer''s phone number', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'PHONE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Customer''s street address', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'ADDRESS';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'City where the customer is located', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CITY';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'State or province where the customer is located', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'STATE_PROVINCE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Postal or ZIP code for the customer''s address', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'POSTAL_CODE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Country where the customer is located', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'COUNTRY';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Flag indicating whether the customer account is active', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'IS_ACTIVE';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the customer record was created', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'CREATED_AT';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the customer record was last modified', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CUSS_T', @level2type=N'COLUMN', @level2name=N'UPDATED_AT';
GO