-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [ecommerce].[Order]
CREATE TABLE [ecommerce].[Order]
(
 [OrderID]               int IDENTITY (1, 1) NOT NULL ,
 [CustomerID]            int NOT NULL ,
 [OrderDate]             date NOT NULL CONSTRAINT [DF_Order_OrderDate] DEFAULT CONVERT(DATE, SYSUTCDATETIME()) ,
 [TotalAmount]           decimal(18, 2) NOT NULL CONSTRAINT [DF_Order_TotalAmount] DEFAULT 0 ,
 [Status]                nvarchar(30) NOT NULL CONSTRAINT [DF_Order_Status] DEFAULT 'Pending' ,
 [ShippingAddress]       nvarchar(500) NOT NULL ,
 [ShippingCity]          nvarchar(100) NULL ,
 [ShippingStateProvince] nvarchar(100) NULL ,
 [ShippingPostalCode]    nvarchar(20) NULL ,
 [ShippingCountry]       nvarchar(100) NULL ,
 [Notes]                 nvarchar(1000) NULL ,
 [CreatedAt]             datetime2(3) NOT NULL CONSTRAINT [DF_Order_CreatedAt] DEFAULT SYSUTCDATETIME() ,
 [UpdatedAt]             datetime2(3) NOT NULL CONSTRAINT [DF_Order_UpdatedAt] DEFAULT SYSUTCDATETIME() ,

 CONSTRAINT [PK_Order] PRIMARY KEY NONCLUSTERED ([OrderID] ASC),
 CONSTRAINT [FK_Order_Customer] FOREIGN KEY ([CustomerID])  REFERENCES [ecommerce].[Customer]([CustomerID]),
 CONSTRAINT [CK_Order_Status] CHECK ( Status IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Returned') ),
 CONSTRAINT [CK_Order_TotalAmount] CHECK ( TotalAmount >= 0 )
);
GO

CREATE NONCLUSTERED INDEX [IX_Order_CustomerID] ON [ecommerce].[Order] 
 (
  [CustomerID] ASC
 )

GO

CREATE NONCLUSTERED INDEX [IX_Order_OrderDate] ON [ecommerce].[Order] 
 (
  [OrderDate] ASC
 )

GO

CREATE NONCLUSTERED INDEX [IX_Order_Status] ON [ecommerce].[Order] 
 (
  [Status] ASC
 )

GO