-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [ECOMMERCE].[CATEGORY_T]
CREATE TABLE [ECOMMERCE].[CATEGORY_T]
(
 [CATEGORY_ID]   int IDENTITY (1, 1) NOT NULL ,
 [CATEGORY_NAME] nvarchar(100) NOT NULL ,
 [DESCRIPTION]   nvarchar(500) NULL ,
 [CREATED_AT]    datetime2(3) NOT NULL CONSTRAINT [DF_Category_CreatedAt] DEFAULT SYSUTCDATETIME() ,
 [UPDATED_AT]    datetime2(3) NOT NULL CONSTRAINT [DF_Category_UpdatedAt] DEFAULT SYSUTCDATETIME() ,

 CONSTRAINT [PK_CATEGORY] PRIMARY KEY NONCLUSTERED ([CATEGORY_ID] ASC),
 CONSTRAINT [UQ_CATEGORY_NAME] UNIQUE NONCLUSTERED ([CATEGORY_NAME] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Master table containing product categories', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the category', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T', @level2type=N'COLUMN', @level2name=N'CATEGORY_ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Name of the product category', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T', @level2type=N'COLUMN', @level2name=N'CATEGORY_NAME';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Detailed description of the product category', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T', @level2type=N'COLUMN', @level2name=N'DESCRIPTION';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the category record was created', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T', @level2type=N'COLUMN', @level2name=N'CREATED_AT';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp when the category record was last updated', @level0type = N'SCHEMA', @level0name = N'ECOMMERCE', @level1type = N'TABLE', @level1name = N'CATEGORY_T', @level2type=N'COLUMN', @level2name=N'UPDATED_AT';
GO