-- ************************** SqlDBM: Snowflake *************************
-- ***** Generated by SqlDBM: Data Warehouse by eric.ruiz@sqldbm.com ****
-- ************************************** EDW.NewFactCurrencyRate
CREATE TABLE EDW.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(3),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  number(38,0),
 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES EDW.DimCurrency ( CurrencyKey )
);
