-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.BKPF
CREATE TABLE ERP.BKPF
(
 BELNR char(10) NOT NULL COMMENT 'Unique identifier for the financial document. Assigned automatically by the system within a company code and fiscal year.',
 GJAHR char(4) COMMENT 'Fiscal year to which the document belongs. Helps in organizing documents chronologically and aids in reporting periods.',
 BUKRS char(4) COMMENT 'The company code for which the document is created. Identifies the legal entity responsible for the financial transaction.',
 BLART char(2) COMMENT 'Used to determine the document category, control posting rules, and ensure accurate reporting.',
 BLDAT date COMMENT 'The date entered by the user as the document’s creation date (e.g., invoice date).',

 CONSTRAINT PK_BKPF PRIMARY KEY ( BELNR )
)
COMMENT = 'Table contains the header information for accounting documents, such as document number, fiscal year, and company code.';
