-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.MARC_T
CREATE TABLE ERP.MARC_T
(
 MATNR       string(18) NOT NULL COMMENT 'Unique identifier for the material; links to the MARA table for general material data.',
 WERKS       string(4) NOT NULL COMMENT 'Code representing the plant where the material is managed; links to the T001W table.',
 DISMM       string(2) COMMENT 'Defines the MRP procedure for the material; links to the T438A table.',
 LastUpdated timestamp NOT NULL,
 CONSTRAINT MATNR PRIMARY KEY (MATNR, WERKS)
)
 COMMENT 'Table stores material-specific data for each plant, such as plant-specific settings for inventory management, procurement, and MRP.';
