-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.VBAP
CREATE TABLE IF NOT EXISTS ERP.VBAP
(
 VBELN     char(10) NOT NULL COMMENT 'Sales Document Number',
 POSNR     char(6) NOT NULL COMMENT 'Item Number',
 MATNR     char(18) COMMENT 'Material Number',
 KWMENG    decimal(13,3),
 ADDRESS_1 string NOT NULL,

 CONSTRAINT VBELN PRIMARY KEY ( VBELN, POSNR )
)
COMMENT = 'Table stores item-level data for sales orders, including materials, quantities, and pricing information.';
