-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.KNA_1
CREATE TABLE ERP.KNA_1
(
KUNNR  string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for the customer; primary key of the table.'),
LAND_1 string OPTIONS(description = 'Specifies the country of the customer; linked to table T005 for country codes.'),
NAME_1 string(50) OPTIONS(description = 'Primary name of the customer.'),
ORT_01 string(35) OPTIONS(description = 'City where the customer is located.'),
PSTLZ  string OPTIONS(description = 'Postal code for the customers address.'),
REGIO  string OPTIONS(description = 'Region or state of the customers location; linked to table T005S for region codes.'),
TELF_1 string OPTIONS(description = 'Primary contact telephone number for the customer.')
)
OPTIONS(description = 'Table contains general data for customers, such as address details and contact information.',
friendly_name = 'Customer Master Records');
