-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** ERP.EKPO
CREATE TABLE ERP.EKPO
(
EBELN string NOT NULL OPTIONS(description = 'Unique identifier for the purchasing document; links to the EKKO table.'),
EBELP string NOT NULL OPTIONS(description = 'Sequential number of the item within the purchasing document.'),
MATNR string OPTIONS(description = 'Identifier for the material; links to the MARA table.'),
MENGE numeric(13, 3) OPTIONS(description = 'Quantity Ordered'),
 PRIMARY KEY (EBELN, EBELP) NOT ENFORCED
)
OPTIONS(description = 'Stores detailed information for each item within purchasing documents such as purchase orders, contracts, and scheduling agreements.',
friendly_name = 'Purchasing Document Item');
