-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.ekko
CREATE TABLE erp.ekko
(
 EBELN varchar(10) NOT NULL COMMENT 'Unique identifier for the purchasing document.' CONSTRAINT pk_ekko PRIMARY KEY,
 BUKRS varchar(4) COMMENT 'Represents the company code associated with the purchasing document.',
 LIFNR varchar(10) COMMENT 'Account number of the vendor associated with the purchasing document.',
 ERDAT date COMMENT 'Date on Which the Record Was Created'
)
USING DELTA
 COMMENT 'Table stores the header information for purchase orders, including the vendor, company code, and document creation date.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
