-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.SILVER_VBRK
CREATE TABLE ERP.SILVER_VBRK
(
 VBELN        varchar(10) NOT NULL COMMENT 'Billing Document Number' CONSTRAINT PK_VBRK PRIMARY KEY,
 FKDAT        date COMMENT 'Billing Date',
 KUNNR        varchar(10) COMMENT 'Customer Number',
 NETWR        decimal(13,2) COMMENT 'Net Value of the Billing Document',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Table stores header information for billing documents, including the customer, billing date, and billing amount.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
