-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.T_001
CREATE TABLE IF NOT EXISTS ERP.T_001
(
 BUKRS     char(4) NOT NULL COMMENT 'Company code associated with the valuation area.',
 BUTXT     varchar(30) COMMENT 'Stores company code data',
 ADDRESS_1 string NOT NULL,

 CONSTRAINT PK_T_001 PRIMARY KEY ( BUKRS )
)
COMMENT = 'Table stores information about company codes in SAP, which represent separate legal entities within the system. Company codes are the highest organizational unit in Financial Accounting (FI).';
