-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.SILVER_VBAP
CREATE TABLE ERP.SILVER_VBAP
(
 VBELN        varchar(10) NOT NULL COMMENT 'Sales Document Number',
 POSNR        varchar(6) NOT NULL COMMENT 'Item Number',
 MATNR        varchar(18) COMMENT 'Material Number',
 KWMENG       decimal(13,3),
 Last_Updated timestamp NOT NULL,
 CONSTRAINT VBELN_34 PRIMARY KEY (VBELN, POSNR)
)
USING DELTA
 COMMENT 'Table stores item-level data for sales orders, including materials, quantities, and pricing information.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
