-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.bseg
CREATE TABLE erp.bseg
(
 BELNR varchar(10) NOT NULL COMMENT 'Unique identifier for the financial document within a company code and fiscal year.',
 GJAHR varchar(4) NOT NULL COMMENT 'Indicates the fiscal year in which the document was created.',
 BUZEI varchar(3) NOT NULL COMMENT 'Sequential number for each line item in the document.',
 HKONT varchar(10) COMMENT 'Specifies the G/L account impacted by the transaction.',
 DMBTR decimal(15,2) COMMENT 'The transaction amount converted to the local currency of the company code.',
 CONSTRAINT belnr PRIMARY KEY (BELNR, GJAHR, BUZEI)
)
USING DELTA
 COMMENT 'Table stores line items for accounting documents, capturing details such as general ledger accounts and amounts.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
