-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** ERP.BSEG
CREATE TABLE ERP.BSEG
(
BELNR string NOT NULL OPTIONS(description = 'Unique identifier for the financial document within a company code and fiscal year.'),
GJAHR string NOT NULL OPTIONS(description = 'Indicates the fiscal year in which the document was created.'),
BUZEI string NOT NULL OPTIONS(description = 'Sequential number for each line item in the document.'),
HKONT string OPTIONS(description = 'Specifies the G/L account impacted by the transaction.'),
DMBTR numeric(15, 2) OPTIONS(description = 'The transaction amount converted to the local currency of the company code.'),
 PRIMARY KEY (BELNR, GJAHR, BUZEI) NOT ENFORCED
)
OPTIONS(description = 'Table stores line items for accounting documents, capturing details such as general ledger accounts and amounts.',
friendly_name = 'Accounting Document Segment');
