-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.SILVER_PA_0001
CREATE TABLE ERP.SILVER_PA_0001
(
 PERNR        varchar(8) NOT NULL COMMENT 'Unique identifier for each employee. Serves as the primary key for HR master data records.' CONSTRAINT PK_PA_0001 PRIMARY KEY,
 WERKS        varchar(4) COMMENT 'Specifies the personnel area where the employee works.',
 BUKRS        varchar(4) COMMENT 'Represents the company code to which the employee is assigned.',
 ABKRS        varchar(2) COMMENT 'Identifies the payroll area to which the employee belongs.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Table contains HR master data, specifically related to employee organizational assignments (e.g., company code, personnel area).'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
