-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.vbrk
CREATE TABLE erp.vbrk
(
 VBELN varchar(10) NOT NULL COMMENT 'Billing Document Number' CONSTRAINT pk_vbrk PRIMARY KEY,
 FKDAT date COMMENT 'Billing Date',
 KUNNR varchar(10) COMMENT 'Customer Number',
 NETWR decimal(13,2) COMMENT 'Net Value of the Billing Document'
)
USING DELTA
 COMMENT 'Table stores header information for billing documents, including the customer, billing date, and billing amount.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
