-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.T_001_K
CREATE TABLE ERP.T_001_K
(
 BWKEY char(4) NOT NULL COMMENT 'Controlling Area',

 CONSTRAINT BUKRS PRIMARY KEY ( BWKEY )
)
COMMENT = 'Table is used to assign company codes to controlling areas. A controlling area is an organizational unit in SAP used for managing costs and internal accounting.';
