-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.pa0001
CREATE TABLE erp.pa0001
(
 PERNR varchar(8) NOT NULL COMMENT 'Unique identifier for each employee. Serves as the primary key for HR master data records.' CONSTRAINT pk_pa0001 PRIMARY KEY,
 WERKS varchar(4) COMMENT 'Specifies the personnel area where the employee works.',
 BUKRS varchar(4) COMMENT 'Represents the company code to which the employee is assigned.',
 ABKRS varchar(2) COMMENT 'Identifies the payroll area to which the employee belongs.'
)
USING DELTA
 COMMENT 'Table contains HR master data, specifically related to employee organizational assignments (e.g., company code, personnel area).'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
