-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.VBRK
CREATE TABLE ERP.VBRK
(
 VBELN char(10) NOT NULL COMMENT 'Billing Document Number',
 FKDAT date COMMENT 'Billing Date',
 KUNNR char(10) COMMENT 'Customer Number',
 NETWR decimal(13,2) COMMENT 'Net Value of the Billing Document',

 CONSTRAINT PK_VBRK PRIMARY KEY ( VBELN )
)
COMMENT = 'Table stores header information for billing documents, including the customer, billing date, and billing amount.';
