-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.PA_0001
CREATE TABLE ERP.PA_0001
(
PERNR string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each employee. Serves as the primary key for HR master data records.'),
WERKS string OPTIONS(description = 'Specifies the personnel area where the employee works.'),
BUKRS string OPTIONS(description = 'Represents the company code to which the employee is assigned.'),
ABKRS string OPTIONS(description = 'Identifies the payroll area to which the employee belongs.')
)
OPTIONS(description = 'Table contains HR master data, specifically related to employee organizational assignments (e.g., company code, personnel area).',
friendly_name = 'HR Master Data');
