-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** ERP.KNA1
CREATE TABLE ERP.KNA1
(
KUNNR string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for the customer; primary key of the table.'),
LAND1 string OPTIONS(description = 'Specifies the country of the customer; linked to table T005 for country codes.'),
NAME1 string(50) OPTIONS(description = 'Primary name of the customer.'),
ORT01 string(35) OPTIONS(description = 'City where the customer is located.'),
PSTLZ string OPTIONS(description = 'Postal code for the customers address.'),
REGIO string OPTIONS(description = 'Region or state of the customers location; linked to table T005S for region codes.'),
TELF1 string OPTIONS(description = 'Primary contact telephone number for the customer.')
)
OPTIONS(description = 'Table contains general data for customers, such as address details and contact information.',
friendly_name = 'Customer Master Records');
