-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.VBRP
CREATE TABLE ERP.VBRP
(
 VBELN char(10) NOT NULL COMMENT 'Billing Document Number.',
 POSNR char(6) NOT NULL COMMENT 'Billing Document Item Number.',
 MATNR char(18) COMMENT 'Material Number.',
 FKIMG decimal(13,3) COMMENT 'Billing Quantity.',

 CONSTRAINT VBELN PRIMARY KEY ( VBELN, POSNR )
)
COMMENT = 'Table stores item-level details for billing documents in the Sales and Distribution (SD) module of SAP.';
