-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.COEP
CREATE TABLE ERP.COEP
(
OBJNR   string OPTIONS(description = 'A unique identifier for the controlling object (e.g., cost center, internal order, WBS element).'),
GJAHR   string OPTIONS(description = 'Indicates the fiscal year in which the document was created.'),
PAROB   string OPTIONS(description = 'Controlling object (e.g., cost center, internal order) linked as the partner in a transaction.'),
BELNR   string OPTIONS(description = 'Unique identifier for the CO document. Links line items to the document header in the COBK table.'),
WRTTP   string OPTIONS(description = 'Defines the type of value (e.g., actual, planned, commitment).'),
WTG_001 numeric(15, 2) OPTIONS(description = 'Total Value in Transaction Currency for Period 1')
)
OPTIONS(description = 'Table stores individual line items for cost accounting documents, linking to the corresponding cost objects (e.g., cost centers, internal orders).',
friendly_name = 'Controlling Document Line Items');
