-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.lfa1
CREATE TABLE erp.lfa1
(
 LIFNR varchar(10) NOT NULL COMMENT 'Unique identifier for the vendor; primary key of the table.' CONSTRAINT pk_lfa1 PRIMARY KEY,
 NAME1 string COMMENT 'Primary name of the vendor.',
 LAND1 varchar(3) COMMENT 'Specifies the country of the vendor; linked to table T005 for country codes.',
 ORT01 string COMMENT 'City where the vendor is located.',
 PSTLZ varchar(10) COMMENT 'Postal code for the vendors address.',
 TELF1 varchar(16) COMMENT 'Primary contact telephone number for the vendor.'
)
USING DELTA
 COMMENT 'Table stores general information about vendors (suppliers), including their names, addresses, and contact details.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
