-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.LFA_1
CREATE TABLE ERP.LFA_1
(
 LIFNR  char(10) NOT NULL COMMENT 'Unique identifier for the vendor; primary key of the table.',
 NAME_1 varchar(50) COMMENT 'Primary name of the vendor.',
 LAND_1 char(3) COMMENT 'Specifies the country of the vendor; linked to table T005 for country codes.',
 ORT_01 varchar(35) COMMENT 'City where the vendor is located.',
 PSTLZ  char(10) COMMENT 'Postal code for the vendor''s address.',
 TELF_1 char(16) COMMENT 'Primary contact telephone number for the vendor.',

 CONSTRAINT PK_LFA_1 PRIMARY KEY ( LIFNR )
)
COMMENT = 'Table stores general information about vendors (suppliers), including their names, addresses, and contact details.';
