-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** ERP.T001
CREATE TABLE ERP.T001
(
BUKRS string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Company code associated with the valuation area.'),
BUTXT string(30) OPTIONS(description = 'Stores company code data')
)
OPTIONS(description = 'Table stores information about company codes in SAP, which represent separate legal entities within the system. Company codes are the highest organizational unit in Financial Accounting (FI).',
friendly_name = 'T001');
