-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.EKPO
CREATE TABLE ERP.EKPO
(
 EBELN char(10) NOT NULL COMMENT 'Unique identifier for the purchasing document; links to the EKKO table.',
 EBELP char(5) NOT NULL COMMENT 'Sequential number of the item within the purchasing document.',
 MATNR char(18) COMMENT 'Identifier for the material; links to the MARA table.',
 MENGE decimal(13,3) COMMENT 'Quantity Ordered',

 CONSTRAINT EBELN PRIMARY KEY ( EBELN, EBELP )
)
COMMENT = 'Stores detailed information for each item within purchasing documents such as purchase orders, contracts, and scheduling agreements.';
