-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.marc
CREATE TABLE erp.marc
(
 MATNR varchar(18) NOT NULL COMMENT 'Unique identifier for the material; links to the MARA table for general material data.',
 WERKS varchar(4) NOT NULL COMMENT 'Code representing the plant where the material is managed; links to the T001W table.',
 DISMM varchar(2) COMMENT 'Defines the MRP procedure for the material; links to the T438A table.',
 CONSTRAINT matnr12 PRIMARY KEY (MATNR, WERKS)
)
USING DELTA
 COMMENT 'Table stores material-specific data for each plant, such as plant-specific settings for inventory management, procurement, and MRP.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
