-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.VBRK
CREATE TABLE ERP.VBRK
(
VBELN string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Billing Document Number'),
FKDAT date OPTIONS(description = 'Billing Date'),
KUNNR string OPTIONS(description = 'Customer Number'),
NETWR numeric(13, 2) OPTIONS(description = 'Net Value of the Billing Document')
)
OPTIONS(description = 'Table stores header information for billing documents, including the customer, billing date, and billing amount.',
friendly_name = 'Billing Document Header');
