-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.ekpo
CREATE TABLE erp.ekpo
(
 EBELN varchar(10) NOT NULL COMMENT 'Unique identifier for the purchasing document; links to the EKKO table.',
 EBELP varchar(5) NOT NULL COMMENT 'Sequential number of the item within the purchasing document.',
 MATNR varchar(18) COMMENT 'Identifier for the material; links to the MARA table.',
 MENGE decimal(13,3) COMMENT 'Quantity Ordered',
 CONSTRAINT ebeln PRIMARY KEY (EBELN, EBELP)
)
USING DELTA
 COMMENT 'Stores detailed information for each item within purchasing documents such as purchase orders, contracts, and scheduling agreements.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
