-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.csks
CREATE TABLE erp.csks
(
 KOSTL varchar(10) NOT NULL COMMENT 'Unique identifier for the cost center within the controlling area.' CONSTRAINT pk_csks PRIMARY KEY,
 BUKRS varchar(4) COMMENT 'Represents the company code associated with the cost center. Linked to table T001.',
 KOSAR varchar(1) COMMENT 'Categorizes the cost center (e.g., administrative, production). Linked to table TKA05.'
)
USING DELTA
 COMMENT 'Table stores master data for cost centers, which are used in cost tracking and controlling.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
