-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.VBAP_T
CREATE TABLE ERP.VBAP_T
(
 VBELN       string(10) NOT NULL COMMENT 'Sales Document Number',
 POSNR       string(6) NOT NULL COMMENT 'Item Number',
 MATNR       string(18) COMMENT 'Material Number',
 KWMENG      decimal(13,3),
 LastUpdated timestamp NOT NULL,
 CONSTRAINT VBELN PRIMARY KEY (VBELN, POSNR)
)
 COMMENT 'Table stores item-level data for sales orders, including materials, quantities, and pricing information.';
