-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** ERP.MARA
CREATE TABLE ERP.MARA
(
MATNR string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Serves as a central repository for material master records, encompassing essential information applicable across various organizational levels.'),
MTART string OPTIONS(description = 'Classification of the material (e.g., raw material, finished product); linked to table T134.'),
MATKL string OPTIONS(description = 'Grouping of materials with similar attributes; linked to table T023.'),
MEINS string OPTIONS(description = 'Unit of Measure')
)
OPTIONS(description = 'Table stores general data about materials, such as material types, material groups, and units of measure. It is part of the Material Management (MM) module.',
friendly_name = 'MARA');
