-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.T_001_W
CREATE TABLE ERP.T_001_W
(
 WERKS  char(4) NOT NULL COMMENT 'Plant Code',
 NAME_1 varchar(40) COMMENT 'Plant Name',
 BUKRS  char(4) COMMENT 'Company Code',

 CONSTRAINT PK_T_001_W PRIMARY KEY ( WERKS )
)
COMMENT = 'Table contains plant-related information within a company code. A plant is a location where materials are produced or goods are stored.';
