-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.SILVER_CSKS
CREATE TABLE ERP.SILVER_CSKS
(
 KOSTL        varchar(10) NOT NULL COMMENT 'Unique identifier for the cost center within the controlling area.' CONSTRAINT PK_CSKS PRIMARY KEY,
 BUKRS        varchar(4) COMMENT 'Represents the company code associated with the cost center. Linked to table T001.',
 KOSAR        varchar(1) COMMENT 'Categorizes the cost center (e.g., administrative, production). Linked to table TKA05.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Table stores master data for cost centers, which are used in cost tracking and controlling.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
