-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.t001
CREATE TABLE erp.t001
(
 BUKRS varchar(4) NOT NULL COMMENT 'Company code associated with the valuation area.' CONSTRAINT pk_t001 PRIMARY KEY,
 BUTXT string COMMENT 'Stores company code data'
)
USING DELTA
 COMMENT 'Table stores information about company codes in SAP, which represent separate legal entities within the system. Company codes are the highest organizational unit in Financial Accounting (FI).'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
