-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.BKPF
CREATE TABLE ERP.BKPF
(
BELNR string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for the financial document. Assigned automatically by the system within a company code and fiscal year.'),
GJAHR string OPTIONS(description = 'Fiscal year to which the document belongs. Helps in organizing documents chronologically and aids in reporting periods.'),
BUKRS string OPTIONS(description = 'The company code for which the document is created. Identifies the legal entity responsible for the financial transaction.'),
BLART string OPTIONS(description = 'Used to determine the document category, control posting rules, and ensure accurate reporting.'),
BLDAT date OPTIONS(description = 'The date entered by the user as the document?s creation date (e.g., invoice date).')
)
OPTIONS(description = 'Table contains the header information for accounting documents, such as document number, fiscal year, and company code.',
friendly_name = 'Accounting Document Header');
