-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.bkpf
CREATE TABLE erp.bkpf
(
 BELNR varchar(10) NOT NULL COMMENT 'Unique identifier for the financial document. Assigned automatically by the system within a company code and fiscal year.' CONSTRAINT pk_bkpf PRIMARY KEY,
 GJAHR varchar(4) COMMENT 'Fiscal year to which the document belongs. Helps in organizing documents chronologically and aids in reporting periods.',
 BUKRS varchar(4) COMMENT 'The company code for which the document is created. Identifies the legal entity responsible for the financial transaction.',
 BLART varchar(2) COMMENT 'Used to determine the document category, control posting rules, and ensure accurate reporting.',
 BLDAT date COMMENT 'The date entered by the user as the document’s creation date (e.g., invoice date).'
)
USING DELTA
 COMMENT 'Table contains the header information for accounting documents, such as document number, fiscal year, and company code.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
