-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** ERP.VBAK
CREATE TABLE ERP.VBAK
(
VBELN string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Sales Document Number'),
VKORG string OPTIONS(description = 'Sales Organization'),
KUNNR string OPTIONS(description = 'Customer Number'),
ERDAT date OPTIONS(description = 'Document Creation Date')
)
OPTIONS(description = 'Table stores the header data for sales orders, including the sales organization, customer, and document creation date.',
friendly_name = 'Sales Document Header');
