-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.SILVER_KNA_1
CREATE TABLE ERP.SILVER_KNA_1
(
 KUNNR        varchar(10) NOT NULL COMMENT 'Unique identifier for the customer; primary key of the table.' CONSTRAINT PK_KNA_1 PRIMARY KEY,
 LAND_1       varchar(3) COMMENT 'Specifies the country of the customer; linked to table T005 for country codes.',
 NAME_1       string COMMENT 'Primary name of the customer.',
 ORT_01       string COMMENT 'City where the customer is located.',
 PSTLZ        varchar(10) COMMENT 'Postal code for the customers address.',
 REGIO        varchar(3) COMMENT 'Region or state of the customers location; linked to table T005S for region codes.',
 TELF_1       varchar(16) COMMENT 'Primary contact telephone number for the customer.',
 Last_Updated timestamp NOT NULL
)
USING DELTA
 COMMENT 'Table contains general data for customers, such as address details and contact information.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported', delta.feature.invariants = 'supported');
