-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.EKPO_T
CREATE TABLE ERP.EKPO_T
(
 EBELN       string(10) NOT NULL COMMENT 'Unique identifier for the purchasing document; links to the EKKO table.',
 EBELP       string(5) NOT NULL COMMENT 'Sequential number of the item within the purchasing document.',
 MATNR       string(18) COMMENT 'Identifier for the material; links to the MARA table.',
 MENGE       decimal(13,3) COMMENT 'Quantity Ordered',
 LastUpdated timestamp NOT NULL,
 CONSTRAINT EBELN PRIMARY KEY (EBELN, EBELP)
)
 COMMENT 'Stores detailed information for each item within purchasing documents such as purchase orders, contracts, and scheduling agreements.';
