-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.GLPCA_T
CREATE TABLE ERP.GLPCA_T
(
 RCLNT       string(3) COMMENT 'Identifies the client for which the data is stored.',
 BELNR       string(10) COMMENT 'The financial accounting document number.',
 GJAHR       string(4) COMMENT 'The fiscal year for the transaction.',
 BUZEI       string(3) COMMENT 'Number of Line Item Within Accounting Document',
 HKONT       string(10) COMMENT 'The general ledger account involved in the transaction.',
 DMBTR       decimal(15,2) COMMENT 'Amount in Local Currency',
 LastUpdated timestamp NOT NULL
)
 COMMENT 'Stores line item data for profit center postings.';
