-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ERP.VBRK_T
CREATE TABLE ERP.VBRK_T
(
 VBELN       string(10) NOT NULL COMMENT 'Billing Document Number' CONSTRAINT PK_VBRK PRIMARY KEY,
 FKDAT       date COMMENT 'Billing Date',
 KUNNR       string(10) COMMENT 'Customer Number',
 NETWR       decimal(13,2) COMMENT 'Net Value of the Billing Document',
 LastUpdated timestamp NOT NULL
)
 COMMENT 'Table stores header information for billing documents, including the customer, billing date, and billing amount.';
