-- ************************* SqlDBM: Databricks *************************
-- *** Generated by SqlDBM: Databricks 32 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** erp.glpca
CREATE TABLE erp.glpca
(
 RCLNT varchar(3) COMMENT 'Identifies the client for which the data is stored.',
 BELNR varchar(10) COMMENT 'The financial accounting document number.',
 GJAHR varchar(4) COMMENT 'The fiscal year for the transaction.',
 BUZEI varchar(3) COMMENT 'Number of Line Item Within Accounting Document',
 HKONT varchar(10) COMMENT 'The general ledger account involved in the transaction.',
 DMBTR decimal(15,2) COMMENT 'Amount in Local Currency'
)
USING DELTA
 COMMENT 'Stores line item data for profit center postings.'
 TBLPROPERTIES (delta.minWriterVersion = 7, delta.enableDeletionVectors = true, delta.minReaderVersion = 3, delta.checkpoint.writeStatsAsStruct = true, delta.checkpoint.writeStatsAsJson = false, delta.feature.deletionVectors = 'supported');
