-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** ERP.MAKT
CREATE TABLE ERP.MAKT
(
MATNR string NOT NULL OPTIONS(description = 'Unique identifier for the material; links to the MARA table for general material data.'),
SPRAS string NOT NULL OPTIONS(description = 'Specifies the language of the material description; linked to table T002 for language codes.'),
MAKTX string(40) OPTIONS(description = 'Provides the materials short description in the specified language.'),
 PRIMARY KEY (MATNR, SPRAS) NOT ENFORCED
)
OPTIONS(description = 'Table stores material descriptions in various languages.',
friendly_name = 'Material Descriptions');
