-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [hub_product]
CREATE TABLE [hub_product]
(
 [product_hkey]  int NOT NULL ,
 [product_sk]    int NOT NULL ,
 [sku]           nvarchar(60) NOT NULL ,
 [load_dtm]      datetime2(3) NOT NULL ,
 [record_source] nvarchar(100) NOT NULL ,

 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([product_hkey] ASC)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Hub table for Product entities', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Surrogate key for Product Hub', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product', @level2type=N'COLUMN', @level2name=N'product_hkey';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Surrogate key from source system', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product', @level2type=N'COLUMN', @level2name=N'product_sk';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Stock Keeping Unit - unique business key', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product', @level2type=N'COLUMN', @level2name=N'sku';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Load date/time of the record', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product', @level2type=N'COLUMN', @level2name=N'load_dtm';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Source system of the record', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'hub_product', @level2type=N'COLUMN', @level2name=N'record_source';
GO