-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** Intermediate.DIM_SUPPLIER
CREATE TABLE Intermediate.DIM_SUPPLIER
(
 SUPPLIERKEY    number(38,0) NOT NULL COMMENT 'Primary key for the supplier',
 SUPPLIERNAME   varchar(75) COMMENT 'Name of the supplier',
 ADDRESS        varchar(40) COMMENT 'Address of the supplier',
 NATIONKEY      number(38,0) COMMENT 'Foreign key referencing the nation',
 PHONE          varchar(16777216) COMMENT 'Contact phone number of the supplier',
 ACCOUNTBALANCE number(12,2) COMMENT 'Account balance of the supplier',
 COMMENT        varchar(303) COMMENT 'Additional comments about the supplier',
 LOAD_TIMESTAMP timestamp_ltz(9) COMMENT 'Timestamp when the record was loaded',
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( SUPPLIERKEY )
);
