-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** Intermediate.DIM_NATION
CREATE TABLE Intermediate.DIM_NATION
(
 NATIONKEY      number(38,0) NOT NULL COMMENT 'Primary key for the nation',
 NAME           varchar(25) COMMENT 'Name of the nation',
 REGIONKEY      number(38,0) COMMENT 'Foreign key referencing the region',
 COMMENT        varchar(152) COMMENT 'Additional comments about the nation',
 LOAD_TIMESTAMP timestamp_ltz(9) COMMENT 'Timestamp when the record was loaded',
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( NATIONKEY )
);
