-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** Intermediate.DIM_CUSTOMER
CREATE TABLE Intermediate.DIM_CUSTOMER
(
 CUSTKEY         number(38,0) NOT NULL,
 CUSTOMER_NAME   varchar(75),
 ADDRESS         varchar(40) COMMENT 'Address of the customer',
 NATIONKEY       number(38,0) COMMENT 'Foreign key referencing the nation',
 PHONE           varchar(16777216) COMMENT 'Contact phone number of the customer',
 ACCOUNT_BALANCE number(12,2),
 MARKET_SEGMENT  varchar(10),
 COMMENT         varchar(117) COMMENT 'Additional comments about the customer',
 LOAD_TIMESTAMP  timestamp_ltz(9) COMMENT 'Timestamp when the record was loaded',
 LAST_UPDATED    timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( CUSTKEY )
);
