-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** PLANT_DIMENSION
CREATE TABLE PLANT_DIMENSION
(
 PLANT_ID   char(4) NOT NULL COMMENT 'Unique identifier for the plant.',
 PLANT_NAME varchar(255) COMMENT 'Name of the plant.',
 LOCATION   varchar(255) COMMENT 'Geographical location of the plant.',
 MANAGER    varchar(100) COMMENT 'Name of the plant manager.',

 CONSTRAINT PK_PLANT_DIMENSION PRIMARY KEY ( PLANT_ID )
)
COMMENT = 'Dimension table for plants, storing details such as name, location, and management information.';
