-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** PLANT_DIMENSION_T
CREATE TABLE PLANT_DIMENSION_T
(
 PLANT_ID    string(4) NOT NULL COMMENT 'Unique identifier for the plant.' CONSTRAINT PK_PLANT_DIMENSION PRIMARY KEY,
 PLANT_NAME  string(255) COMMENT 'Name of the plant.',
 LOCATION    string(255) COMMENT 'Geographical location of the plant.',
 MANAGER     string(100) COMMENT 'Name of the plant manager.',
 LastUpdated timestamp NOT NULL
)
 COMMENT 'Dimension table for plants, storing details such as name, location, and management information.';
