-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** POS.Category
CREATE TABLE POS.Category
(
CategoryId numeric NOT NULL OPTIONS(description = 'A unique identifier for each category.'),
Name       string NOT NULL
)
OPTIONS(friendly_name = 'Category');
