-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.EMPLOYEE
CREATE TABLE POS.EMPLOYEE
(
EMPLOYEE_ID  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each employee.'),
FIRST_NAME   string OPTIONS(description = 'The first name of the employee.'),
LAST_NAME    string OPTIONS(description = 'The last name of the employee.'),
POSITION     string OPTIONS(description = 'The role or job position of the employee.'),
LOCATION_ID  numeric REFERENCES POS.LOCATION(LOCATION_ID) NOT ENFORCED OPTIONS(description = 'The location where the employee works, linked to the Location table.'),
CREATED_DATE date OPTIONS(description = 'The date when the employee record was created.')
)
OPTIONS(description = 'Table stores information about employees working at different business locations.',
friendly_name = 'Employee');
