-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.PurchaseOrder
CREATE TABLE POS.PurchaseOrder
(
PurchaseOrderId numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each purchase order.'),
SupplierId      numeric REFERENCES POS.Supplier(SupplierId) NOT ENFORCED OPTIONS(description = 'The supplier from whom the order was made, linked to the Supplier table.'),
OrderDate       date OPTIONS(description = 'The date when the purchase order was created.'),
TotalAmount     numeric(15, 2) OPTIONS(description = 'The total value of the purchase order.'),
Status          string OPTIONS(description = 'The status of the purchase order.')
)
OPTIONS(description = 'Table stores purchase order details from suppliers, including order date and total amount.',
friendly_name = 'PurchaseOrder');
