-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS."ORDER"
CREATE TABLE IF NOT EXISTS POS."ORDER"
(
 ORDER_ID     number NOT NULL COMMENT 'A unique identifier for each order.',
 LOC_ID       number COMMENT 'The location where the order was placed, linked to the Location table.',
 ORDER_DATE   date COMMENT 'The date when the order was placed.',
 TOTAL_AMOUNT decimal(15, 2) COMMENT 'The total value of the order.',
 STATUS       varchar2(20) COMMENT 'The status of the order (e.g., "Completed", "Pending").',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT PK_ORDER PRIMARY KEY ( ORDER_ID ),
 CONSTRAINT LOC_ID FOREIGN KEY ( LOC_ID ) REFERENCES POS.LOCATION ( LOC_ID )
)
COMMENT = 'Table stores the details for customer orders placed at the business.';
