-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.MenuItem
CREATE TABLE POS.MenuItem
(
MenuItemId  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each menu item.'),
MenuId      numeric REFERENCES POS.Menu(MenuId) NOT ENFORCED OPTIONS(description = 'The menu that the item belongs to, linked to the Menu table.'),
Name        string NOT NULL OPTIONS(description = 'The name of the menu item.'),
Description string OPTIONS(description = 'A description of the menu item.'),
Price       numeric(10, 2) NOT NULL OPTIONS(description = 'The price of the menu item.'),
IsAvailable string OPTIONS(description = 'A flag indicating if the item is currently available (Y or N).'),
CreatedDate date OPTIONS(description = 'The date when the menu item was added.')
)
OPTIONS(description = 'Table stores individual items available in a menu.',
friendly_name = 'MenuItem');
