-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.RESERVATION
CREATE TABLE IF NOT EXISTS POS.RESERVATION
(
 RESERVATION_ID   number NOT NULL COMMENT 'A unique identifier for each reservation.',
 CUSTOMER_ID      number COMMENT 'The customer who made the reservation, linked to the Customer table.',
 LOC_ID           number COMMENT 'The location where the reservation was made, linked to the Location table.',
 RESERVATION_DATE date COMMENT 'The date and time of the reservation.',
 NUMBER_OF_GUESTS number COMMENT 'The number of guests for the reservation.',
 STATUS           varchar2(20) COMMENT 'The status of the reservation (e.g., "Confirmed", "Cancelled").',
 ADDRESS_1        string NOT NULL,

 CONSTRAINT PK_RESERVATION PRIMARY KEY ( RESERVATION_ID ),
 CONSTRAINT CUSTOMER_ID FOREIGN KEY ( CUSTOMER_ID ) REFERENCES POS.CUSTOMER ( CUSTOMER_ID ),
 CONSTRAINT LOC_ID FOREIGN KEY ( LOC_ID ) REFERENCES POS.LOCATION ( LOC_ID )
)
COMMENT = 'Table stores data for customer reservations at various locations.';
