-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.PURCHASE_ORDER_ITEM
CREATE TABLE POS.PURCHASE_ORDER_ITEM
(
 PURCHASE_ORDER_ITEM_ID number NOT NULL COMMENT 'A unique identifier for each purchase order item.',
 PURCHASE_ORDER_ID      number COMMENT 'The purchase order to which the item belongs, linked to the PurchaseOrder table.',
 PRODUCT_NAME           varchar2(100) COMMENT 'The name of the product purchased.',
 QUANTITY               number COMMENT 'The quantity of the product ordered.',
 UNIT_PRICE             decimal(10, 2) COMMENT 'The price per unit of the product.',

 CONSTRAINT PK_PURCHASE_ORDER_ITEM PRIMARY KEY ( PURCHASE_ORDER_ITEM_ID ),
 CONSTRAINT PURCHASE_ORDER_ID FOREIGN KEY ( PURCHASE_ORDER_ID ) REFERENCES POS.PURCHASE_ORDER ( PURCHASE_ORDER_ID )
)
COMMENT = 'Table stores individual items included in a purchase order.';
