-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.CATEGORY_T
CREATE TABLE POS.CATEGORY_T
(
 CATEGORY_ID  decimal(10,0) NOT NULL COMMENT 'A unique identifier for each category.' CONSTRAINT PK_CATEGORY PRIMARY KEY,
 NAME         varchar2(50) NOT NULL COMMENT 'The name of the category (e.g., "Appetizers", "Entrees").',
 DESCRIPTION  varchar2(255) COMMENT 'A description of the category.',
 CREATED_DATE date COMMENT 'The date when the category was created.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Table stores the categories for menu items, helping organize products by type (e.g., appetizers, main courses, desserts).';
