-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.SUPPLIER_T
CREATE TABLE POS.SUPPLIER_T
(
 SUPPLIER_ID  decimal(10,0) NOT NULL COMMENT 'A unique identifier for each supplier' CONSTRAINT PK_SUPPLIER PRIMARY KEY,
 NAME         varchar2(100) COMMENT 'The name of the supplier.',
 CONTACT_NAME varchar2(100) COMMENT 'The name of the supplier''s primary contact.',
 PHONE        varchar2(20) COMMENT 'The phone number of the supplier.',
 ADDRESS      varchar2(200) COMMENT 'The physical address of the supplier.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Table stores information about suppliers who provide products or services to the business. Each supplier is uniquely identified by the SupplierId.';
