-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.PURCHASE_ORDER
CREATE TABLE POS.PURCHASE_ORDER
(
PURCHASE_ORDER_ID numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each purchase order.'),
SUPPLIER_ID       numeric REFERENCES POS.SUPPLIER(SUPPLIER_ID) NOT ENFORCED OPTIONS(description = 'The supplier from whom the order was made, linked to the Supplier table.'),
ORDER_DATE        date OPTIONS(description = 'The date when the purchase order was created.'),
TOTAL_AMOUNT      numeric(15, 2) OPTIONS(description = 'The total value of the purchase order.'),
STATUS            string OPTIONS(description = 'The status of the purchase order.')
)
OPTIONS(description = 'Table stores purchase order details from suppliers, including order date and total amount.',
friendly_name = 'PurchaseOrder');
