-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.RESERVATION
CREATE TABLE POS.RESERVATION
(
RESERVATION_ID   numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each reservation.'),
CUSTOMER_ID      numeric OPTIONS(description = 'The customer who made the reservation, linked to the Customer table.'),
LOCATION_ID      numeric OPTIONS(description = 'The location where the reservation was made, linked to the Location table.'),
RESERVATION_DATE date OPTIONS(description = 'The date and time of the reservation.'),
NUMBER_OF_GUESTS numeric OPTIONS(description = 'The number of guests for the reservation.'),
STATUS           string OPTIONS(description = 'The status of the reservation.'),
 CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES POS.CUSTOMER (CUSTOMER_ID) NOT ENFORCED,
 CONSTRAINT LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES POS.LOCATION (LOCATION_ID) NOT ENFORCED
)
OPTIONS(description = 'Table stores data for customer reservations at various locations.',
friendly_name = 'Reservation');
