-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.CUSTOMER_T
CREATE TABLE POS.CUSTOMER_T
(
 CUSTOMER_ID  decimal(10,0) NOT NULL COMMENT 'A unique identifier for each customer.' CONSTRAINT PK_CUSTOMER PRIMARY KEY,
 FIRST_NAME   varchar2(50) COMMENT 'The first name of the customer',
 LAST_NAME    varchar2(50) COMMENT 'The last name of the customer.',
 EMAIL        varchar2(100) COMMENT 'The email address of the customer.',
 PHONE        varchar2(20) COMMENT 'The phone number of the customer.',
 CREATED_DATE date COMMENT 'The date when the customer record was created.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Table stores details about customers who make purchases or reservations.';
