-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.dim_CUSTOMER
CREATE TABLE POS.dim_CUSTOMER
(
 CUSTOMER_ID  number NOT NULL COMMENT 'A unique identifier for each customer.',
 from_dts     timestamp_ntz(9) NOT NULL,
 to_dts       timestamp_ntz(9) NOT NULL,
 FIRST_NAME   varchar2(50) COMMENT 'The first name of the customer',
 LAST_NAME    varchar2(50) COMMENT 'The last name of the customer.',
 EMAIL        varchar2(100) COMMENT 'The email address of the customer.',
 PHONE        varchar2(20) COMMENT 'The phone number of the customer.',
 CREATED_DATE date COMMENT 'The date when the customer record was created.',
 load_dts     timestamp_ntz(9) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( CUSTOMER_ID, from_dts )
);
