-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.CUSTOMER
CREATE TABLE IF NOT EXISTS POS.CUSTOMER
(
 CUSTOMER_ID  number NOT NULL COMMENT 'A unique identifier for each customer.',
 PHONE        varchar2(20) COMMENT 'The phone number of the customer.',
 CREATED_DATE date COMMENT 'The date when the customer record was created.',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT PK_CUSTOMER PRIMARY KEY ( CUSTOMER_ID )
)
COMMENT = 'Table stores details about customers who make purchases or reservations.';
