-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.OrderDiscount
CREATE TABLE POS.OrderDiscount
(
OrderDiscountId numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for the order discount.'),
OrderId         numeric OPTIONS(description = 'The order to which the discount is applied, linked to the Order table.'),
DiscountId      numeric OPTIONS(description = 'The discount applied to the order, linked to the Discount table'),
 CONSTRAINT OrderId FOREIGN KEY (OrderId) REFERENCES POS.Order (OrderId) NOT ENFORCED,
 CONSTRAINT DiscountId FOREIGN KEY (DiscountId) REFERENCES POS.Discount (DiscountId) NOT ENFORCED
)
OPTIONS(description = 'Table stores discounts applied to individual orders.',
friendly_name = 'OrderDiscount');
