-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.CUSTOMER
CREATE TABLE POS.CUSTOMER
(
 CUSTOMER_ID  number NOT NULL COMMENT 'A unique identifier for each customer.',
 FIRST_NAME   varchar2(50) COMMENT 'The first name of the customer',
 LAST_NAME    varchar2(50) COMMENT 'The last name of the customer.',
 EMAIL        varchar2(100) COMMENT 'The email address of the customer.',
 PHONE        varchar2(20) COMMENT 'The phone number of the customer.',
 CREATED_DATE date COMMENT 'The date when the customer record was created.',

 CONSTRAINT PK_CUSTOMER PRIMARY KEY ( CUSTOMER_ID )
)
COMMENT = 'Table stores details about customers who make purchases or reservations.';
