-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.CATEGORY
CREATE TABLE POS.CATEGORY
(
 CATEGORY_ID  number NOT NULL COMMENT 'A unique identifier for each category.',
 NAME         varchar2(50) NOT NULL COMMENT 'The name of the category (e.g., "Appetizers", "Entrees").',
 DESCRIPTION  varchar2(255) COMMENT 'A description of the category.',
 CREATED_DATE date COMMENT 'The date when the category was created.',

 CONSTRAINT PK_CATEGORY PRIMARY KEY ( CATEGORY_ID )
)
COMMENT = 'Table stores the categories for menu items, helping organize products by type (e.g., appetizers, main courses, desserts).';
