-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.CUSTOMER
CREATE TABLE POS.CUSTOMER
(
CUSTOMER_ID  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each customer.'),
FIRST_NAME   string OPTIONS(description = 'The first name of the customer'),
LAST_NAME    string OPTIONS(description = 'The last name of the customer.'),
EMAIL        string OPTIONS(description = 'The email address of the customer.'),
PHONE        string OPTIONS(description = 'The phone number of the customer.'),
CREATED_DATE date OPTIONS(description = 'The date when the customer record was created.')
)
OPTIONS(description = 'Table stores details about customers who make purchases or reservations.',
friendly_name = 'Customer');
