-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.MENU_ITEM_CATEGORY
CREATE TABLE IF NOT EXISTS POS.MENU_ITEM_CATEGORY
(
 MENU_ITEM_ID number NOT NULL COMMENT 'The ID of the menu item, linked to the MenuItem table.',
 CATEGORY_ID  number NOT NULL COMMENT 'The ID of the category to which the menu item belongs, linked to the Category table.',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT MENU_ITEM_ID PRIMARY KEY ( MENU_ITEM_ID, CATEGORY_ID ),
 CONSTRAINT CATEGORY_ID FOREIGN KEY ( CATEGORY_ID ) REFERENCES POS.CATEGORY ( CATEGORY_ID ),
 CONSTRAINT MENU_ITEM_ID_1 FOREIGN KEY ( MENU_ITEM_ID ) REFERENCES POS.MENU_ITEM ( MENU_ITEM_ID )
)
COMMENT = 'Table associates menu items with categories.';
