-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.MenuItemCategory
CREATE TABLE POS.MenuItemCategory
(
MenuItemId numeric NOT NULL OPTIONS(description = 'The ID of the menu item, linked to the MenuItem table.'),
CategoryId numeric NOT NULL OPTIONS(description = 'The ID of the category to which the menu item belongs, linked to the Category table.'),
 PRIMARY KEY (MenuItemId, CategoryId) NOT ENFORCED,
 CONSTRAINT MenuItemId1 FOREIGN KEY (MenuItemId) REFERENCES POS.MenuItem (MenuItemId) NOT ENFORCED,
 CONSTRAINT CategoryId FOREIGN KEY (CategoryId) REFERENCES POS.Category (CategoryId) NOT ENFORCED
)
OPTIONS(description = 'Table associates menu items with categories.',
friendly_name = 'MenuItemCategory');
