-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** POS.Shift
CREATE TABLE POS.Shift
(
ShiftId    numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each shift record.'),
EmployeeId numeric OPTIONS(description = 'The employee working the shift, linked to the Employee table.'),
StartDate  date OPTIONS(description = 'The starting time of the shift.'),
EndDate    date OPTIONS(description = 'The ending time of the shift.')
)
OPTIONS(description = 'Table stores employee work shift details.',
friendly_name = 'Shift');
