-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.INVENTORY
CREATE TABLE POS.INVENTORY
(
 INVENTORY_ID      number NOT NULL COMMENT 'A unique identifier for each inventory record.',
 LOCATION_ID       number COMMENT 'The location of the inventory, linked to the Location table.',
 PRODUCT_NAME      varchar2(100) COMMENT 'The name of the product.',
 QUANTITY_ON_HAND  number COMMENT 'The number of items available in stock.',
 UNIT              varchar2(10) COMMENT 'The unit of measurement (e.g., "pieces", "cases").',
 LAST_UPDATED_DATE date COMMENT 'The date when the inventory was last updated.',

 CONSTRAINT PK_INVENTORY PRIMARY KEY ( INVENTORY_ID ),
 CONSTRAINT LOCATION_ID FOREIGN KEY ( LOCATION_ID ) REFERENCES POS.LOCATION ( LOCATION_ID )
)
COMMENT = 'Table tracks the stock of products at each location, including quantities and units of measure.';
