-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.SHIFT
CREATE TABLE POS.SHIFT
(
 SHIFT_ID    number NOT NULL COMMENT 'A unique identifier for each shift record.',
 EMPLOYEE_ID number COMMENT 'The employee working the shift, linked to the Employee table.',
 START_DATE  date COMMENT 'The starting time of the shift.',
 END_DATE    date COMMENT 'The ending time of the shift.',

 CONSTRAINT PK_SHIFT PRIMARY KEY ( SHIFT_ID ),
 CONSTRAINT EMPLOYEE_ID FOREIGN KEY ( EMPLOYEE_ID ) REFERENCES POS.EMPLOYEE ( EMPLOYEE_ID )
)
COMMENT = 'Table stores employee work shift details.';
