-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.FEEDBACK
CREATE TABLE POS.FEEDBACK
(
FEEDBACK_ID    numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each feedback entry.'),
CUSTOMER_ID    numeric OPTIONS(description = 'The customer who provided the feedback, linked to the Customer table.'),
ORDER_ID       numeric OPTIONS(description = 'The order that the feedback relates to, linked to the Order table.'),
RATING         numeric OPTIONS(description = 'A numeric rating provided by the customer.'),
COMMENTS       string OPTIONS(description = 'The feedback comments from the customer.'),
SUBMITTED_DATE date OPTIONS(description = 'The date when the feedback was submitted.'),
 CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES POS.CUSTOMER (CUSTOMER_ID) NOT ENFORCED,
 CONSTRAINT ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES POS.ORDER (ORDER_ID) NOT ENFORCED
)
OPTIONS(description = 'Table stores customer feedback related to orders.',
friendly_name = 'Feedback');
