-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.LOCATION
CREATE TABLE IF NOT EXISTS POS.LOCATION
(
 LOC_ID      number NOT NULL COMMENT 'A unique identifier for each location.',
 NAME        varchar2(100) NOT NULL COMMENT 'The name of the location.',
 ADDRESS     varchar2(200) COMMENT 'The address of the location.',
 CITY        varchar2(50) COMMENT 'The city where the location is based.',
 STATE       varchar2(50) COMMENT 'The state of the location.',
 POSTAL_CODE varchar2(10) COMMENT 'The postal code of the location.',
 PHONE       varchar2(20) COMMENT 'The phone number of the location',
 ADDRESS_1   string NOT NULL,

 CONSTRAINT PK_LOCATION PRIMARY KEY ( LOC_ID )
)
COMMENT = 'Table stores information about different business locations, such as restaurants, retail stores, or branches of a business.';
