-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.EMPLOYEE
CREATE TABLE IF NOT EXISTS POS.EMPLOYEE
(
 EMPLOYEE_ID  number NOT NULL COMMENT 'A unique identifier for each employee.',
 F_NAME       varchar2(50) COMMENT 'The first name of the employee.',
 LAST_NAME    varchar2(50) COMMENT 'The last name of the employee.',
 POSITION     varchar2(50) COMMENT 'The role or job position of the employee (e.g., "Cashier", "Manager").',
 LOC_ID       number COMMENT 'The location where the employee works, linked to the Location table.',
 CREATED_DATE date COMMENT 'The date when the employee record was created.',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT PK_EMPLOYEE PRIMARY KEY ( EMPLOYEE_ID ),
 CONSTRAINT LOC_ID FOREIGN KEY ( LOC_ID ) REFERENCES POS.LOCATION ( LOC_ID )
)
COMMENT = 'Table stores information about employees working at different business locations.';
