-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.MENU_ITEM_CATEGORY
CREATE TABLE POS.MENU_ITEM_CATEGORY
(
MENU_ITEM_ID numeric NOT NULL OPTIONS(description = 'The ID of the menu item, linked to the MenuItem table.'),
CATEGORY_ID  numeric NOT NULL OPTIONS(description = 'The ID of the category to which the menu item belongs, linked to the Category table.'),
 PRIMARY KEY (MENU_ITEM_ID, CATEGORY_ID) NOT ENFORCED,
 CONSTRAINT MENU_ITEM_ID_1 FOREIGN KEY (MENU_ITEM_ID) REFERENCES POS.MENU_ITEM (MENU_ITEM_ID) NOT ENFORCED,
 CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES POS.CATEGORY (CATEGORY_ID) NOT ENFORCED
)
OPTIONS(description = 'Table associates menu items with categories.',
friendly_name = 'MenuItemCategory');
