-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.Customer
CREATE TABLE POS.Customer
(
CustomerId  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each customer.'),
FirstName   string OPTIONS(description = 'The first name of the customer'),
LastName    string OPTIONS(description = 'The last name of the customer.'),
Email       string OPTIONS(description = 'The email address of the customer.'),
Phone       string OPTIONS(description = 'The phone number of the customer.'),
CreatedDate date OPTIONS(description = 'The date when the customer record was created.')
)
OPTIONS(description = 'Table stores details about customers who make purchases or reservations.',
friendly_name = 'Customer');
