-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.SUPPLIER
CREATE TABLE POS.SUPPLIER
(
SUPPLIER_ID  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each supplier'),
NAME         string OPTIONS(description = 'The name of the supplier.'),
CONTACT_NAME string OPTIONS(description = 'The name of the suppliers primary contact.'),
PHONE        string OPTIONS(description = 'The phone number of the supplier.'),
ADDRESS      string OPTIONS(description = 'The physical address of the supplier.')
)
OPTIONS(description = 'Table stores information about suppliers who provide products or services to the business. Each supplier is uniquely identified by the SupplierId.',
friendly_name = 'Supplier');
