-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.DISCOUNT
CREATE TABLE POS.DISCOUNT
(
DISCOUNT_ID   numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each discount.'),
NAME          string OPTIONS(description = 'The name of the discount.'),
DISCOUNT_TYPE string OPTIONS(description = 'Type of the discount.'),
AMOUNT        numeric(10, 2) OPTIONS(description = 'The value of the discount.'),
IS_ACTIVE     string OPTIONS(description = 'Indicates whether the discount is active (Y or N).'),
CREATED_DATE  date OPTIONS(description = 'The date the discount was created.')
)
OPTIONS(description = 'Table stores information about discount schemes that can be applied to orders or items, such as promotional discounts or loyalty program discounts.',
friendly_name = 'Discount');
