-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.Discount
CREATE TABLE POS.Discount
(
DiscountId   numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each discount.'),
Name         string OPTIONS(description = 'The name of the discount.'),
DiscountType string OPTIONS(description = 'Type of the discount.'),
Amount       numeric(10, 2) OPTIONS(description = 'The value of the discount.'),
IsActive     string OPTIONS(description = 'Indicates whether the discount is active (Y or N).'),
CreatedDate  date OPTIONS(description = 'The date the discount was created.')
)
OPTIONS(description = 'Table stores information about discount schemes that can be applied to orders or items, such as promotional discounts or loyalty program discounts.',
friendly_name = 'Discount');
