-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.ORDER
CREATE TABLE POS.ORDER
(
ORDER_ID     numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each order.'),
LOCATION_ID  numeric REFERENCES POS.LOCATION(LOCATION_ID) NOT ENFORCED OPTIONS(description = 'The location where the order was placed, linked to the Location table.'),
ORDER_DATE   date OPTIONS(description = 'The date when the order was placed.'),
TOTAL_AMOUNT numeric(15, 2) OPTIONS(description = 'The total value of the order.'),
STATUS       string OPTIONS(description = 'The status of the order.')
)
OPTIONS(description = 'Table stores the details for customer orders placed at the business.',
friendly_name = 'Order');
