-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.EMPLOYEE
CREATE TABLE POS.EMPLOYEE
(
 EMPLOYEE_ID  number NOT NULL COMMENT 'A unique identifier for each employee.',
 FIRST_NAME   varchar2(50) COMMENT 'The first name of the employee.',
 LAST_NAME    varchar2(50) COMMENT 'The last name of the employee.',
 POSITION     varchar2(50) COMMENT 'The role or job position of the employee (e.g., "Cashier", "Manager").',
 LOCATION_ID  number COMMENT 'The location where the employee works, linked to the Location table.',
 CREATED_DATE date COMMENT 'The date when the employee record was created.',

 CONSTRAINT PK_EMPLOYEE PRIMARY KEY ( EMPLOYEE_ID ),
 CONSTRAINT LOCATION_ID FOREIGN KEY ( LOCATION_ID ) REFERENCES POS.LOCATION ( LOCATION_ID )
)
COMMENT = 'Table stores information about employees working at different business locations.';
