-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.MENU
CREATE TABLE IF NOT EXISTS POS.MENU
(
 MENU_ID      number NOT NULL COMMENT 'A unique identifier for each menu.',
 LOC_ID       number COMMENT 'The location that the menu is associated with, linked to the Location table.',
 NAME         varchar2(100) NOT NULL COMMENT 'The name of the menu (e.g., "Dinner Menu").',
 DESCRIPTION  varchar2(255) COMMENT 'A description of the menu.',
 CREATED_DATE date COMMENT 'The date when the menu was created.',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT PK_MENU PRIMARY KEY ( MENU_ID ),
 CONSTRAINT LOC_ID FOREIGN KEY ( LOC_ID ) REFERENCES POS.LOCATION ( LOC_ID )
)
COMMENT = 'Table stores information about menus available at each location, including menu names and descriptions.';
