-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** POS.Supplier
CREATE TABLE POS.Supplier
(
SupplierId  numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each supplier'),
Name        string OPTIONS(description = 'The name of the supplier.'),
ContactName string OPTIONS(description = 'The name of the suppliers primary contact.'),
Phone       string OPTIONS(description = 'The phone number of the supplier.'),
Address     string OPTIONS(description = 'The physical address of the supplier.')
)
OPTIONS(description = 'Table stores information about suppliers who provide products or services to the business. Each supplier is uniquely identified by the SupplierId.',
friendly_name = 'Supplier');
