-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** POS.Employee
CREATE TABLE POS.Employee
(
EmployeeId numeric NOT NULL OPTIONS(description = 'A unique identifier for each employee.'),
FirstName  string OPTIONS(description = 'The first name of the employee.'),
LastName   string OPTIONS(description = 'The last name of the employee.'),
Position   string
)
OPTIONS(friendly_name = 'Employee');
