-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** POS.Payment
CREATE TABLE POS.Payment
(
PaymentId   numeric NOT NULL OPTIONS(description = 'A unique identifier for each payment.'),
OrderId     numeric OPTIONS(description = 'The order for which the payment was made, linked to the Order table.'),
PaymentType string
)
OPTIONS(friendly_name = 'Payment');
