-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS.DISCOUNT_T
CREATE TABLE POS.DISCOUNT_T
(
 DISCOUNT_ID   decimal(10,0) NOT NULL COMMENT 'Unique identifier for each discount.' CONSTRAINT PK_DISCOUNT PRIMARY KEY,
 NAME          varchar2(50) COMMENT 'The name of the discount.',
 DISCOUNT_TYPE varchar2(20) COMMENT 'Type of the discount (e.g., "percentage", "fixed amount").',
 AMOUNT        decimal(10, 2) COMMENT 'The value of the discount.',
 IS_ACTIVE     string(1) COMMENT 'Indicates whether the discount is active (''Y'' or ''N'').',
 CREATED_DATE  date COMMENT 'The date the discount was created.',
 LastUpdated   timestamp NOT NULL
)
 COMMENT 'Table stores information about discount schemes that can be applied to orders or items, such as promotional discounts or loyalty program discounts.';
