-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** POS.MENU
CREATE TABLE POS.MENU
(
MENU_ID      numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each menu.'),
LOCATION_ID  numeric REFERENCES POS.LOCATION(LOCATION_ID) NOT ENFORCED OPTIONS(description = 'The location that the menu is associated with, linked to the Location table.'),
NAME         string NOT NULL OPTIONS(description = 'The name of the menu.'),
DESCRIPTION  string OPTIONS(description = 'A description of the menu.'),
CREATED_DATE date OPTIONS(description = 'The date when the menu was created.')
)
OPTIONS(description = 'Table stores information about menus available at each location, including menu names and descriptions.',
friendly_name = 'Menu');
