-- ************************** SqlDBM: BigQuery **************************
-- **** Generated by SqlDBM: GBQ Demo 56 by eric.ruiz+yew@sqldbm.com ****

-- ************************************** POS.OrderItem
CREATE TABLE POS.OrderItem
(
OrderItemId numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each order item'),
OrderId     numeric OPTIONS(description = 'The order to which the item belongs, linked to the Order table.'),
MenuItemId  numeric OPTIONS(description = 'The menu item ordered, linked to the MenuItem table.'),
Quantity    numeric NOT NULL OPTIONS(description = 'The quantity of the menu item ordered.'),
UnitPrice   numeric(10, 2) NOT NULL OPTIONS(description = 'The price per unit of the menu item.'),
 CONSTRAINT OrderId FOREIGN KEY (OrderId) REFERENCES POS.Order (OrderId) NOT ENFORCED,
 CONSTRAINT MenuItemId FOREIGN KEY (MenuItemId) REFERENCES POS.MenuItem (MenuItemId) NOT ENFORCED
)
OPTIONS(description = 'Table stores the details of individual items within an order.',
friendly_name = 'OrderItem');
