-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** POS.Feedback
CREATE TABLE POS.Feedback
(
FeedbackId    numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'A unique identifier for each feedback entry.'),
CustomerId    numeric REFERENCES POS.Customer(CustomerId) NOT ENFORCED OPTIONS(description = 'The customer who provided the feedback, linked to the Customer table.'),
OrderId       numeric OPTIONS(description = 'The order that the feedback relates to, linked to the Order table.'),
Rating        numeric OPTIONS(description = 'A numeric rating provided by the customer.'),
Comments      string OPTIONS(description = 'The feedback comments from the customer.'),
SubmittedDate date OPTIONS(description = 'The date when the feedback was submitted.')
)
OPTIONS(description = 'Table stores customer feedback related to orders.',
friendly_name = 'Feedback');
