-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS_ORDER_T
CREATE TABLE POS_ORDER_T
(
 ORDER_ID     decimal(10,0) NOT NULL COMMENT 'A unique identifier for each order.' CONSTRAINT PK_ORDER PRIMARY KEY,
 CUSTOMER_ID  decimal(10,0) COMMENT 'The customer who made the order, linked to the Customer table.' CONSTRAINT CUSTOMER_ID REFERENCES POS.CUSTOMER_T,
 LOCATION_ID  decimal(10,0) COMMENT 'The location where the order was made, linked to the Location table.' CONSTRAINT LOCATION_ID REFERENCES POS.LOCATION_T,
 ORDER_DATE   date COMMENT 'The date when the order was placed.',
 TOTAL_AMOUNT decimal(10,0) COMMENT 'The total amount of the order.',
 ITEMS        varchar2(500) COMMENT 'A JSON representation of the items in the order.',
 STATUS       varchar2(20) COMMENT 'The status of the order (e.g., "Pending", "Delivered").',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Table stores details about customer orders made at various locations.';
