-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** POS_ORDER
CREATE TABLE IF NOT EXISTS POS_ORDER
(
 ORDER_ID     number NOT NULL COMMENT 'A unique identifier for each order.',
 CUSTOMER_ID  number COMMENT 'The customer who made the order, linked to the Customer table.',
 LOC_ID       number COMMENT 'The location where the order was made, linked to the Location table.',
 ORDER_DATE   date COMMENT 'The date when the order was placed.',
 TOTAL_AMOUNT number COMMENT 'The total amount of the order.',
 ITEMS        varchar2(500) COMMENT 'A JSON representation of the items in the order.',
 STATUS       varchar2(20) COMMENT 'The status of the order (e.g., "Pending", "Delivered").',
 ADDRESS_1    string NOT NULL,

 CONSTRAINT PK_ORDER PRIMARY KEY ( ORDER_ID ),
 CONSTRAINT CUSTOMER_ID FOREIGN KEY ( CUSTOMER_ID ) REFERENCES POS.CUSTOMER ( CUSTOMER_ID ),
 CONSTRAINT LOC_ID FOREIGN KEY ( LOC_ID ) REFERENCES POS.LOCATION ( LOC_ID )
)
COMMENT = 'Table stores details about customer orders made at various locations.';
