-- *************************************** SqlDBM: Snowflake ***************************************
-- * Generated by SqlDBM: Snowflake export of 'Sample - Logical Model' by eric.ruiz+yew@sqldbm.com *

-- ************************************** product
CREATE TABLE product
(
 CUSS_id number(38,0) NOT NULL,

 CONSTRAINT FK_1 FOREIGN KEY ( CUSS_id ) REFERENCES CUSS ( CUSS_id )
);
