-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** RAW.PARTSUPP
CREATE TABLE RAW.PARTSUPP
(
 PS_PARTKEY    int NOT NULL COMMENT 'Foreign key referencing the part',
 PS_SUPPKEY    int NOT NULL COMMENT 'Foreign key referencing the supplier',
 PS_AVAILQTY   int COMMENT 'Available quantity of the part supplied',
 PS_SUPPLYCOST decimal(12,2) COMMENT 'Cost of supplying the part',
 PS_COMMENT    string COMMENT 'Additional comments about the part-supplier relationship',
 LAST_UPDATED  timestamp NOT NULL,

 CONSTRAINT PK_PARTSUPP PRIMARY KEY ( PS_PARTKEY, PS_SUPPKEY ),
 CONSTRAINT FK_PARTSUPP_PART FOREIGN KEY ( PS_PARTKEY ) REFERENCES RAW.PART ( P_PARTKEY ),
 CONSTRAINT FK_PARTSUPP_SUPPLIER FOREIGN KEY ( PS_SUPPKEY ) REFERENCES RAW.SUPPLIER ( S_SUPPKEY )
);
