-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** RAW.REGION
CREATE TABLE RAW.REGION
(
 R_REGIONKEY  int NOT NULL COMMENT 'Primary key for the region',
 R_NAME       string COMMENT 'Name of the region',
 R_COMMENT    string COMMENT 'Additional comments about the region',
 LAST_UPDATED timestamp NOT NULL,

 CONSTRAINT PK_REGION PRIMARY KEY ( R_REGIONKEY )
);
