-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** RAW.NATION
CREATE TABLE RAW.NATION
(
 N_NATIONKEY  int NOT NULL COMMENT 'Primary key for the nation',
 N_NAME       string COMMENT 'Name of the nation',
 N_REGIONKEY  int COMMENT 'Foreign key referencing the region',
 N_COMMENT    string COMMENT 'Additional comments about the nation',
 LAST_UPDATED timestamp NOT NULL,

 CONSTRAINT PK_NATION PRIMARY KEY ( N_NATIONKEY ),
 CONSTRAINT FK_NATION_REGION FOREIGN KEY ( N_REGIONKEY ) REFERENCES RAW.REGION ( R_REGIONKEY )
);
