-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** RAW.SUPPLIER
CREATE TABLE RAW.SUPPLIER
(
 S_SUPPKEY    int NOT NULL COMMENT 'Primary key for the supplier',
 S_NAME       string COMMENT 'Name of the supplier',
 S_ADDRESS    string COMMENT 'Address of the supplier',
 S_NATIONKEY  int COMMENT 'Foreign key referencing the nation',
 S_PHONE      string COMMENT 'Contact phone number of the supplier',
 S_ACCTBAL    decimal(12,2) COMMENT 'Account balance of the supplier',
 S_COMMENT    string COMMENT 'Additional comments about the supplier',
 LAST_UPDATED timestamp NOT NULL,

 CONSTRAINT PK_SUPPLIER PRIMARY KEY ( S_SUPPKEY ),
 CONSTRAINT FK_SUPPLIER_NATION FOREIGN KEY ( S_NATIONKEY ) REFERENCES RAW.NATION ( N_NATIONKEY )
);
