-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SALES_FACT_T
CREATE TABLE SALES_FACT_T
(
 SALE_ID       decimal(10,0) NOT NULL COMMENT 'Unique identifier for each sales transaction.' CONSTRAINT PK_SALES_FACT PRIMARY KEY,
 DATE_ID       date NOT NULL COMMENT 'Unique identifier for the date.' CONSTRAINT FK_4 REFERENCES DATE_DIMENSION_T,
 MATERIAL_ID   string(18) COMMENT 'References the material sold in the transaction.' CONSTRAINT FK_MATERIAL_ID_74 REFERENCES SC.MATERIAL_T,
 PLANT_ID      string(4) COMMENT 'References the plant associated with the transaction.' CONSTRAINT FK_PLANT_ID_3 REFERENCES SC.PLANT_T,
 INVENTORY_ID  decimal(10,0) COMMENT 'References the inventory record for the material at the plant.' CONSTRAINT FK_INVENTORY_ID REFERENCES SC.INVENTORY_T,
 QUANTITY_SOLD decimal(15,3) COMMENT 'Quantity of the material sold.',
 REVENUE       decimal(15,2) COMMENT 'Total revenue generated by the transaction.',
 SALE_DATE_ID  date COMMENT 'Date of the sale, references the date dimension.',
 LastUpdated   timestamp NOT NULL
)
 COMMENT 'Fact table for storing sales data, capturing quantity sold, revenue, and associated material, plant, and inventory details.';
