-- ************************************** SALES_FACT
CREATE TABLE SALES_FACT (
  SALE_ID decimal(10,0) NOT NULL CONSTRAINT PK_SALES_FACT PRIMARY KEY COMMENT 'Unique identifier for each sales transaction.',
  DATE_ID date NOT NULL COMMENT 'Unique identifier for the date.',
  MATERIAL_ID string COMMENT 'References the material sold in the transaction.',
  PLANT_ID string COMMENT 'References the plant associated with the transaction.',
  INVENTORY_ID decimal(10,0) COMMENT 'References the inventory record for the material at the plant.',
  QUANTITY_SOLD decimal(10,0) COMMENT 'Quantity of the material sold.',
  REVENUE decimal(10,0) COMMENT 'Total revenue generated by the transaction.',
  SALE_DATE_ID date COMMENT 'Date of the sale, references the date dimension.',
  CONSTRAINT FK_MATERIAL_ID FOREIGN KEY (MATERIAL_ID) REFERENCES SC.MATERIAL (MATERIAL_ID),
  CONSTRAINT FK_4 FOREIGN KEY (DATE_ID) REFERENCES DATE_DIMENSION (DATE_ID),
  CONSTRAINT FK_PLANT_ID FOREIGN KEY (PLANT_ID) REFERENCES SC.PLANT (PLANT_ID),
  CONSTRAINT FK_INVENTORY_ID FOREIGN KEY (INVENTORY_ID) REFERENCES SC.INVENTORY_1 (INVENTORY_ID)
)
COMMENT 'Fact table for storing sales data, capturing quantity sold, revenue, and associated material, plant, and inventory details.';