-- ******************** SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: SqlServer Demo 56 by eric.ruiz+yew@sqldbm.com *

-- ************************************** [SAT_PRODUCT_INVENTORY_T]
CREATE TABLE [SAT_PRODUCT_INVENTORY_T]
(
 [PRODUCT_HKEY]   int NOT NULL ,
 [LOAD_DTM]       datetime2(3) NOT NULL ,
 [LOAD_END_DTM]   datetime2(3) NOT NULL ,
 [IS_CURRENT]     bit NOT NULL ,
 [HASH_DIFF]      char(32) NOT NULL ,
 [STOCK_QUANTITY] int NOT NULL ,
 [REORDER_LEVEL]  int NULL ,
 [RECORD_SOURCE]  nvarchar(100) NOT NULL ,

 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([PRODUCT_HKEY] ASC, [LOAD_DTM] ASC),
 CONSTRAINT [FK_1] FOREIGN KEY ([PRODUCT_HKEY])  REFERENCES [HUB_PRODUCT_T]([PRODUCT_HKEY]),
 CONSTRAINT [FK_2] FOREIGN KEY ([PRODUCT_HKEY])  REFERENCES [HUB_PRODUCT_T]([PRODUCT_HKEY]),
 CONSTRAINT [FK_3] FOREIGN KEY ([PRODUCT_HKEY])  REFERENCES [HUB_PRODUCT_T]([PRODUCT_HKEY])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Satellite for Product inventory information', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Foreign key to Product Hub', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'PRODUCT_HKEY';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Load date/time of the record', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'LOAD_DTM';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp of latest data in source', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'LOAD_END_DTM';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates if the record is currently active', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'IS_CURRENT';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Hash of all attributes', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'HASH_DIFF';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Current stock quantity', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'STOCK_QUANTITY';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Reorder level', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'REORDER_LEVEL';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Source system', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SAT_PRODUCT_INVENTORY_T', @level2type=N'COLUMN', @level2name=N'RECORD_SOURCE';
GO