-- ********************** SqlDBM: Microsoft SQL Server *********************
-- * Generated by SqlDBM: SqlServer Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** [sat_product_pricing]
CREATE TABLE [sat_product_pricing]
(
 [product_hkey]  int NOT NULL ,
 [load_dtm]      datetime2(3) NOT NULL ,
 [load_end_dtm]  datetime2(3) NOT NULL ,
 [is_current]    bit NOT NULL ,
 [hash_diff]     char(32) NOT NULL ,
 [price]         decimal(18, 2) NOT NULL ,
 [currency_code] nvarchar(3) NULL ,
 [record_source] nvarchar(100) NOT NULL ,

 CONSTRAINT [PK_1] PRIMARY KEY CLUSTERED ([product_hkey] ASC, [load_dtm] ASC),
 CONSTRAINT [FK_1] FOREIGN KEY ([product_hkey])  REFERENCES [hub_product]([product_hkey]),
 CONSTRAINT [FK_2] FOREIGN KEY ([product_hkey])  REFERENCES [hub_product]([product_hkey]),
 CONSTRAINT [FK_3] FOREIGN KEY ([product_hkey])  REFERENCES [hub_product]([product_hkey]),
 CONSTRAINT [FK_4] FOREIGN KEY ([product_hkey])  REFERENCES [hub_product]([product_hkey])
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Satellite for Product pricing information', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing';
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Foreign key to Product Hub', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'product_hkey';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Load date/time of the record', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'load_dtm';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Timestamp of latest data in source', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'load_end_dtm';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates if the record is currently active', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'is_current';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Hash of all attributes', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'hash_diff';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Product price', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'price';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Currency code', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'currency_code';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Source system', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'sat_product_pricing', @level2type=N'COLUMN', @level2name=N'record_source';
GO