-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.BILL_OF_MATERIALS
CREATE TABLE SC.BILL_OF_MATERIALS
(
 BOM_ID                char(10) NOT NULL COMMENT 'Unique identifier for each Bill of Materials (BOM).',
 MATERIAL_ID           char(18) COMMENT 'References the finished product associated with the BOM.',
 COMPONENT_MATERIAL_ID char(18) COMMENT 'References the material used as a component in the BOM.',
 QUANTITY              decimal(15,3) COMMENT 'The quantity of the component material required for the finished product.',

 CONSTRAINT PK_BILL_OF_MATERIALS PRIMARY KEY ( BOM_ID ),
 CONSTRAINT COMPONENT_MATERIAL_ID FOREIGN KEY ( COMPONENT_MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID ),
 CONSTRAINT MATERIAL_ID FOREIGN KEY ( MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID )
)
COMMENT = 'Tracks relationships between finished products and their component materials, including quantities.';
