-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** SC.Customer
CREATE TABLE SC.Customer
(
CustomerId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each customer.'),
CustomerName string(100) OPTIONS(description = 'The name of the customer organization or individual.'),
Country      string OPTIONS(description = 'The country code where the customer is located.'),
ContactName  string(100) OPTIONS(description = 'The primary contact person for the customer.'),
Phone        string OPTIONS(description = 'The contact phone number for the customer.')
)
OPTIONS(description = 'Stores information about customers who place orders in the supply chain.',
friendly_name = 'Customer');
