-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.CUSTOMER_T
CREATE TABLE SC.CUSTOMER_T
(
 CUSTOMER_ID   string(10) NOT NULL COMMENT 'Unique identifier for each customer.' CONSTRAINT PK_CUSTOMER PRIMARY KEY,
 CUSTOMER_NAME string(100) COMMENT 'The name of the customer organization or individual.',
 COUNTRY       string(3) COMMENT 'The country code where the customer is located.',
 CONTACT_NAME  string(100) COMMENT 'The primary contact person for the customer.',
 PHONE         string(15) COMMENT 'The contact phone number for the customer.',
 LastUpdated   timestamp NOT NULL
)
 COMMENT 'Stores information about customers who place orders in the supply chain.';
