-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.DEMAND_FORECAST
CREATE TABLE SC.DEMAND_FORECAST
(
 FORECAST_ID         number NOT NULL COMMENT 'Unique identifier for each demand forecast record.',
 MATERIAL_ID         char(18) COMMENT 'References the material for which demand is forecasted.',
 FORECAST_DATE       date COMMENT 'The date for which demand is forecasted.',
 FORECASTED_QUANTITY decimal(15,3) COMMENT 'The predicted quantity of the material needed on the forecast date.',

 CONSTRAINT PK_DEMAND_FORECAST PRIMARY KEY ( FORECAST_ID ),
 CONSTRAINT MATERIAL_ID FOREIGN KEY ( MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID )
)
COMMENT = 'Tracks forecasted material quantities based on historical data and trends.';
