-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.DEMAND_PLANNING
CREATE TABLE SC.DEMAND_PLANNING
(
 PLANNING_ID      number NOT NULL COMMENT 'Unique identifier for each demand planning record.',
 MATERIAL_ID      char(18) COMMENT 'References the material for which demand is planned.',
 PLANNING_DATE    date COMMENT 'The date associated with the demand planning.',
 PLANNED_QUANTITY decimal(15,3) COMMENT 'The planned quantity of the material for the specified date.',

 CONSTRAINT PK_DEMAND_PLANNING PRIMARY KEY ( PLANNING_ID ),
 CONSTRAINT MATERIAL_ID FOREIGN KEY ( MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID )
)
COMMENT = 'Tracks planned material quantities for future production or sales.';
