-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.DELIVERY
CREATE TABLE SC.DELIVERY
(
DELIVERY_ID    string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each delivery record.'),
SALES_ORDER_ID string REFERENCES SC.SALES_ORDER(SALES_ORDER_ID) NOT ENFORCED OPTIONS(description = 'References the sales order associated with the delivery.'),
DELIVERY_DATE  date OPTIONS(description = 'The date when the delivery occurred or is scheduled.'),
STATUS         string(20) OPTIONS(description = 'The current status of the delivery (e.g., In Transit, Delivered).')
)
OPTIONS(description = 'Tracks deliveries associated with sales orders, including status and dates.',
friendly_name = 'Delivery');
