-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.DEMAND_FORECAST_T
CREATE TABLE SC.DEMAND_FORECAST_T
(
 FORECAST_ID         decimal(10,0) NOT NULL COMMENT 'Unique identifier for each demand forecast record.' CONSTRAINT PK_DEMAND_FORECAST PRIMARY KEY,
 MATERIAL_ID         string(18) COMMENT 'References the material for which demand is forecasted.' CONSTRAINT MATERIAL_ID_9 REFERENCES SC.MATERIAL_T,
 FORECAST_DATE       date COMMENT 'The date for which demand is forecasted.',
 FORECASTED_QUANTITY decimal(15,3) COMMENT 'The predicted quantity of the material needed on the forecast date.',
 LastUpdated         timestamp NOT NULL
)
 COMMENT 'Tracks forecasted material quantities based on historical data and trends.';
