-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.Delivery
CREATE TABLE SC.Delivery
(
DeliveryId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each delivery record.'),
SalesOrderId string REFERENCES SC.SalesOrder(SalesOrderId) NOT ENFORCED OPTIONS(description = 'References the sales order associated with the delivery.'),
DeliveryDate date OPTIONS(description = 'The date when the delivery occurred or is scheduled.'),
Status       string(20) OPTIONS(description = 'The current status of the delivery (e.g., In Transit, Delivered).')
)
OPTIONS(description = 'Tracks deliveries associated with sales orders, including status and dates.',
friendly_name = 'Delivery');
