-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.DemandForecast
CREATE TABLE SC.DemandForecast
(
ForecastId         numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each demand forecast record.'),
MaterialId         string REFERENCES SC.Material(MaterialId) NOT ENFORCED OPTIONS(description = 'References the material for which demand is forecasted.'),
ForecastDate       date OPTIONS(description = 'The date for which demand is forecasted.'),
ForecastedQuantity numeric(15, 3) OPTIONS(description = 'The predicted quantity of the material needed on the forecast date.')
)
OPTIONS(description = 'Tracks forecasted material quantities based on historical data and trends.',
friendly_name = 'DemandForecast');
