-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.INVENTORY
CREATE TABLE SC.INVENTORY
(
 INVENTORY_ID      number NOT NULL COMMENT 'Unique identifier for each inventory record.',
 QUANTITY_ON_HAND  decimal(15,3) COMMENT 'The quantity of the material currently available at the plant.',
 LAST_UPDATED_DATE date COMMENT 'The last date when the inventory record was updated.',

 CONSTRAINT PK_INVENTORY PRIMARY KEY ( INVENTORY_ID )
)
COMMENT = 'Tracks the quantity of materials available at specific plants.';
