-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.Material
CREATE TABLE SC.Material
(
MaterialId    string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each material or product.'),
MaterialName  string(100) NOT NULL OPTIONS(description = 'The name or description of the material.'),
MaterialType  string OPTIONS(description = 'The type or category of the material (e.g., raw material, finished good).'),
MaterialGroup string OPTIONS(description = 'The group or classification for the material.'),
BaseUnit      string OPTIONS(description = 'The base unit of measure for the material (e.g., KG, PCS).'),
CreatedDate   date OPTIONS(description = 'The date when the material record was created.')
)
OPTIONS(description = 'Stores master data for materials and products in the supply chain.',
friendly_name = 'Material');
