-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.PRODUCTION_ORDER
CREATE TABLE SC.PRODUCTION_ORDER
(
PRODUCTION_ORDER_ID string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each production order.'),
MATERIAL_ID         string OPTIONS(description = 'References the material being produced.'),
PLANT_ID            string OPTIONS(description = 'References the plant where production is taking place.'),
QUANTITY            numeric(15, 3) OPTIONS(description = 'The quantity of the material to be produced.'),
START_DATE          date OPTIONS(description = 'The start date for the production order.'),
END_DATE            date OPTIONS(description = 'The end date or completion date of the production order.'),
STATUS              string(20) OPTIONS(description = 'The current status of the production order (e.g., In Progress, Completed).'),
 CONSTRAINT MATERIAL_ID FOREIGN KEY (MATERIAL_ID) REFERENCES SC.MATERIAL (MATERIAL_ID) NOT ENFORCED,
 CONSTRAINT PLANT_ID FOREIGN KEY (PLANT_ID) REFERENCES SC.PLANT (PLANT_ID) NOT ENFORCED
)
OPTIONS(description = 'Tracks orders for producing materials, linking them to plants and materials.',
friendly_name = 'ProductionOrder');
