-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.PURCHASE_ORDER_ITEM
CREATE TABLE SC.PURCHASE_ORDER_ITEM
(
 PURCHASE_ORDER_ITEM_ID number NOT NULL COMMENT 'Unique identifier for each purchase order item.',
 PURCHASE_ORDER_ID      char(10) COMMENT 'References the purchase order to which this item belongs.',
 MATERIAL_ID            char(18) COMMENT 'References the material being purchased in this item.',
 QUANTITY               decimal(15,3) COMMENT 'The quantity of the material ordered.',
 UNIT_PRICE             decimal(15,2) COMMENT 'The price per unit of the material.',

 CONSTRAINT PK_PURCHASE_ORDER_ITEM PRIMARY KEY ( PURCHASE_ORDER_ITEM_ID ),
 CONSTRAINT MATERIAL_ID FOREIGN KEY ( MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID ),
 CONSTRAINT PURCHASE_ORDER_ID FOREIGN KEY ( PURCHASE_ORDER_ID ) REFERENCES SC.PURCHASE_ORDER ( PURCHASE_ORDER_ID )
)
COMMENT = 'Tracks individual items within purchase orders, including materials, quantities, and pricing.';
