-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** SC.ProductionOrder
CREATE TABLE SC.ProductionOrder
(
ProductionOrderId string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each production order.'),
MaterialId        string OPTIONS(description = 'References the material being produced.'),
PlantId           string OPTIONS(description = 'References the plant where production is taking place.'),
Quantity          numeric(15, 3) OPTIONS(description = 'The quantity of the material to be produced.'),
StartDate         date OPTIONS(description = 'The start date for the production order.'),
EndDate           date OPTIONS(description = 'The end date or completion date of the production order.'),
Status            string(20) OPTIONS(description = 'The current status of the production order (e.g., In Progress, Completed).'),
 CONSTRAINT MaterialId FOREIGN KEY (MaterialId) REFERENCES SC.Material (MaterialId) NOT ENFORCED,
 CONSTRAINT PlantId FOREIGN KEY (PlantId) REFERENCES SC.Plant (PlantId) NOT ENFORCED
)
OPTIONS(description = 'Tracks orders for producing materials, linking them to plants and materials.',
friendly_name = 'ProductionOrder');
