-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.PURCHASE_ORDER_T
CREATE TABLE SC.PURCHASE_ORDER_T
(
 PURCHASE_ORDER_ID string(10) NOT NULL COMMENT 'Unique identifier for each purchase order.' CONSTRAINT PK_PURCHASE_ORDER PRIMARY KEY,
 SUPPLIER_ID       string(10) COMMENT 'References the supplier from whom the order was placed.' CONSTRAINT SUPPLIER_ID REFERENCES SC.SUPPLIER_T,
 ORDER_DATE        date COMMENT 'The date when the purchase order was created.',
 STATUS            string(20) COMMENT 'The current status of the purchase order (e.g., Pending, Received).',
 TOTAL_AMOUNT      decimal(15,2) COMMENT 'The total monetary value of the purchase order.',
 LastUpdated       timestamp NOT NULL
)
 COMMENT 'Stores purchase orders placed with suppliers, including order status and total value.';
