-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.PURCHASE_ORDER_ITEM_T
CREATE TABLE SC.PURCHASE_ORDER_ITEM_T
(
 PURCHASE_ORDER_ITEM_ID decimal(10,0) NOT NULL COMMENT 'Unique identifier for each purchase order item.' CONSTRAINT PK_PURCHASE_ORDER_ITEM PRIMARY KEY,
 PURCHASE_ORDER_ID      string(10) COMMENT 'References the purchase order to which this item belongs.' CONSTRAINT PURCHASE_ORDER_ID REFERENCES SC.PURCHASE_ORDER_T,
 MATERIAL_ID            string(18) COMMENT 'References the material being purchased in this item.' CONSTRAINT MATERIAL_ID_5666796 REFERENCES SC.MATERIAL_T,
 QUANTITY               decimal(15,3) COMMENT 'The quantity of the material ordered.',
 UNIT_PRICE             decimal(15,2) COMMENT 'The price per unit of the material.',
 LastUpdated            timestamp NOT NULL
)
 COMMENT 'Tracks individual items within purchase orders, including materials, quantities, and pricing.';
