-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** SC.Plant
CREATE TABLE SC.Plant
(
PlantId     string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each manufacturing or production plant.'),
PlantName   string(80) OPTIONS(description = 'The name of the plant.'),
Location    string(100) OPTIONS(description = 'The physical location of the plant.'),
Region      string OPTIONS(description = 'The region code where the plant operates.'),
CreatedDate date OPTIONS(description = 'The date when the plant record was created.')
)
OPTIONS(description = 'Represents manufacturing or production facilities within the supply chain.',
friendly_name = 'Plant');
