-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.PLANT_T
CREATE TABLE SC.PLANT_T
(
 PLANT_ID     string(4) NOT NULL COMMENT 'Unique identifier for each manufacturing or production plant.' CONSTRAINT PK_PLANT PRIMARY KEY,
 PLANT_NAME   string(80) COMMENT 'The name of the plant.',
 LOCATION     string(100) COMMENT 'The physical location of the plant.',
 REGION       string(3) COMMENT 'The region code where the plant operates.',
 CREATED_DATE date COMMENT 'The date when the plant record was created.',
 LastUpdated  timestamp NOT NULL
)
 COMMENT 'Represents manufacturing or production facilities within the supply chain.';
