-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.QUALITY_CHECK_T
CREATE TABLE SC.QUALITY_CHECK_T
(
 QUALITY_CHECK_ID    decimal(10,0) NOT NULL COMMENT 'Unique identifier for each quality check.' CONSTRAINT PK_QUALITY_CHECK PRIMARY KEY,
 PRODUCTION_ORDER_ID string(10) COMMENT 'References the production order associated with the quality check.' CONSTRAINT PRODUCTION_ORDER_ID REFERENCES SC.PRODUCTION_ORDER_T,
 CHECK_DATE          date COMMENT 'The date when the quality check was performed.',
 RESULT              string(20) COMMENT 'The result of the quality check (e.g., Passed, Failed).',
 NOTES               string(255) COMMENT 'Additional notes or observations from the quality check.',
 LastUpdated         timestamp NOT NULL
)
 COMMENT 'Tracks quality checks for production orders, ensuring compliance with quality standards.';
