-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.QUALITY_CHECK
CREATE TABLE SC.QUALITY_CHECK
(
QUALITY_CHECK_ID    numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each quality check.'),
PRODUCTION_ORDER_ID string REFERENCES SC.PRODUCTION_ORDER(PRODUCTION_ORDER_ID) NOT ENFORCED OPTIONS(description = 'References the production order associated with the quality check.'),
CHECK_DATE          date OPTIONS(description = 'The date when the quality check was performed.'),
RESULT              string(20) OPTIONS(description = 'The result of the quality check (e.g., Passed, Failed).'),
NOTES               string(255) OPTIONS(description = 'Additional notes or observations from the quality check.')
)
OPTIONS(description = 'Tracks quality checks for production orders, ensuring compliance with quality standards.',
friendly_name = 'QualityCheck');
