-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.QualityCheck
CREATE TABLE SC.QualityCheck
(
QualityCheckId    numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each quality check.'),
ProductionOrderId string REFERENCES SC.ProductionOrder(ProductionOrderId) NOT ENFORCED OPTIONS(description = 'References the production order associated with the quality check.'),
CheckDate         date OPTIONS(description = 'The date when the quality check was performed.'),
Result            string(20) OPTIONS(description = 'The result of the quality check (e.g., Passed, Failed).'),
Notes             string(255) OPTIONS(description = 'Additional notes or observations from the quality check.')
)
OPTIONS(description = 'Tracks quality checks for production orders, ensuring compliance with quality standards.',
friendly_name = 'QualityCheck');
