-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.QUALITY_CHECK
CREATE TABLE SC.QUALITY_CHECK
(
 QUALITY_CHECK_ID    number NOT NULL COMMENT 'Unique identifier for each quality check.',
 PRODUCTION_ORDER_ID char(10) COMMENT 'References the production order associated with the quality check.',
 CHECK_DATE          date COMMENT 'The date when the quality check was performed.',
 RESULT              varchar(20) COMMENT 'The result of the quality check (e.g., Passed, Failed).',
 NOTES               varchar(255) COMMENT 'Additional notes or observations from the quality check.',

 CONSTRAINT PK_QUALITY_CHECK PRIMARY KEY ( QUALITY_CHECK_ID ),
 CONSTRAINT PRODUCTION_ORDER_ID FOREIGN KEY ( PRODUCTION_ORDER_ID ) REFERENCES SC.PRODUCTION_ORDER ( PRODUCTION_ORDER_ID )
)
COMMENT = 'Tracks quality checks for production orders, ensuring compliance with quality standards.';
