-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.SALES_ORDER_ITEM_T
CREATE TABLE SC.SALES_ORDER_ITEM_T
(
 SALES_ORDER_ITEM_ID    decimal(10,0) NOT NULL COMMENT 'Unique identifier for each sales order item.' CONSTRAINT PK_SALES_ORDER_ITEM PRIMARY KEY,
 SALES_ORDER_ID         string(10) COMMENT 'References the sales order to which this item belongs.' CONSTRAINT SALES_ORDER_ID_65444 REFERENCES SC.SALES_ORDER_T,
 MATERIAL_ID            string(18) COMMENT 'References the material being sold in this item.' CONSTRAINT MATERIAL_ID_9678 REFERENCES SC.MATERIAL_T,
 QUANTITY               decimal(15,3) COMMENT 'The quantity of the material ordered.',
 UNIT_PRICE             decimal(15,2) COMMENT 'The price per unit of the material.',
 PURCHASE_ORDER_ITEM_ID decimal(10,0) NOT NULL COMMENT 'Unique identifier for each purchase order item.',
 LastUpdated            timestamp NOT NULL
)
 COMMENT 'Tracks individual items within sales orders, including materials, quantities, and pricing.';
