-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.SALES_ORDER_ITEM
CREATE TABLE SC.SALES_ORDER_ITEM
(
 SALES_ORDER_ITEM_ID number NOT NULL COMMENT 'Unique identifier for each sales order item.',
 SALES_ORDER_ID      char(10) COMMENT 'References the sales order to which this item belongs.',
 MATERIAL_ID         char(18) COMMENT 'References the material being sold in this item.',
 QUANTITY            decimal(15,3) COMMENT 'The quantity of the material ordered.',
 UNIT_PRICE          decimal(15,2) COMMENT 'The price per unit of the material.',

 CONSTRAINT PK_SALES_ORDER_ITEM PRIMARY KEY ( SALES_ORDER_ITEM_ID ),
 CONSTRAINT MATERIAL_ID FOREIGN KEY ( MATERIAL_ID ) REFERENCES SC.MATERIAL ( MATERIAL_ID ),
 CONSTRAINT SALES_ORDER_ID FOREIGN KEY ( SALES_ORDER_ID ) REFERENCES SC.SALES_ORDER ( SALES_ORDER_ID )
)
COMMENT = 'Tracks individual items within sales orders, including materials, quantities, and pricing.';
