-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.SalesOrder
CREATE TABLE SC.SalesOrder
(
SalesOrderId string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each sales order.'),
OrderDate    date OPTIONS(description = 'The date when the order was placed.'),
Status       string(20) OPTIONS(description = 'The current status of the sales order (e.g., Pending, Shipped).'),
TotalAmount  numeric(15, 2) OPTIONS(description = 'The total monetary value of the order.')
)
OPTIONS(description = 'Stores customer orders, including details about order status and value.',
friendly_name = 'SalesOrder');
