-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.SALES_ORDER
CREATE TABLE SC.SALES_ORDER
(
SALES_ORDER_ID string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each sales order.'),
ORDER_DATE     date OPTIONS(description = 'The date when the order was placed.'),
STATUS         string(20) OPTIONS(description = 'The current status of the sales order (e.g., Pending, Shipped).'),
TOTAL_AMOUNT   numeric(15, 2) OPTIONS(description = 'The total monetary value of the order.')
)
OPTIONS(description = 'Stores customer orders, including details about order status and value.',
friendly_name = 'SalesOrder');
