-- ************************** SqlDBM: BigQuery **************************
-- *** Generated by SqlDBM: BigQuery Demo by eric.ruiz+yew@sqldbm.com ***

-- ************************************** SC.Supplier
CREATE TABLE SC.Supplier
(
SupplierId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each supplier.'),
SupplierName string(100) OPTIONS(description = 'The name of the supplier organization.'),
ContactName  string(100) OPTIONS(description = 'The name of the primary contact person for the supplier.'),
Phone        string OPTIONS(description = 'The contact phone number for the supplier.'),
Country      string OPTIONS(description = 'The country code where the supplier is based.'),
CreatedDate  date OPTIONS(description = 'The date when the supplier record was created.')
)
OPTIONS(description = 'Contains information about suppliers who provide materials or goods.',
friendly_name = 'Supplier');
