-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.SAT_SALES_ORDER_ITEM
CREATE TABLE IF NOT EXISTS SC.SAT_SALES_ORDER_ITEM
(
 ADDRESS_1                 string NOT NULL,
 MD_5_HUB_SALES_ORDER_ITEM binary NOT NULL,
 LOAD_DTS                  timestamp_ntz(9) NOT NULL,
 SALES_ORDER_ID            char(10) COMMENT 'References the sales order to which this item belongs.',
 MATERIAL_ID               char(18) COMMENT 'References the material being sold in this item.',
 QUANTITY                  decimal(15,3) COMMENT 'The quantity of the material ordered.',
 UNIT_PRICE                decimal(15,2) COMMENT 'The price per unit of the material.',
 HASH_DIFF                 binary NOT NULL,
 REC_SRC                   varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( MD_5_HUB_SALES_ORDER_ITEM, LOAD_DTS )
);
