-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.SalesOrderItem
CREATE TABLE SC.SalesOrderItem
(
SalesOrderItemId numeric NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each sales order item.'),
SalesOrderId     string OPTIONS(description = 'References the sales order to which this item belongs.'),
MaterialId       string OPTIONS(description = 'References the material being sold in this item.'),
Quantity         numeric(15, 3) OPTIONS(description = 'The quantity of the material ordered.'),
UnitPrice        numeric(15, 2) OPTIONS(description = 'The price per unit of the material.'),
 CONSTRAINT MaterialId FOREIGN KEY (MaterialId) REFERENCES SC.Material (MaterialId) NOT ENFORCED,
 CONSTRAINT SalesOrderId FOREIGN KEY (SalesOrderId) REFERENCES SC.SalesOrder (SalesOrderId) NOT ENFORCED
)
OPTIONS(description = 'Tracks individual items within sales orders, including materials, quantities, and pricing.',
friendly_name = 'SalesOrderItem');
