-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.SUPPLIER_T
CREATE TABLE SC.SUPPLIER_T
(
 SUPPLIER_ID   string(10) NOT NULL COMMENT 'Unique identifier for each supplier.' CONSTRAINT PK_SUPPLIER PRIMARY KEY,
 SUPPLIER_NAME string(100) COMMENT 'The name of the supplier organization.',
 CONTACT_NAME  string(100) COMMENT 'The name of the primary contact person for the supplier.',
 PHONE         string(15) COMMENT 'The contact phone number for the supplier.',
 COUNTRY       string(3) COMMENT 'The country code where the supplier is based.',
 CREATED_DATE  date COMMENT 'The date when the supplier record was created.',
 LastUpdated   timestamp NOT NULL
)
 COMMENT 'Contains information about suppliers who provide materials or goods.';
