-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.Transportation
CREATE TABLE SC.Transportation
(
TransportationId string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each transportation record.'),
DeliveryId       string REFERENCES SC.Delivery(DeliveryId) NOT ENFORCED OPTIONS(description = 'References the delivery associated with the transportation.'),
TransportDate    date OPTIONS(description = 'The date when the transportation occurred.'),
Carrier          string(100) OPTIONS(description = 'The name of the carrier or logistics provider handling the transportation.'),
TrackingNumber   string(50) OPTIONS(description = 'The tracking number for the shipment.'),
Status           string(20) OPTIONS(description = 'The current status of the transportation (e.g., In Transit, Delivered).')
)
OPTIONS(description = 'Tracks transportation details for deliveries, including carriers, tracking numbers, and status.',
friendly_name = 'Transportation');
