-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.TRANSPORTATION
CREATE TABLE SC.TRANSPORTATION
(
TRANSPORTATION_ID string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each transportation record.'),
DELIVERY_ID       string REFERENCES SC.DELIVERY(DELIVERY_ID) NOT ENFORCED OPTIONS(description = 'References the delivery associated with the transportation.'),
TRANSPORT_DATE    date OPTIONS(description = 'The date when the transportation occurred.'),
CARRIER           string(100) OPTIONS(description = 'The name of the carrier or logistics provider handling the transportation.'),
TRACKING_NUMBER   string(50) OPTIONS(description = 'The tracking number for the shipment.'),
STATUS            string(20) OPTIONS(description = 'The current status of the transportation (e.g., In Transit, Delivered).')
)
OPTIONS(description = 'Tracks transportation details for deliveries, including carriers, tracking numbers, and status.',
friendly_name = 'Transportation');
