-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SC.WAREHOUSE_INVENTORY_T
CREATE TABLE SC.WAREHOUSE_INVENTORY_T
(
 WAREHOUSE_INVENTORY_ID decimal(10,0) NOT NULL COMMENT 'Unique identifier for each warehouse inventory record.' CONSTRAINT PK_WAREHOUSE_INVENTORY PRIMARY KEY,
 WAREHOUSE_ID           string(10) COMMENT 'References the warehouse storing the material.' CONSTRAINT WAREHOUSE_ID REFERENCES SC.WAREHOUSE_T,
 MATERIAL_ID            string(18) COMMENT 'References the material stored in the warehouse.' CONSTRAINT MATERIAL_ID_646 REFERENCES SC.MATERIAL_T,
 QUANTITY_ON_HAND       decimal(15,3) COMMENT 'The quantity of the material currently available in the warehouse.',
 LAST_UPDATED_DATE      date COMMENT 'The last date when the inventory record was updated.',
 LastUpdated            timestamp NOT NULL
)
 COMMENT 'Tracks material quantities stored in warehouses.';
