-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** SC.Warehouse
CREATE TABLE SC.Warehouse
(
WarehouseId   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each warehouse.'),
WarehouseName string(100) OPTIONS(description = 'The name of the warehouse.'),
Location      string(100) OPTIONS(description = 'The physical location of the warehouse.'),
Capacity      numeric(15, 2) OPTIONS(description = 'The maximum storage capacity of the warehouse, typically measured in units.'),
CreatedDate   date OPTIONS(description = 'The date when the warehouse record was created.')
)
OPTIONS(description = 'Stores details about warehouses used for storing inventory.',
friendly_name = 'Warehouse');
