-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** SC.WAREHOUSE
CREATE TABLE SC.WAREHOUSE
(
WAREHOUSE_ID   string NOT NULL PRIMARY KEY NOT ENFORCED OPTIONS(description = 'Unique identifier for each warehouse.'),
WAREHOUSE_NAME string(100) OPTIONS(description = 'The name of the warehouse.'),
LOCATION       string(100) OPTIONS(description = 'The physical location of the warehouse.'),
CAPACITY       numeric(15, 2) OPTIONS(description = 'The maximum storage capacity of the warehouse, typically measured in units.'),
CREATED_DATE   date OPTIONS(description = 'The date when the warehouse record was created.')
)
OPTIONS(description = 'Stores details about warehouses used for storing inventory.',
friendly_name = 'Warehouse');
