-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SILVER_TABLE_48
CREATE TABLE SILVER_TABLE_48
(
 COLUMN_3     string NOT NULL,
 COLUMN_4     varchar NOT NULL,
 Last_Updated timestamp NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
