-- ************************** SqlDBM: Databricks *************************
-- * Generated by SqlDBM: Databricks Demo 65 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SILVER_50
CREATE TABLE SILVER_50
(
 Last_Updated timestamp NOT NULL
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
