-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** STAGING.STG_CUSTOMER
CREATE TABLE STAGING.STG_CUSTOMER
(
 CUSTKEY        int NOT NULL COMMENT 'Primary key for the customer',
 NATIONKEY      int COMMENT 'Foreign key referencing the nation',
 NAME           string COMMENT 'Name of the customer',
 ADDRESS        string COMMENT 'Address of the customer',
 PHONE          string COMMENT 'Contact phone number of the customer',
 ACCTBAL        decimal(12,2) COMMENT 'Account balance of the customer',
 MKTSEGMENT     string COMMENT 'Market segment classification of the customer',
 COMMENT        string COMMENT 'Additional comments about the customer',
 LOAD_TIMESTAMP timestamp_ltz NOT NULL,
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_CUSTOMER PRIMARY KEY ( CUSTKEY ),
 CONSTRAINT FK_CUSTOMER_NATION FOREIGN KEY ( NATIONKEY ) REFERENCES STAGING.STG_NATION ( NATIONKEY )
);
