-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** STAGING.STG_PARTSUPP
CREATE TABLE STAGING.STG_PARTSUPP
(
 PARTKEY        int NOT NULL COMMENT 'Foreign key referencing the part',
 SUPPKEY        int NOT NULL COMMENT 'Foreign key referencing the supplier',
 AVAILQTY       int COMMENT 'Available quantity of the part supplied',
 SUPPLYCOST     decimal(12,2) COMMENT 'Cost of supplying the part',
 COMMENT        string COMMENT 'Additional comments about the part-supplier relationship',
 LOAD_TIMESTAMP timestamp_ltz NOT NULL,
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_PARTSUPP PRIMARY KEY ( PARTKEY, SUPPKEY ),
 CONSTRAINT FK_PARTSUPP_PART FOREIGN KEY ( PARTKEY ) REFERENCES STAGING.STG_PART ( PARTKEY ),
 CONSTRAINT FK_PARTSUPP_SUPPLIER FOREIGN KEY ( SUPPKEY ) REFERENCES STAGING.STG_SUPPLIER ( SUPPLIERKEY )
);
