-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** STAGING.STG_PART
CREATE TABLE STAGING.STG_PART
(
 PARTKEY        int NOT NULL COMMENT 'Primary key for the part',
 P_NAME         string COMMENT 'Name of the part',
 MFGR           string COMMENT 'Manufacturer of the part',
 BRAND          string COMMENT 'Brand of the part',
 TYPE           string COMMENT 'Type or category of the part',
 SIZE           int COMMENT 'Size of the part',
 CONTAINER      string COMMENT 'Container type used for the part',
 RETAILPRICE    decimal(12,2) COMMENT 'Retail price of the part',
 COMMENT        string COMMENT 'Additional comments about the part',
 LOAD_TIMESTAMP timestamp_ltz NOT NULL,
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_PART PRIMARY KEY ( PARTKEY )
);
