-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** STAGING.STG_ORDERS
CREATE TABLE STAGING.STG_ORDERS
(
 ORDERKEY       int NOT NULL COMMENT 'Primary key for the order',
 CUSTKEY        int COMMENT 'Foreign key referencing the customer who placed the order',
 ORDERSTATUS    string COMMENT 'Status of the order',
 TOTALPRICE     decimal(12,2) COMMENT 'Total price of the order',
 ORDERDATE      date COMMENT 'Date when the order was placed',
 ORDERPRIORITY  string COMMENT 'Priority of the order',
 CLERK          string COMMENT 'Clerk responsible for the order',
 SHIPPRIORITY   int COMMENT 'Shipping priority of the order',
 COMMENT        string COMMENT 'Additional comments about the order',
 LOAD_TIMESTAMP timestamp_ltz NOT NULL,
 LAST_UPDATED   timestamp NOT NULL,

 CONSTRAINT PK_ORDERS PRIMARY KEY ( ORDERKEY ),
 CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY ( CUSTKEY ) REFERENCES STAGING.STG_CUSTOMER ( CUSTKEY )
);
