-- ***************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: dbt + SqlDBM One Project by eric.ruiz+yew@sqldbm.com *

-- ************************************** STAGING.STG_REGION
CREATE TABLE STAGING.STG_REGION
(
 REGIONKEY      int NOT NULL COMMENT 'Primary key for the region',
 NAME           string COMMENT 'Name of the region',
 COMMENT        string COMMENT 'Additional comments about the region',
 LOAD_TIMESTAMP timestamp_ltz NOT NULL,
 LAST_UPDATED   timestamp NOT NULL,
 GEOGRAPHY_HKEY binary NOT NULL,

 CONSTRAINT PK_REGION PRIMARY KEY ( REGIONKEY ),
 CONSTRAINT FK_1 FOREIGN KEY ( GEOGRAPHY_HKEY ) REFERENCES CENTRAL_INFOMART.DIM_GEOGRAPHY ( GEOGRAPHY_HKEY )
);
