-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CATEGORYDIM
CREATE TABLE SUPPLYCHAIN.CATEGORYDIM
(
 CATEGORYKEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the product category',
 CATEGORYNAME varchar(255) NOT NULL COMMENT 'Business name of the product category',
 DESCRIPTION  varchar(500) COMMENT 'Detailed description of the category and products it contains',

 CONSTRAINT PK_1 PRIMARY KEY ( CATEGORYKEY )
)
COMMENT = 'Dimension table containing product categories, providing a standardized list of categories used to classify and organize products in the supply chain.';
