-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.PRICINGDIM
CREATE TABLE SUPPLYCHAIN.PRICINGDIM
(
 PRICINGKEY         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the pricing record',
 PRODUCTKEY         number(38,0) COMMENT 'Surrogate key linking to product; foreign key reference to product dimension',
 CUSTOMERKEY        number(38,0) COMMENT 'Surrogate key linking to customer; foreign key reference to customer dimension',
 PRICETIER          varchar(50) COMMENT 'Price tier or category (e.g., Standard, Premium, Wholesale)',
 UNITPRICE          number(10,2) COMMENT 'Selling price per unit in standard currency',
 EFFECTIVESTARTDATE date COMMENT 'Date when this pricing becomes effective',
 EFFECTIVEENDDATE   date COMMENT 'Date when this pricing expires (null if still active)',

 CONSTRAINT PK_1 PRIMARY KEY ( PRICINGKEY )
)
COMMENT = 'Dimension table maintaining pricing information including product price tiers by customer and effective date ranges for historical price tracking.';
