-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.PRODUCT
CREATE TABLE SUPPLYCHAIN.PRODUCT
(
 PRODUCTID    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the product',
 SUPPLIERID   number(38,0) NOT NULL COMMENT 'Unique identifier of the primary supplier; links to SUPPLIER',
 PRODUCTNAME  varchar(255) NOT NULL COMMENT 'Business name or description of the product',
 CATEGORY     varchar(100) COMMENT 'Product category or classification',
 UNITPRICE    number(10,2) COMMENT 'Standard selling price per unit in standard currency',
 UNITSINSTOCK number(38,0) COMMENT 'Current quantity of the product in stock across all locations',
 UNITSONORDER number(38,0) COMMENT 'Quantity of the product on open purchase orders awaiting delivery',
 REORDERLEVEL number(38,0) COMMENT 'Minimum stock level that triggers automatic reordering',
 DISCONTINUED boolean DEFAULT FALSE COMMENT 'Flag indicating whether the product is discontinued or still active (true/false)',

 CONSTRAINT PK_1 PRIMARY KEY ( PRODUCTID ),
 CONSTRAINT FK_12 FOREIGN KEY ( SUPPLIERID ) REFERENCES SUPPLYCHAIN.SUPPLIER ( SUPPLIERID )
)
COMMENT = 'Master product dimension containing product details, categorization, inventory levels, and supplier information for all sellable items.';
