-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.QUALITYCONTROLFACT
CREATE TABLE SUPPLYCHAIN.QUALITYCONTROLFACT
(
 QCID             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the quality control inspection',
 PRODUCTKEY       number(38,0) COMMENT 'Surrogate key linking to product; foreign key reference to product dimension',
 SUPPLIERKEY      number(38,0) COMMENT 'Surrogate key linking to supplier; foreign key reference to supplier dimension',
 DATEKEY          date COMMENT 'Date when the quality inspection was conducted',
 QUANTITYCHECKED  number(38,0) COMMENT 'Number of units inspected during the quality control process',
 QUANTITYREJECTED number(38,0) COMMENT 'Number of units that failed quality inspection',
 QCNOTES          varchar(500) COMMENT 'Detailed notes about quality issues, defects found, or inspection results',

 CONSTRAINT PK_1 PRIMARY KEY ( QCID )
)
COMMENT = 'Fact table recording quality control inspection results for received products, tracking quantities checked, rejected, and QC notes for supplier performance.';
