-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CUSTOMERPAYMENTS
CREATE TABLE SUPPLYCHAIN.CUSTOMERPAYMENTS
(
 PAYMENTDATE      date NOT NULL COMMENT 'Date when the payment was received or processed',
 AMOUNT           number(15,2) NOT NULL COMMENT 'Monetary amount of the payment in standard currency',
 PAYMENTMETHOD    varchar(50) COMMENT 'Method used for payment (e.g., Credit Card, Bank Transfer, Check)',
 PAYMENTREFERENCE varchar(100) COMMENT 'Reference number or confirmation code for the payment transaction',
 CUSTOMERID       number(38,0) NOT NULL COMMENT 'Unique identifier of the customer making the payment; links to CUSTOMER',
 PAYMENTID        number(38,0) NOT NULL COMMENT 'Unique identifier for the payment transaction',

 CONSTRAINT FK_17 FOREIGN KEY ( PAYMENTID ) REFERENCES SUPPLYCHAIN.SUPPLIERPAYMENTS ( PAYMENTID ),
 CONSTRAINT FK_7 FOREIGN KEY ( CUSTOMERID ) REFERENCES SUPPLYCHAIN.CUSTOMER ( CUSTOMERID )
)
COMMENT = 'Fact table recording all customer payment transactions, including payment methods, amounts, and reconciliation references for accounts receivable tracking.';
