-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.AUDITLOGFACT
CREATE TABLE SUPPLYCHAIN.AUDITLOGFACT
(
 USERID         number(38,0) NOT NULL COMMENT 'Unique identifier of the user who performed the action; links to USERDIM',
 AUDITID        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the audit log entry',
 ACTION         varchar(255) COMMENT 'Type of action performed (e.g., CREATE, UPDATE, DELETE, READ)',
 ACTIONDATE     date COMMENT 'Calendar date when the action was performed',
 ACTIONTIME     timestamp_ntz(9) COMMENT 'Exact timestamp with timezone information when the action occurred',
 ENTITYAFFECTED varchar(100) COMMENT 'Name of the business entity or table that was affected by the action',
 ENTITYID       number(38,0) COMMENT 'Unique identifier of the specific record that was affected',
 NOTES          varchar(500) COMMENT 'Additional details, context, or description of the action performed',

 CONSTRAINT FK_18 FOREIGN KEY ( USERID ) REFERENCES SUPPLYCHAIN.USERDIM ( USERID )
) WITH TAG (SUPPLYCHAIN.ACCESS_LEVEL = 'RESTRICTED')
COMMENT = 'Fact table recording all audit events and system activities within the supply chain, tracking user actions, affected entities, and timestamps for compliance and monitoring purposes.';
