-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
CREATE TABLE SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
(
 CANCELLATIONREASONKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the cancellation reason',
 REASONDESCRIPTION     varchar(255) NOT NULL COMMENT 'Text description of the reason for order cancellation',

 CONSTRAINT PK_1 PRIMARY KEY ( CANCELLATIONREASONKEY )
)
COMMENT = 'Dimension table providing standardized reasons for order cancellations, enabling detailed analysis of cancellation patterns and root causes.';
