-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.TRANSPORTVEHICLEDIM
CREATE TABLE SUPPLYCHAIN.TRANSPORTVEHICLEDIM
(
 VEHICLEKEY   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the vehicle',
 VEHICLEID    varchar(100) COMMENT 'Business identifier or asset ID for the vehicle',
 VEHICLETYPE  varchar(100) COMMENT 'Type of vehicle (e.g., Truck, Van, Trailer, Forklift)',
 CAPACITY     number(38,0) COMMENT 'Maximum load capacity in units or weight',
 LICENSEPLATE varchar(20) COMMENT 'License plate number of the vehicle',
 OPERATORNAME varchar(100) COMMENT 'Name of the primary operator or driver assigned to the vehicle',

 CONSTRAINT PK_1 PRIMARY KEY ( VEHICLEKEY )
)
COMMENT = 'Dimension table containing vehicle and transportation equipment information for fleet management and logistics operations.';
