-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: Sample/Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.TRANSPORTVEHICLEDIM
CREATE TABLE SUPPLYCHAIN.TRANSPORTVEHICLEDIM
(
 VEHICLEKEY   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''VehicleKey'' column contains data related to ''vehiclekey''.',
 VEHICLEID    varchar(100) COMMENT 'The ''VehicleID'' column contains data related to ''vehicleid''. This column likely represents an identifier.',
 VEHICLETYPE  varchar(100) COMMENT 'The ''VehicleType'' column contains data related to ''vehicletype''.',
 CAPACITY     number(38,0) COMMENT 'The ''Capacity'' column contains data related to ''capacity''.',
 LICENSEPLATE varchar(20) COMMENT 'The ''LicensePlate'' column contains data related to ''licenseplate''.',
 OPERATORNAME varchar(100) COMMENT 'The ''OperatorName'' column contains data related to ''operatorname''. This column holds name-related data.',

 CONSTRAINT PK_1 PRIMARY KEY ( VEHICLEKEY )
) WITH TAG (SUPPLYCHAIN.PII = 'YES')
COMMENT = 'A dimension table in the supply chain schema that stores descriptive attributes of transport vehicles used in logistics and distribution operations. It captures key details such as vehicle type, capacity, carrier information, and operational characteristics, enabling analysis of shipment performance, route efficiency, and fleet utilization across the supply chain network.';
