-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
CREATE TABLE IF NOT EXISTS SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
(
 CANCELLATIONREASONKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''CancellationReasonKey'' column contains data related to ''cancellationreasonkey''.',
 REASONDESCRIPTION     varchar(255) NOT NULL COMMENT 'The ''ReasonDescription'' column contains data related to ''reasondescription''.',
 ADDRESS_1             string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( CANCELLATIONREASONKEY )
);
