-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CUSTOMERFEEDBACKFACT
CREATE TABLE SUPPLYCHAIN.CUSTOMERFEEDBACKFACT
(
 FEEDBACKID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the feedback entry',
 CUSTOMERKEY      number(38,0) COMMENT 'Surrogate key linking to customer; foreign key reference to customer dimension',
 PRODUCTKEY       number(38,0) COMMENT 'Surrogate key linking to product; foreign key reference to product dimension',
 DATEKEY          date COMMENT 'Date when the feedback was submitted',
 FEEDBACKRATING   number(38,0) COMMENT 'Numeric rating score provided by the customer (typically 1-5 or similar scale)',
 FEEDBACKCOMMENTS varchar(500) COMMENT 'Text comments and detailed feedback provided by the customer',

 CONSTRAINT PK_1 PRIMARY KEY ( FEEDBACKID )
)
COMMENT = 'Fact table capturing customer feedback and ratings for products, enabling analysis of customer satisfaction, product quality perception, and feedback trends.';
