-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 78 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ACMECORP.SUPPLYCHAIN.SUPPLIERPAYMENTTERMSDIM
CREATE TABLE ACMECORP.SUPPLYCHAIN.SUPPLIERPAYMENTTERMSDIM
(
 PAYMENTTERMSKEY        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''PaymentTermsKey'' column contains data related to ''paymenttermskey''.',
 SUPPLIERKEY            number(38,0) COMMENT 'The ''SupplierKey'' column contains data related to ''supplierkey''.',
 PAYMENTTERMDESCRIPTION varchar(255) COMMENT 'The ''PaymentTermDescription'' column contains data related to ''paymenttermdescription''.',

 CONSTRAINT PK_1 PRIMARY KEY ( PAYMENTTERMSKEY )
);
