-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.INVENTORYSHRINKAGEFACT
CREATE TABLE SUPPLYCHAIN.INVENTORYSHRINKAGEFACT
(
 SHRINKAGEID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the shrinkage event',
 PRODUCTKEY        number(38,0) COMMENT 'Surrogate key linking to product; foreign key reference to product dimension',
 WAREHOUSEKEY      number(38,0) COMMENT 'Surrogate key linking to warehouse; foreign key reference to warehouse dimension',
 DATEKEY           date COMMENT 'Date when the shrinkage was discovered or recorded',
 SHRINKAGEQUANTITY number(38,0) COMMENT 'Quantity of inventory lost or shrunk',
 SHRINKAGEREASON   varchar(255) COMMENT 'Explanation of shrinkage cause (e.g., Theft, Damage, Obsolescence, Administrative Error)',

 CONSTRAINT PK_1 PRIMARY KEY ( SHRINKAGEID )
)
COMMENT = 'Fact table recording inventory shrinkage events including quantity lost and reasons (damage, theft, obsolescence), supporting inventory accuracy analysis.';
