-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.SUPPLIER
CREATE TABLE SUPPLYCHAIN.SUPPLIER
(
 SUPPLIERID   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the supplier',
 SUPPLIERNAME varchar(255) NOT NULL COMMENT 'Legal or registered name of the supplier',
 CONTACTNAME  varchar(255) COMMENT 'Name of the primary contact person at the supplier',
 CONTACTTITLE varchar(255) COMMENT 'Job title or role of the contact person',
 ADDRESS      varchar(255) COMMENT 'Street address of the supplier location',
 CITY         varchar(100) COMMENT 'City where the supplier is located',
 STATE        varchar(100) COMMENT 'State or province where the supplier is located',
 ZIPCODE      varchar(20) COMMENT 'Postal or ZIP code of the supplier location',
 COUNTRY      varchar(100) COMMENT 'Country where the supplier is located',
 PHONE        varchar(20) COMMENT 'Primary phone number for contacting the supplier',
 EMAIL        varchar(100) COMMENT 'Primary email address for contacting the supplier',
 WEBSITE      varchar(100) COMMENT 'Web address or URL of the supplier''s website',

 CONSTRAINT PK_1 PRIMARY KEY ( SUPPLIERID )
) WITH TAG (SUPPLYCHAIN.PII = 'YES')
COMMENT = 'Master dimension table containing supplier information, contact details, and classification; serves as the primary reference for all sourcing and procurement activities.';
