-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.PURCHASEORDER
CREATE TABLE SUPPLYCHAIN.PURCHASEORDER
(
 PURCHASEORDERID number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the purchase order',
 ORDERDATE       date NOT NULL COMMENT 'Date when the purchase order was created',
 DELIVERYDATE    date COMMENT 'Expected or actual date of delivery from the supplier',
 STATUS          varchar(50) NOT NULL COMMENT 'Current status of the purchase order (e.g., Open, Received, Cancelled)',
 TOTALAMOUNT     number(15,2) COMMENT 'Total order value in standard currency',
 SUPPLIERID      number(38,0) NOT NULL COMMENT 'Unique identifier of the supplier; links to SUPPLIER',

 CONSTRAINT PK_1 PRIMARY KEY ( PURCHASEORDERID ),
 CONSTRAINT FK_16 FOREIGN KEY ( SUPPLIERID ) REFERENCES SUPPLYCHAIN.SUPPLIER ( SUPPLIERID )
)
COMMENT = 'Fact table containing all purchase orders placed with suppliers, tracking order dates, delivery status, and financial commitments.';
