-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 78 by eric.ruiz+yew@sqldbm.com *

-- ************************************** ACMECORP.SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
CREATE TABLE ACMECORP.SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
(
 CANCELLATIONREASONKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''CancellationReasonKey'' column contains data related to ''cancellationreasonkey''.',
 REASONDESCRIPTION     varchar(255) NOT NULL COMMENT 'The ''ReasonDescription'' column contains data related to ''reasondescription''.',

 CONSTRAINT PK_1 PRIMARY KEY ( CANCELLATIONREASONKEY )
);
