-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.SHIPPINGINCIDENTFACT
CREATE TABLE SUPPLYCHAIN.SHIPPINGINCIDENTFACT
(
 INCIDENTID     number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the shipping incident',
 ZONEKEY        number(38,0) NOT NULL COMMENT 'Surrogate key linking to warehouse zone; foreign key reference to warehouse zone dimension',
 ORDERSTATUSKEY number(38,0) NOT NULL COMMENT 'Surrogate key linking to order status; foreign key reference to order status dimension',
 SHIPMENTID     number(38,0) NOT NULL COMMENT 'Unique identifier of the affected shipment; links to SHIPMENT',
 DATEKEY        date COMMENT 'Date when the incident was reported or discovered',
 INCIDENTTYPE   varchar(50) COMMENT 'Type or category of the incident (e.g., Delay, Damage, Missing, Lost)',
 RESOLUTION     varchar(255) COMMENT 'Description of the resolution or corrective action taken',

 CONSTRAINT PK_1 PRIMARY KEY ( INCIDENTID, ZONEKEY, ORDERSTATUSKEY ),
 CONSTRAINT FK_2 FOREIGN KEY ( ZONEKEY ) REFERENCES SUPPLYCHAIN.WAREHOUSEZONEDIM ( ZONEKEY ),
 CONSTRAINT FK_3 FOREIGN KEY ( ORDERSTATUSKEY ) REFERENCES SUPPLYCHAIN.ORDERSTATUSDIM ( ORDERSTATUSKEY ),
 CONSTRAINT FK_8 FOREIGN KEY ( SHIPMENTID ) REFERENCES SUPPLYCHAIN.SHIPMENT ( SHIPMENTID )
)
COMMENT = 'Fact table recording shipping incidents (delays, damage, exceptions) with warehouse zones and resolutions for supply chain risk analysis.';
