-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ENVIRONMENTALIMPACTFACT
CREATE TABLE SUPPLYCHAIN.ENVIRONMENTALIMPACTFACT
(
 IMPACTID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the environmental impact record',
 DATEKEY        date COMMENT 'Date of the impact measurement or shipment',
 EMISSIONSCO2KG number(10,2) COMMENT 'Carbon dioxide emissions in kilograms',
 SHIPMENTID     number(38,0) NOT NULL COMMENT 'Unique identifier of the associated shipment; links to SHIPMENT',

 CONSTRAINT PK_1 PRIMARY KEY ( IMPACTID ),
 CONSTRAINT FK_13 FOREIGN KEY ( SHIPMENTID ) REFERENCES SUPPLYCHAIN.SHIPMENT ( SHIPMENTID )
)
COMMENT = 'Fact table tracking environmental impact metrics such as carbon emissions associated with shipments, supporting sustainability and ESG reporting.';
