-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERS
CREATE TABLE SUPPLYCHAIN.ORDERS
(
 ORDERID      number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique identifier for the order',
 SHIPMENTID   number(38,0) NOT NULL COMMENT 'Unique identifier of the associated shipment; links to SHIPMENT',
 CUSTOMERID   number(38,0) NOT NULL COMMENT 'Unique identifier of the customer placing the order; links to CUSTOMER',
 ORDERDATE    date NOT NULL COMMENT 'Date when the order was placed',
 REQUIREDDATE date NOT NULL COMMENT 'Expected or promised delivery date specified at order placement',
 SHIPPEDDATE  date COMMENT 'Date when the order was actually shipped from the warehouse',
 STATUS       varchar(50) NOT NULL COMMENT 'Current status of the order (e.g., Pending, Processing, Shipped, Delivered, Cancelled)',
 TOTALAMOUNT  number(15,2) COMMENT 'Total monetary value of the order in standard currency',

 CONSTRAINT PK_1 PRIMARY KEY ( ORDERID ),
 CONSTRAINT FK_19 FOREIGN KEY ( SHIPMENTID ) REFERENCES SUPPLYCHAIN.SHIPMENT ( SHIPMENTID ),
 CONSTRAINT FK_6 FOREIGN KEY ( CUSTOMERID ) REFERENCES SUPPLYCHAIN.CUSTOMER ( CUSTOMERID )
) WITH TAG (SUPPLYCHAIN.ACCESS_LEVEL = 'RESTRICTED', SUPPLYCHAIN.DATA_OWNER = 'SUPPLYCHAINTEAM')
COMMENT = 'Core fact table containing all customer orders with shipment, delivery, and financial details; primary order transaction record.';
