-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERSTATUSDIM
CREATE TABLE SUPPLYCHAIN.ORDERSTATUSDIM
(
 ORDERSTATUSKEY    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the order status',
 STATUSDESCRIPTION varchar(255) NOT NULL COMMENT 'Detailed description of the order status and its meaning',

 CONSTRAINT PK_1 PRIMARY KEY ( ORDERSTATUSKEY )
)
COMMENT = 'Dimension table defining all possible order statuses with descriptions, standardizing order state values for consistent reporting.';
