-- ********************************** SqlDBM: Snowflake *********************************
-- * Generated by SqlDBM: Enterprise Data Model - Snowflake by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.PRODUCTLIFECYCLEDIM
CREATE TABLE SUPPLYCHAIN.PRODUCTLIFECYCLEDIM
(
 LIFECYCLEKEY       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique surrogate key for the product lifecycle record',
 PRODUCTKEY         number(38,0) COMMENT 'Surrogate key linking to product; foreign key reference to product dimension',
 LIFECYCLESTAGE     varchar(50) COMMENT 'Current lifecycle stage of the product (e.g., Introduction, Growth, Maturity, Decline)',
 EFFECTIVESTARTDATE date COMMENT 'Date when the product entered this lifecycle stage',
 EFFECTIVEENDDATE   date COMMENT 'Date when the product exited this lifecycle stage (null if current stage)',

 CONSTRAINT PK_1 PRIMARY KEY ( LIFECYCLEKEY )
)
COMMENT = 'Dimension table tracking product lifecycle stages over time, supporting analysis of products by maturity and market phase.';
