-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 78 by eric.ruiz+yew@sqldbm.com *

-- ************************************** table_43
CREATE TABLE table_43
(
 ZONEKEY number(38,0) NOT NULL COMMENT 'The ''ZoneKey'' column contains data related to ''zonekey''.',

 CONSTRAINT FK_1 FOREIGN KEY ( ZONEKEY ) REFERENCES SUPPLYCHAIN.WAREHOUSEZONEDIM ( ZONEKEY )
);
