-- ************************** SqlDBM: BigQuery **************************
-- ***** Generated by SqlDBM: GBQ Demo1 by eric.ruiz+yew@sqldbm.com *****

-- ************************************** TABLE_77
CREATE TABLE TABLE_77
(
column1  NOT NULL PRIMARY KEY NOT ENFORCED,
column2  NOT NULL
)
OPTIONS(friendly_name = 'table_77');
