-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 35 by eric.ruiz+yew@sqldbm.com *

-- ************************************** table_41
CREATE TABLE table_41
(
 WAREHOUSEID number(38,0) NOT NULL COMMENT 'The ''''WarehouseID'''' column contains data related to ''''warehouseid''''. This column likely represents an identifier.',

 CONSTRAINT FK_1 FOREIGN KEY ( WAREHOUSEID ) REFERENCES SUPPLYCHAIN.WAREHOUSE ( WAREHOUSEID )
);
