-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** TABLE_129
CREATE TABLE IF NOT EXISTS TABLE_129
(
 F_NAME    varchar2(50) COMMENT 'The first name of the customer',
 LAST_NAME varchar2(50) COMMENT 'The last name of the customer.',
 EMAIL     varchar2(100) COMMENT 'The email address of the customer.',
 NAME_1    varchar(50) COMMENT 'Primary name of the customer.',
 ORT_01    varchar(35) COMMENT 'City where the customer is located.',
 ADDRESS_1 string NOT NULL
);
