-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: Sample/Sample - Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** TABLE_127
CREATE TABLE TABLE_127
(
 LAND_1        char(3) COMMENT 'Specifies the country of the customer; linked to table T005 for country codes.',
 NAME_1        varchar(50) COMMENT 'Primary name of the customer.',
 LAST_NAME     varchar2(50) COMMENT 'The last name of the customer.',
 CUSTOMER_NAME varchar(100) COMMENT 'The name of the customer organization or individual.',
 COUNTRY       char(3) COMMENT 'The country code where the customer is located.',
 EMAIL         varchar2(100) COMMENT 'The email address of the customer.',
 ADDRESS       string NOT NULL
);
