-- ************************** SqlDBM: BigQuery **************************
-- ****** Generated by SqlDBM: BQ Demo by eric.ruiz+yew@sqldbm.com ******

-- ************************************** table_77
CREATE TABLE table_77
(
)
OPTIONS(friendly_name = 'table_77');
