-- ************************** SqlDBM: Snowflake *************************
-- ***** Generated by SqlDBM: Data Warehouse by eric.ruiz@sqldbm.com ****
-- ************************************** testing123
CREATE TABLE testing123
(
 testing123 varchar(50) NOT NULL
);
