-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Data Warehouse, v10 vs v9 by eric.ruiz@sqldbm.com *

ALTER TABLE testing123
    DROP COLUMN newcolumn;