-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Data Warehouse, v11 vs v10 by eric.ruiz@sqldbm.com *

ALTER TABLE testing123
    ADD COLUMN NewColumn123 varchar NOT NULL;