-- *************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Data Warehouse, v9 vs v8 by eric.ruiz@sqldbm.com *

ALTER TABLE EDW.DimAccount
    ALTER COLUMN Operator COMMENT '<a href="https://sqldbm.com/Home/">
    <img src="smiley.gif" alt="HTML tutorial" style="width:42px;height:42px;">
</a>';

ALTER TABLE testing123
    ADD COLUMN newcolumn ;