-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Eaton Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** VG_WARRANTY_ANALYTICS_SA.CC_CLAIM_DETAILS_T
CREATE TABLE VG_WARRANTY_ANALYTICS_SA.CC_CLAIM_DETAILS_T
(
 CN                           varchar(16777216),
 CREATED                      timestamp_ntz(9),
 CREATEDBY                    varchar(16777216),
 CLAIMCLOSEDATE               timestamp_ntz(9),
 CLAIMSTATUS                  varchar(16777216),
 CLAIMTYPE                    varchar(16777216),
 CLAIMSOURCE                  varchar(16777216),
 VIN                          varchar(16777216),
 DEALERCODE                   varchar(16777216),
 PRODUCTCLASS                 varchar(16777216),
 PAYTOACCOUNT                 varchar(16777216),
 PAYTOACCOUNTNAME             varchar(16777216),
 PAYTOACCOUNTCRMID            varchar(16777216),
 SERVICEPROVIDERNAME          varchar(16777216),
 SERVICEPROVIDERCRMID         varchar(16777216),
 X_TRANS_CLUTCH               varchar(16777216),
 TRANSMODELCLUTCHINSTALLATION varchar(16777216),
 CLAIMCATEGORY                varchar(16777216),
 CLAIMANTCLAIM                varchar(16777216),
 LAST_MODIFIED                timestamp_ntz(9)
);
