-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: Eaton Data Model by eric.ruiz+yew@sqldbm.com *

-- ************************************** VG_WARRANTY_ANALYTICS_SA.SIEBEL_ACTIVITY_T
CREATE TABLE VG_WARRANTY_ANALYTICS_SA.SIEBEL_ACTIVITY_T
(
 FK_CLAIM                          varchar(16777216) COMMENT 'Foreign key linking to a claim.',
 FK_ORDER_ITEM                     varchar(16777216) COMMENT 'Foreign key referencing the order item.',
 PK_SIEBEL_ACTIVITY                varchar(16777216) COMMENT 'Primary key for the activity record.',
 FK_SIEBEL_POSITION_OWNER_PR_HELD  varchar(16777216) COMMENT 'Position owner reference.',
 FK_SIEBEL_OPPORTUNITY             varchar(16777216) COMMENT 'Foreign key linking to an opportunity.',
 FK_SIEBEL_OPPORTUNITY_PRIMARY     varchar(16777216) COMMENT 'Primary opportunity reference.',
 FK_SIEBEL_SERVICE_REQUEST_PRIMARY varchar(16777216) COMMENT 'Primary service request reference.',
 FK_SIEBEL_SERVICE_REQUEST_SRA     varchar(16777216) COMMENT 'Service request reference in Siebel.',
 FK_SIEBEL_ADDRESS_TARGET_OU       varchar(16777216) COMMENT 'Target organizational unit address.',
 FST_NAME                          varchar(16777216) COMMENT 'First name of the assigned person.',
 LAST_NAME                         varchar(16777216) COMMENT 'Last name of the assigned person.',
 ASSIGNEDTO                        varchar(16777216) COMMENT 'Person assigned to the activity.',
 ASSIGNEDTOTEAM                    varchar(16777216) COMMENT 'Team responsible for the activity.',
 SERVICEREQUESTNUM                 varchar(16777216) COMMENT 'Service request number linked to the activity.',
 PRIORITY                          varchar(16777216) COMMENT 'Priority level of the activity.',
 SR_PRIORITY                       varchar(16777216) COMMENT 'Service request priority level.',
 CN                                varchar(16777216) COMMENT 'Claim number associated with this activity.',
 SR_CAT_TYPE                       varchar(16777216) COMMENT 'Service request category type.',
 SR_SUBTYPE                        varchar(16777216) COMMENT 'Subtype of the service request.',
 SR_STATUS                         varchar(16777216) COMMENT 'Current status of the service request.',
 SR_CREATED_DT                     timestamp_ntz(9) COMMENT 'Date when the service request was created.',
 SR_LAST_UPD_DT                    timestamp_ntz(9) COMMENT 'Last update timestamp for the service request.',
 SR_ACT_CLOSE_DT                   timestamp_ntz(9) COMMENT 'Actual completion date of the service request.',
 CRMACTIVITYNUMBER                 varchar(16777216) COMMENT 'CRM-generated activity number.',
 CREATEDDATE                       timestamp_ntz(9) COMMENT 'Date the activity was created.',
 ENDDUEDATE                        timestamp_ntz(9) COMMENT 'Planned completion date for the activity.',
 ACTUALCOMPLETIONDATE              timestamp_ntz(9) COMMENT 'Date when the activity was actually completed.',
 CREATEDBY                         varchar(16777216) COMMENT 'User who created the activity.',
 ACTIVITYSUBTYPE                   varchar(16777216) COMMENT 'Subtype of the activity.',
 ACTIVITYTYPE                      varchar(16777216) COMMENT 'Type of activity performed.',
 ACTIVITYSUMMARY                   varchar(16777216) COMMENT 'Summary description of the activity.',
 ACTIVITYCOMMENTS                  varchar(16777216) COMMENT 'Additional comments about the activity.',
 ACTIVITYSTATUS                    varchar(16777216) COMMENT 'Current status of the activity.',
 ACCOUNT_NAME                      varchar(16777216) COMMENT 'Associated account name.',
 ACTIVITYTATCREATED                number(22,7) COMMENT 'Turnaround time from creation to resolution.',
 ACTIVITYTATPLANNED                number(22,7) COMMENT 'Planned turnaround time for activity completion.',
 ACT_CREATED_BY_NAME               varchar(16777216) COMMENT 'Name of the user who created the activity.'
)
COMMENT = 'Stores details about Siebel activities related to claims, including assignments, statuses, and completion times.';
